### ISSUE TITLE
SDM665 SUPPORT?

### ISSUE THREAD

**Issue by adjexpress** [bkerler/edl#10]
Hi
Thanks for great work.
I own xiaomi sdm665 device which is dead
There is no msmid for sdm665 in edl.py
and no chance of dumping pbl with your tool.
Is this about  secure loading on xiaomi devices or something wrong about qcom
And two thing else 
Do you tried to fetch signature out of pbl and patch and resign loader to bypass secure load?
Is it possible to load sbl or aboot or boot image through firehose to complete boot from usb ?

**Comment by bkerler** [comment]
Which device is that from xiaomi ?
I might try to add secure edl for xiaomi soon.
Patching and resigning is only possible if you have the right root ca key. The newer edl have el1 instead of el3 and aarch64 prevents soft reboot, so I don't think it would work, but I might be wrong.

**Comment by adjexpress** [comment]
My device is Mi A3.
I think that some keys must be readable and reusable from pbl.
Or maybe there's a way to boot system at least until  fastboot through USB , by sending a package of  binaries through firehose ,but how to build that and bypass signature verification?!

**Comment by bkerler** [comment]
All newer xiaomi devices use signed authentification for talking to edl using a custom "sig" command. This is a customisation that I cannot add as long as I do not own the private keys needed for signing the sig request (only xiaomi has them). So, you need to use miflash using an authorized mi account for flashing.

**Comment by serj-kzv** [comment]
**FYI** According this forum https://c.mi.com/oc/thread-3144073-1-0.html?mobile=no Xiaomi blocked possibility to use EDL for all non Service Center Mi Accounts. Also I could not to use MiFlash or event leaked MiFlashPro to install firmware through EDL.

But I successfully installed firmware on my phone and unbrick my phone with custom **prog_firehose_ddr.elf** file and with custom ufs partition images. Some people wrote that it was a Service Center firmware, I don't know if it was true. I have a phone with **Qualcomm Snapdragon 665**.

Firmware installing was possible with **QFIL** utility. I don't know if it is official leaked utility or an unofficial utility. Whereas with MiFlash and MiFlashPro I got an EDL Authorization error.

**Comment by serj-kzv** [comment]
The phone was unbricked with the guide https://c.mi.com/thread-3527044-1-0.html

**Comment by serj-kzv** [comment]
I mean all you need to work with Xiaomi phone is right **prog_firehose_ddr.elf**, drivers and **QFIL**. I don't know how to work Sahara or Firehose protocols. But I can say that I didn't enter an additional commands with a sig.

**Comment by bkerler** [comment]
I've added the xiaomi auth protocol to the current edl. There are no "patched" loaders. There were some loaders without auth in the transitioning time. For most xiaomi devices, edl should work (except newer xiaomi with additional security)

**Comment by pyro556666** [comment]
> I mean all you need to work with Xiaomi phone is right **prog_firehose_ddr.elf**, drivers and **QFIL**. I don't know how to work Sahara or Firehose protocols. But I can say that I didn't enter an additional commands with a sig.
> 
> @bkerler @adjexpress



> **FYI** According this forum https://c.mi.com/oc/thread-3144073-1-0.html?mobile=no Xiaomi blocked possibility to use EDL for all non Service Center Mi Accounts. Also I could not to use MiFlash or even leaked MiFlashPro to install firmware through EDL.
> 
> But I successfully installed firmware on my phone and unbrick my phone with custom **prog_firehose_ddr.elf** file and with custom ufs partition images. Some people wrote that it was a Service Center firmware, I don't know if it was true. I have a phone with **Qualcomm Snapdragon 665**.
> 
> Firmware installing was possible with **QFIL** utility. I don't know if it is official leaked utility or an unofficial utility. Whereas with MiFlash and MiFlashPro I got an EDL Authorization error.

Can you provide me with the patched firehose ?
mi flash is showing "write time out device may be disconnected
