### ISSUE TITLE
HDK 8250 could not decet my device 

### ISSUE THREAD

**Issue by pavankn** [bkerler/edl#104]
Hi , Trying this on HDK 8250 and getting this error , this is a UFS based device

------------------------
HWID:              0x001560e100000000 (MSM_ID:0x001560e1,OEM_ID:0x0000,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0xd40eee56f3194665574109a39267724ae7944134cd53cb767e293d3c40497955
Serial:            0xb2bbe8e3

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (001560e100000000_d40eee56f3194665_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}

![HDK8250](https://user-images.githubusercontent.com/4539056/121990727-e2a56280-cdbb-11eb-8926-595c1a786278.jpeg)

**Comment by bkerler** [comment]
Hi, you need to use the correct firehose programmer which you got with the HDK and name it as 001560e100000000_d40eee56f3194665_FHPRG.bin and then copy to the Loaders directory, or use the --loader option instead.
