### ISSUE TITLE
List index out of range - firehose_client.py (line 157) - Redmi 5 Plus 

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#108]
Guys, could you give me a hand with this?

While trying to execute edl.py rf mem.bin, edl.py returned this error:

```
Traceback (most recent call last):
  File "/home/leandro/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/leandro/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/leandro/edl/edl.py", line 368, in <module>
    base.run()
  File "/home/leandro/edl/edl.py", line 350, in run
    fh.handle_firehose(cmd, options)
  File "/home/leandro/edl/Library/firehose_client.py", line 301, in handle_firehose
    storageinfo = self.get_storage_info()
  File "/home/leandro/edl/Library/firehose_client.py", line 157, in get_storage_info
    rs = info.split("INFO: ")[1]
IndexError: list index out of range

Process finished with exit code 1

```

![Screenshot_2_meg7-storage-info](https://user-images.githubusercontent.com/4167122/123529456-56017b00-d6be-11eb-9995-4e9bb77961ab.png)

**Dump of variable VAL**

```
[True, {'value': 'ACK'}, 
bytearray(b'
<?xml version="1.0" encoding="UTF-8" ?>
<data><log value="num_partition_sectors=61071360" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="SECTOR_SIZE_IN_BYTES=512" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="num_physical_partitions=3" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="MFR_ID=144" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="OEM_ID=74" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="Product name=HBG4a2" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><log value="{&quot;storage_info&quot;: {&quot;total_blocks&quot;:61071360, &quot;block_size&quot;:512, &quot;page_size&quot;:512, &quot;num_physical&quot;:3, &quot;mfr_id&quot;:144, &quot;serial_num&quot;:3325436310, &quot;fw_version&quot;:&quot;165&quot;,&quot;mem_type&quot;:&quot;eMMC&quot;, &quot;prod_name&quot;:&quot;HBG4a2&quot;}}" /></data>
<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" /></data>')
]
```
[log.txt](https://github.com/bkerler/edl/files/6720862/log.txt)

**Comment by bkerler** [comment]
Thanks, I will fix it.

Am 27. Juni 2021 02:43:39 MESZ schrieb Leandro Oliveira ***@***.***>:
>Guys could you give me a hand with this error?
>
>While trying to execute edl.py rf mem.bin, edl.py returned this error:
>
>
>```
>Traceback (most recent call last):
>File
>"/home/leandro/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/pydevd.py",
>line 1438, in _exec
>    pydev_imports.execfile(file, globals, locals)  # execute the script
>File
>"/home/leandro/pycharm-community-2020.1.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py",
>line 18, in execfile
>    exec(compile(contents+"\n", file, 'exec'), glob, loc)
>  File "/home/leandro/edl/edl.py", line 368, in <module>
>    base.run()
>  File "/home/leandro/edl/edl.py", line 350, in run
>    fh.handle_firehose(cmd, options)
>File "/home/leandro/edl/Library/firehose_client.py", line 301, in
>handle_firehose
>    storageinfo = self.get_storage_info()
>File "/home/leandro/edl/Library/firehose_client.py", line 157, in
>get_storage_info
>    rs = info.split("INFO: ")[1]
>IndexError: list index out of range
>
>Process finished with exit code 1
>
>```
>
>![Screenshot_2_meg7-storage-info](https://user-images.githubusercontent.com/4167122/123529456-56017b00-d6be-11eb-9995-4e9bb77961ab.png)
>
>**Dump of variable <val>**
>
>```
>[True, {'value': 'ACK'}, 
>bytearray(b'
><?xml version="1.0" encoding="UTF-8" ?>
><data><log value="num_partition_sectors=61071360" /></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log
>value="SECTOR_SIZE_IN_BYTES=512" /></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log
>value="num_physical_partitions=3" /></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log value="MFR_ID=144"
>/></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log value="OEM_ID=74"
>/></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log value="Product
>name=HBG4a2" /></data>
><?xml version="1.0" encoding="UTF-8" ?><data><log
>value="{&quot;storage_info&quot;: {&quot;total_blocks&quot;:61071360,
>&quot;block_size&quot;:512, &quot;page_size&quot;:512,
>&quot;num_physical&quot;:3, &quot;mfr_id&quot;:144,
>&quot;serial_num&quot;:3325436310,
>&quot;fw_version&quot;:&quot;165&quot;,&quot;mem_type&quot;:&quot;eMMC&quot;,
>&quot;prod_name&quot;:&quot;HBG4a2&quot;}}" /></data>
><?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK"
>/></data>')
>]
>```
>[log.txt](https://github.com/bkerler/edl/files/6720862/log.txt)
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/edl/issues/108

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by bkerler** [comment]
Please try this commit : 59bf655

**Comment by leosol** [comment]
It's almost perfect!
**firehose_client.modules** used to be initialized at firehose_client constructor, right?  I guess it's now initialized just after configuration, and, since my device is a Xiaomi one, it requires **authentication** which is not possible since firehose_client.modules had not been initialized yet. Besides that, I could read 3 luns each having 30 GB. Do you think that's normal? This device has 32GB of space.

Oh, sorry about not using the latest version when I opened the issue. I thought I was using the latest version (Jun 26, 2021) but I was at 402f6935a37fb3bf45a2af4bb20870ec6b2cb16f (Jun 25, 2021)

Thank you once again for the help.

```
./edl.py rf dump.dd --debugmode > log.txt
Traceback (most recent call last):
  File "./edl.py", line 368, in <module>
    base.run()
  File "./edl.py", line 346, in run
    fh = firehose_client(args, self.cdc, self.sahara, self.__logger.level, print)
  File "/home/leandro/edl-latest/edl/Library/firehose_client.py", line 99, in __init__
    if self.firehose.configure(0):
  File "/home/leandro/edl-latest/edl/Library/firehose.py", line 799, in configure
    if self.modules.edlauth():
AttributeError: 'NoneType' object has no attribute 'edlauth'
```

**Comment by bkerler** [comment]
Yeah, ufs and emmc work best using gpt approach. As we have no gpt (usually) on some spinor, I'm reading the storageinfo. Which is weird that it reports the same storage size on all luns, I think that's a bug of the qc edl loader. It should work fine now on the latest commit at least for reading :)
