### ISSUE TITLE
OnePlus 8 pro

### ISSUE THREAD

**Issue by Tamermak** [bkerler/edl#109]
Tried the loader provided here for OnePlus 8 t lite 
Gave me an error  in Ddr type 
Tried a ddr loader provided elsewhere claiming its for 8 pro
it passes the ddr test but gives usb error and i saw that same error in one of the issues here where you stated that it was caused of a loader made for a different phone

**Comment by Tamermak** [comment]
Hi @bkerler 
https://github.com/bkerler/edl/issues/30

May you please advise if the loader for OnePlus 8 Pro is available yet? 
As I tried the one uploaded and it didn't work

**Comment by bkerler** [comment]
Use the one in the loader repo, it's tested to work. Or use the lite firehose.

**Comment by Tamermak** [comment]
Got your loaders folder installed and the edl detects the best suitable 
It works fine with reading 
Dumping partitions
And printgpt works fine and completes successfully
But when i try to write
Either using edl.py reset
Or writing back partition dumps 
I get an error saying DDR type error

When i manually chose another firehose programmer called prog_firehose_ddr.elf 
From another image 
It passes the ddr test but doesn't write either and finally stops with the following  error
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5

**Comment by Tamermak** [comment]
@bkerler the one that gives me USB error 5 is the one extracted
FYI my phone is IN2020 the Chinese model

**Comment by Domiology** [comment]
@Tamermak 
@bkerler 
here's the full output
[errlog.txt](https://github.com/bkerler/edl/files/6772695/errlog.txt)

**Comment by Domiology** [comment]
and using another firehose lite loader 

 ./edl.py reset --loader=prog_firehose_lite.elf
Qualcomm Sahara / Firehose Client V3.4 (c) B.Kerler 2018-2021.
main - Using loader prog_firehose_lite.elf ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000c30e100514d6d (MSM_ID:0x000c30e1,OEM_ID:0x0051,MODEL_ID:0x4d6d)
CPU detected:      "SM8250:CD90-PH805-1A"
PK_HASH:           0x7c15a98db4e70963715f51c8da39c1e66fc1c3334e95f4c6a5627da6a49c842f
Serial:            0x1219869b

sahara - Uploading loader prog_firehose_lite.elf ...
Successfully uploaded programmer :)
firehose - Chip serial num: 303662747 (0x1219869b)
firehose - Supported Functions: program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,gethwversion,getrfversion,getprjversion,eraseuserdata,sha256init,sha256final,demacia,setprojmodel
firehose - 
firehose_client - Target detected: SM8250:CD90-PH805-1A
firehose_client - Based on the chipset, we assume UFS as default memory type...
firehose - TargetName=
firehose - MemoryName=UFS
firehose - Version=
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,gethwversion,getrfversion,getprjversion,eraseuserdata,sha256init,sha256final,demacia,setprojmodel
Will issue reset/power off 100 useconds, if this hangs check if watchdog is enabled
bsp_target_reset() 1
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5

**Comment by bkerler** [comment]
> Got your loaders folder installed and the edl detects the best suitable 
> It works fine with reading 
> Dumping partitions
> And printgpt works fine and completes successfully
> But when i try to write
> Either using edl.py reset
> Or writing back partition dumps 
> I get an error saying DDR type error
> 
> When i manually chose another firehose programmer called prog_firehose_ddr.elf 
> From another image 
> It passes the ddr test but doesn't write either and finally stops with the following  error
> USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5

You need to add devicemodel for writing (prjid). Oneplus has a write authentication.

**Comment by Tamermak** [comment]
> You need to add devicemodel for writing (prjid). Oneplus has a write authentication.

May you please explain how to do that? 
@bkerler

**Comment by Tamermak** [comment]
If you mean adding --pid= to the reset command 
Where can i get the id of my phone to add it

**Comment by Tamermak** [comment]
Hi @bkerler 

Got the vid and pid  from lsusb
Tried to use both or either and still getting the usb error

**Comment by bkerler** [comment]
I will have a look. The last commit should work with autodetection of the prjid

**Comment by bkerler** [comment]
please try commit 6283183535ab5b33b8c312011068364d3c1a7e6e

**Comment by bkerler** [comment]
Looks like the loaders directory wasn't updated and had the wrong op8 loader in it. Should work fine now, make sure to git submodule init and git submodule update.

**Comment by reikred** [comment]
I'm thoroughly confused. Does or does not  edl WRITE (write a single partition) work with Oneplus devices? From this issue/thread, it seems that it does, but from README.mdd and other threads, it seems write does NOT work.
