### ISSUE TITLE
error in "Library/firehose.py", line 497, in connect

### ISSUE THREAD

**Issue by adjexpress** [bkerler/edl#11]
try to change active bootable storage and get this error :
`Traceback (most recent call last):
  File "./edl.py", line 1592, in <module>
    main()
  File "./edl.py", line 411, in main
    handle_firehose(args, cdc, sahara, verbose)
  File "./edl.py", line 1084, in handle_firehose
    supported_functions = fh.connect(0)
  File "/home/abdorahmanamani/workspace/Linux/Qcom/edl/edl-master/Library/firehose.py", line 497, in connect
    self.serial=int(serial.split(" ")[0])
ValueError: invalid literal for int() with base 10: 'Chip'
`
this is caused by firehose.py line 496 , which is this: `serial=line.split(": ")[1]`
and changing to this will solve the problem: `serial=line.split(": ")[2]  `
pointing to 3th array cell which is decimal chip info

**Comment by bkerler** [comment]
Thanks, will have a look

**Comment by bkerler** [comment]
Please test with commit 775684a
