### ISSUE TITLE
Oppo A72 (CPH2067) Timed out error.

### ISSUE THREAD

**Issue by HighlanderUkUk** [bkerler/edl#111]
System i'm using is Kali linux 
command i'm entering is
python3 edl.py --debugmode printgpt

I have Extracted Loader from official firmware ofp and have added it to loaders in edl using following command ./Loaders/fhloaderparse.py newstuff Loaders
it shows as being added and edl uses it when i connect phone.
edl shows it's sending loader then times out with following error
"Timed out
bytearray(b'')
Unexpected error on uploading, maybe signature of loader wasn't accepted ?
'NoneType' object is not subscriptable"

Here is link to the firmware

https://mega.nz/file/srACQLAa#_1LuKpVL-TPufWojLscM_mxZx6DEqAB29latq-I5WU4

and i have attached log
[log.txt](https://github.com/bkerler/edl/files/6758649/log.txt)

**Comment by on4r4p** [comment]
What is the original name of the file you use from the .ofp to get this loader (0010a0e100510000_6e91b529aad0307f_fhprg.bin)

**Comment by HighlanderUkUk** [comment]
> What is the original name of the file you did used from the .ofp to get that loader (0010a0e100510000_6e91b529aad0307f_fhprg.bin) ?

I will get the correct name for loader when I am at my pc tomorrow.

**Comment by on4r4p** [comment]
Kay i got it i think .
it was prog_firehose_ddr_ufs.elf right ?

**Comment by HighlanderUkUk** [comment]
> Kay i got it i think .
> It was prog_firehose_ddr_ufs.elf right ?
> Have you tried with --memory=ufs ?

Just checked and yes that's the one I used. And yes I have tried with --memory=ufs

**Comment by on4r4p** [comment]
Can't believe it ....
Still a timeout ?
So that means that we have a real firehose but not signed for that oppo .

**Comment by bkerler** [comment]
Oppo is using vip programming, means you can only flash exactly the same cmds and flash data oppo provides, nothing else. And you can't use other firehose loaders because the pkhash has to match the device fused public key.

So in other words..... don't buy oppo devices.

**Comment by HighlanderUkUk** [comment]
> Oppo is using vip programming, means you can only flash exactly the same cmds and flash data oppo provides, nothing else. And you can't use other firehose loaders because the pkhash has to match the device fused public key.
> 
> So in other words..... don't buy oppo devices.

So even with the correct ofp for this device it's not possible to flash?

**Comment by on4r4p** [comment]
> Oppo is using vip programming, means you can only flash exactly the same cmds and flash data oppo provides, nothing else. And you can't use other firehose loaders because the pkhash has to match the device fused public key.
> So in other words..... don't buy oppo devices.

Thnks a lot sir :)

> So even with the correct ofp for this device it's not possible to flash?

Well you have the correct .ofp and the correct firehose i think 
but those were not used in the factory .

can you access the urgency call num pad and do *#899# ?
Then go to manual test - Swipe to the right until the "Others" tab.
And tap  : "Reading reset complete indicator"
You should see the real names of firmware used by oppo'sdev gave to whoever setup the phone.

**Comment by HighlanderUkUk** [comment]
Here is what I see
![Screenshot_2021-07-18-14-58-48-43_d2d8289d0defa94da624856a026fa830.jpg](https://user-images.githubusercontent.com/86885986/126070129-95e0cb74-0563-446d-946c-163098603f7e.jpg)

**Comment by on4r4p** [comment]
You see ..? iv Never Seen an official 2067_11_A.24.200508 before .
Especially for the A72 .

**Comment by HighlanderUkUk** [comment]
>  You see ..? iv Never Seen an official 2067_11_A.24.200508 before .
> Especially for the A72 .
> Mine was  :
> 
> info:download over 2020-07-17 07:22:03+Download Mode ID:1 Str+MES+software version:CPH2067_11_A32_223326_08cbffff+download version: V2.0.2 for eMMC/UFS+Net STatus : intranet + Readback Verify: true
> ota_info:upgrade time: 2021-01-31 21:49:03 display version CPH2067_11_A.54 OTA version; CPH 2059EU_.A.54_0540_2020012010000
> 
> And the only one we are able to download from oppo is the one that u gave in ur first post .
> 
> 
> Edit : Thats a nice screenshot that you have here .....Your a72 is not bricked ? 

It's not bricked I want to reflash because I updated via vpn from Kazakhstan and now can't change firmware version to EU.

**Comment by HighlanderUkUk** [comment]
>  You see ..? iv Never Seen an official 2067_11_A.24.200508 before .
> Especially for the A72 .
> Mine was  :
> 
> info:download over 2020-07-17 07:22:03+Download Mode ID:1 Str+MES+software version:CPH2067_11_A32_223326_08cbffff+download version: V2.0.2 for eMMC/UFS+Net STatus : intranet + Readback Verify: true
> ota_info:upgrade time: 2021-01-31 21:49:03 display version CPH2067_11_A.54 OTA version; CPH 2059EU_.A.54_0540_2020012010000
> 
> And the only one we are able to download from oppo is the one that u gave in ur first post .
> 
> 
> Edit : Thats a nice screenshot that you have here .....Your a72 is not bricked ? 

I know the A92 CPH2059 uses the same ozip updates and can find CPH2059_11_A.24.200508_70a32281.ofp wondering if I should try loader from this

**Comment by on4r4p** [comment]
A9 A72 and A92 are bascilly the same phone with new features . 
You could flash them all in a blink whithout vip programming .
but you said it all those firmwares have not been released officially.
And since we have to use them specifically we r stuck .

The only thing i could think of is to try this ...
https://www.getdroidtips.com/oppo-a72-cph2067-isp-pinout-test-point/

**Comment by HighlanderUkUk** [comment]
Iv still had no joy so will close this issue
