### ISSUE TITLE
firehose edlauth causes exception

### ISSUE THREAD

**Issue by Bytekeeper** [bkerler/edl#115]
firehose.modules is initialized in `firehose_client.py` line 109  only after `firehose.configure(0)` is called in line 100.
But in case of edl auth, `configure` will try to authenticate, using `self.modules` in line 799.

Nevertheless, thanks for this tool! I hope I can manage to dump the contents of my severely dead Redmi K20, although I doubt it is supported here yet...

**Comment by Bytekeeper** [comment]
As I expected, the authdata does not seem to work for the Redmi K20 :( 
Offtopic, but: Any idea how I could retrieve it?

**Comment by bkerler** [comment]
Thanks, I will have a look

**Comment by bkerler** [comment]
fixed with commit 55bbfa4

**Comment by bkerler** [comment]
updated on commit 6283183535ab5b33b8c312011068364d3c1a7e6e and confirmed to work. Closing this now.
