### ISSUE TITLE
cannot execute commands

### ISSUE THREAD

**Issue by demonical** [bkerler/edl#12]
Brand: Nubia , Model: z18 (NX606J) , CPU: SDM845
LOG:
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2019.
__main__ - Using loader D:\Downloads\edl-master\edl-master\Loaders\0008b0e100040000_6c1ed0375298d9a4fcd5c3bdd10776acdc6a927a3600b1d5dcfd57b9bacfe7c4_FHPRG.bin ...
__main__ - Waiting for the device
__main__ - Device detected :)
__main__ - Mode detected: sahara
Device is in EDL mode .. continuing.
Library.sahara -
------------------------
HWID:              0x0008b0e100040000 (MSM_ID:0x0008b0e1,OEM_ID:0x0004,MODEL_ID:0x0000)
PK_HASH:           0x6c1ed0375298d9a4fcd5c3b*******0b1d5dcfd57b9bacfe7c4
Serial:            0x3d***8
SBL Version:       0x00000000

Successfully uploaded programmer :)
Library.firehose - INFO: Chip serial num: 1039***624 (0x***88)
Traceback (most recent call last):
  File "D:\Downloads\edl-master\edl-master\Library\usblib.py", line 169, in read
    tmp=self.device.read(self.EP_IN, length,timeout)
  File "C:\Users\ice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\core.py", line 988, in read
    self.__get_timeout(timeout))
  File "C:\Users\ice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb0.py", line 542, in bulk_read
    timeout)
  File "C:\Users\ice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb0.py", line 627, in __read
    timeout
  File "C:\Users\ice\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "edl.py", line 1592, in <module>
    main()
  File "edl.py", line 411, in main
    handle_firehose(args, cdc, sahara, verbose)
  File "edl.py", line 1084, in handle_firehose
    supported_functions = fh.connect(0)
  File "D:\Downloads\edl-master\edl-master\Library\firehose.py", line 528, in connect
    self.cdc.read()
  File "D:\Downloads\edl-master\edl-master\Library\usblib.py", line 171, in read
    if "timed out" in e.strerror:
TypeError: a bytes-like object is required, not 'str'

also trying to reset phone with debug command output:
.......
<log value="WARN: NAK: MaxPayloadSizeToTargetInBytes sent by host 1048576 larger than supported 32768" /></data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="NAK" MemoryName="eMMC" MinVersionSupported="1" Version="1" MaxPayloadSizeToTargetInBytes="32768" MaxPayloadSizeToTargetInBytesSupported="32768" MaxXMLSizeInBytes="4096" DateTime="Dec  7 2018 - 11:49:46" /></data>
Traceback (most recent call last):
  File "edl.py", line 1592, in <module>
    main()
  File "edl.py", line 411, in main
    handle_firehose(args, cdc, sahara, verbose)
  File "edl.py", line 1084, in handle_firehose
    supported_functions = fh.connect(0)
  File "D:\Downloads\edl-master\edl-master\Library\firehose.py", line 556, in connect
    self.cfg.MaxPayloadSizeFromTargetInBytes = int(rsp[1]["MaxPayloadSizeFromTargetInBytes"])

**Comment by bkerler** [comment]
Hi, can you please test the latest commit with --debugmode commandline option added, and upload the resulting log.txt over here ?

**Comment by demonical** [comment]
the log is verry big :) but here it is:
[log.txt](https://github.com/bkerler/edl/files/4046254/log.txt)

P.P. there is another strange thing, when i add the line for the momry type "memory=ufs" the output of the eld is the help menu: 
[mem-log.txt](https://github.com/bkerler/edl/files/4046265/mem-log.txt)

**Comment by bkerler** [comment]
> P.P. there is another strange thing, when i add the line for the memory type "memory=ufs" the output of the eld.py is the help menu.

You need to use --memory=ufs :)

Regarding the log ... it seems that everything works fine, except the MaxPayloadSizeToTargetInBytes ... will have a closer look for it.

**Comment by bkerler** [comment]
please retry using commit 89274aa :) Should be fixed now. If not, make a new log please :)

**Comment by demonical** [comment]
> 
> 
> > P.P. there is another strange thing, when i add the line for the memory type "memory=ufs" the output of the eld.py is the help menu.
> 
> You need to use --memory=ufs :)
> 
> Regarding the log ... it seems that everything works fine, except the MaxPayloadSizeToTargetInBytes ... will have a closer look for it.
output with --memory=ufs :
D:\Downloads\edl-master\edl-master>python3.7 edl.py reset --memory=ufs --loader=D:\Downloads\edl-master\edl-master\Loaders\0008b0e100040000_6c1ed0375298d9a4_FHPRG.bin
Usage:
    edl.py -h | --help
    edl.py [--vid=vid] [--pid=pid]
    edl.py [--loader=filename] [--memory=memtype]
    edl.py [--debugmode]
    edl.py [--gpt-num-part-entries=number] [--gpt-part-entry............


and the new log without pointing mem type:
[log2.txt](https://github.com/bkerler/edl/files/4049499/log2.txt)

**Comment by bkerler** [comment]
The reset command doesn't need any flash options, the memory option is just for flash commands, that's why it shows the help.

**Comment by demonical** [comment]
> 
> 
> The reset command doesn't need any flash options, the memory option is just for flash commands, that's why it shows the help.

any suggestions , about the error ?

**Comment by bkerler** [comment]
OK, the commit 9497194 was tested to work with 16 different devices, including sdm855 :) Hope this works now :)

**Comment by demonical** [comment]
starting to think that my python is some kind of sick or my test nubia phone ..... :D but here is the log from  command: python3.7 edl.py printgpt --memory=UFS --lun=0 --debugmode
[cmdLineLog.txt](https://github.com/bkerler/edl/files/4055709/cmdLineLog.txt)
(reset also do not work)

pease 💯

**Comment by bkerler** [comment]
Latest commit 0b0ebae should address this issue :) Please test :)

**Comment by demonical** [comment]
in the latest log provided, that is is included...

**Comment by bkerler** [comment]
The issue should be solved in the last commit and only affects Windows.
