### ISSUE TITLE
Unknown mode. Aborting. And UsbClass timing out. Error in edl mode in Ubuntu. (LG G7 One)

### ISSUE THREAD

**Issue by BudDeuce** [bkerler/edl#120]
../edl.py --debugmode
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.5 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
UsbClass
UsbClass - [LIB]: Detaching kernel driver
UsbClass
UsbClass - [LIB]:   CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xa0 Bus Powered, Remote Wakeup
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
main - Device detected :)
UsbClass
UsbClass - [LIB]: connect:0x80
UsbClass
UsbClass - [LIB]: Timed out
UsbClass
UsbClass - [LIB]: bytearray(b'')
UsbClass
UsbClass - [LIB]: [Errno 110] Operation timed out
UsbClass
UsbClass - [LIB]: 
Stack (most recent call last):
  File "/home/buddeuce/edl/./edl.py", line 358, in <module>
    base.run()
  File "/home/buddeuce/edl/./edl.py", line 254, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "/home/buddeuce/edl/./edl.py", line 196, in doconnect
    mode, resp = self.sahara.connect()
  File "/home/buddeuce/edl/edl/Library/sahara.py", line 395, in connect
    self.cdc.write(data)
  File "/home/buddeuce/edl/edl/Library/usblib.py", line 368, in write
    self.verify_data(bytearray(command), "TX:")
  File "/home/buddeuce/edl/edl/Library/usblib.py", line 111, in verify_data
    self.debug("", stack_info=True)
UsbClass
UsbClass - [LIB]: TX:<?xml version="1.0" ?><data><nop /></data>
UsbClass
UsbClass - [LIB]: connect:0x80
UsbClass
UsbClass - [LIB]: Timed out
UsbClass
UsbClass - [LIB]: bytearray(b'')
UsbClass
UsbClass - [LIB]: [Errno 110] Operation timed out
UsbClass
UsbClass - [LIB]: 
Stack (most recent call last):
  File "/home/buddeuce/edl/./edl.py", line 358, in <module>
    base.run()
  File "/home/buddeuce/edl/./edl.py", line 254, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "/home/buddeuce/edl/./edl.py", line 196, in doconnect
    mode, resp = self.sahara.connect()
  File "/home/buddeuce/edl/edl/Library/sahara.py", line 400, in connect
    self.cdc.write(data)
  File "/home/buddeuce/edl/edl/Library/usblib.py", line 368, in write
    self.verify_data(bytearray(command), "TX:")
  File "/home/buddeuce/edl/edl/Library/usblib.py", line 111, in verify_data
    self.debug("", stack_info=True)
UsbClass
UsbClass - [LIB]: TX:7e064e957e
UsbClass
UsbClass - [LIB]: connect:0x80
UsbClass
UsbClass - [LIB]: Timed out
UsbClass
UsbClass - [LIB]: bytearray(b'')
main - Unknown mode. Aborting.

**Comment by BudDeuce** [comment]
I would love some advice on how to fix this.

**Comment by bkerler** [comment]
Actually you need the right signed edl loader for your device.

**Comment by BudDeuce** [comment]
Thanks, the issue fixed itself.

**Comment by BudDeuce** [comment]
Basically, for those wondering, I downloaded the latest version of edl, it now works!

**Comment by BudDeuce** [comment]
Oh, and the program found the correct loader automatically.

**Comment by bkerler** [comment]
Ah great. Thanks for the feedback ;)

**Comment by BudDeuce** [comment]
No problem :)
