### ISSUE TITLE
namespace attribute error

### ISSUE THREAD

**Issue by yssreddy1961** [bkerler/edl#121]
while running diag.py we are getting  this error after latest pull .Earlier 3.1 release it was ok for oneplus6t
Traceback (most recent call last):
  File "/home/yssreddy/edl/diag.py", line 1339, in <module>
    main()
  File "/home/yssreddy/edl/diag.py", line 1335, in main
    dg.run(args)
  File "/home/yssreddy/edl/diag.py", line 1247, in run
    diag.efsread(args.efsread)
AttributeError: 'Namespace' object has no attribute 'efsread'

**Comment by yssreddy1961** [comment]
Same error even with livedvd

**Comment by bkerler** [comment]
Thanks for reporting, I will have a look

**Comment by bkerler** [comment]
Fixed with commit ff6159f

**Comment by yssreddy1961** [comment]
python3 diag.py -vid 0x5c6 -pid 0x9091 nvread 0x21

Qualcomm Diag Client (c) B.Kerler 2019-2021.
---------------------------------------

Traceback (most recent call last):
  File "/home/yssreddy/edl/diag.py", line 1339, in <module>
    main()
  File "/home/yssreddy/edl/diag.py", line 1335, in main
    dg.run(args)
  File "/home/yssreddy/edl/diag.py", line 1193, in run
    if "0x" in args.nvread:
AttributeError: 'Namespace' object has no attribute 'nvread'

same error wirh efslistdir parameter and nvread.solved only nvackup

**Comment by bkerler** [comment]
Hopefully now solved with commit 6ab7925aaeda0e0aee11fab5242d25a8f38300ab

**Comment by yssreddy1961** [comment]
solved after correcting one syntax error  " ]" removed  "]" in line no 1208 of diag.py

pl correct syntax in diag.py line no 1208

**Comment by bkerler** [comment]
thx :)

**Comment by yssreddy1961** [comment]
Thank you
