### ISSUE TITLE
libusb on Ubuntu

### ISSUE THREAD

**Issue by vcj-huy** [bkerler/edl#123]
Thank you for this great app.

I want to report a bug and the solution in case someone else has to deal with the same error.
I'm running on Ubuntu 18.04. After updating edl to the latest version, I got  the following error when trying "python edl.py":
"AttributeError: /usr/lib/x86_64-linux-gnu/libusb-1.0.so: undefined symbol: libusb_set_option"

I editted the file /edl/Library/usblib.py, line 103 as
"libusb-1.0.so" -> "libusb.so"

and everything works fine. 
BTW I did not get this error with the previous version.

Again, thank you for your great works.

**Comment by BudDeuce** [comment]
Try using a newer version of Ubuntu.

**Comment by bkerler** [comment]
@vcj-huy  Thanks for reporting. Normally it should work with the fallback option to libusb0. I will have a look.

**Comment by bkerler** [comment]
Please try if  commit 5ee044a solves your issue.

**Comment by CyberMan571** [comment]
@vcj-huy 
is it  ongoing ?

**Comment by CyberMan571** [comment]
Results:
```
ubuntu@ubuntu:/lib$ find -iname libusb*
./x86_64-linux-gnu/libusb-1.0.so.0
./x86_64-linux-gnu/libusb-1.0.so.0.2.0
./x86_64-linux-gnu/libusbmuxd.so.6
./x86_64-linux-gnu/libusbmuxd.so.6.0.0
./x86_64-linux-gnu/pkgconfig/libusb-1.0.pc
./x86_64-linux-gnu/libusb-1.0.so
./x86_64-linux-gnu/libusb-1.0.a

```

**Comment by vcj-huy** [comment]
> Please try if commit [5ee044a](https://github.com/bkerler/edl/commit/5ee044ad03d9960847c660fe7583415b90e8d416) solves your issue.

It's working great now. Thank you very much.
