### ISSUE TITLE
LG G7 One issues.

### ISSUE THREAD

**Issue by BudDeuce** [bkerler/edl#124]
Immediately after the device goes into EDL mode, I get these error messages that I got before but were fixed when immediately putting the device into EDL mode. This isn't the case in this situation, I have tried everything I can think of. After 50%, the erase speed drops to less than 1 megabyte a second, and I get a "firehose - [LIB]: Error:{}" error afterwards.

**Comment by BudDeuce** [comment]
After 50%, the erase speed drops to less than 1 megabyte a second, and I get a "firehose - [LIB]: Error:{}" error afterwards.

**Comment by BudDeuce** [comment]
Help would be appreciated.

**Comment by BudDeuce** [comment]
NOTE: Writing works just fine.

**Comment by bkerler** [comment]
That sounds like it might be a range issue on writing. Erase is in fact just the same as writing (uses same command)

**Comment by BudDeuce** [comment]
UPDATE: I got a new error, which is this: "firehose - [LIB]: USB read has failed. Returned 0 bytes."

I have tried different cables, switching USB ports, etc.

**Comment by bkerler** [comment]
can you please run with --debugmode and then upload the log ? Also which command you have executed.

**Comment by BudDeuce** [comment]
Alright.

**Comment by BudDeuce** [comment]
https://drive.google.com/file/d/109IfI9ZpRwQNTSDU3VMsAOZSY7pYmJR1/view

**Comment by BudDeuce** [comment]
@bkerler I sent the log.

**Comment by BudDeuce** [comment]
Forgot to close this, smh.
