### ISSUE TITLE
Install log  pylzma warning 

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#128]
[install-log.txt](https://github.com/bkerler/edl/files/7000970/install-log.txt)
Dear @bkerler, Hi,
![pylzma-error_2021-08-17_00-01-00](https://user-images.githubusercontent.com/30759335/129749718-093f142f-c44e-4771-9e7b-cb6e9da7c8f0.png)
the problem, I have   experiencing windows and linux
is it  problem for edl?

**Comment by bkerler** [comment]
Hi, pylzma errors are out of the scope of this project. Please ask the pylzma authors for sorting out compilation errors/warnings.
