### ISSUE TITLE
problem in Readme and  setup.py 

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#129]
Dear @bkerler Hi,
these are  missing  in setup.py
```
    'capstone',
    'keystone-engine'
```
```
install_requires=[
    'colorama',
    'docopt',
    'usb',
    'pyusb',
    'pyserial',
    'lxml',
    'pylzma',
    'pycryptodome',
    'capstone',
    'keystone-engine'
    ],
```
I fixed however I want you check  other problem

please, change all python to python3

**Comment by bkerler** [comment]
Hi, those aren't missing in setup.py as those two libraries aren't used in the non-development version of edl and thus not needed.

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/130300330-2850210b-44e9-4621-854c-9e2026ab62bf.png)
I added missing to setup.py and the problem is gone out
Thanks
