### ISSUE TITLE
Cannot start edl.py   No module named 'edl.Config';   (tested on ubuntu and ubuntu_re)

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#134]
![Screenshot from 2021-08-31 03-03-35](https://user-images.githubusercontent.com/30759335/131435055-2388a841-fd05-4803-ba8e-55b0de06e37c.png)
Hi B. Kerler
after installed edl.py  I have met with this problem!  
Cannot open or start! 
Thanks

**Comment by CyberMan571** [comment]
same it with python3.9 
![Screenshot from 2021-08-31 03-16-38](https://user-images.githubusercontent.com/30759335/131436116-d3be6a1e-cfc7-4d8c-9d6e-b8ac6327db05.png)

**Comment by HighlanderUkUk** [comment]
Have you tried it directly from git pull in your home directory.

git clone https://github.com/bkerler/edl 
cd edl
 git submodule update - - init - - recursive pip3 install - r requirements.txt

**Comment by CyberMan571** [comment]
I have tried, however  it was no change

HighlanderUkUk ***@***.***>, 31 Ağu 2021 Sal, 17:49 tarihinde
şunu yazdı:

**Comment by CyberMan571** [comment]
Yes, I have new cloned from github
Tried commands:
```
sudo python3.8 -m pip uninstall edl
sudo python3.9 -m pip uninstall edl
python3.9 setup.py build
sudo python3.9 setup.py install 
```
In cloned edl folder, it works and no problem.   However,  the problem has appearing in root folder and else folder.

![image](https://user-images.githubusercontent.com/30759335/131587274-12c84ff1-6d65-439f-a13d-c6ab32e92ee1.png)

**Comment by CyberMan571** [comment]
Does it give you an idea?
`https://docs.python.org/3/library/configparser.html`

Problem of -m 'module' 
`https://docs.python.org/3/library/__main__.html`
 The problem, because of  missing main lib.

**Comment by CyberMan571** [comment]
![Screenshot from 2021-08-31 23-39-27](https://user-images.githubusercontent.com/30759335/131589342-58354f1e-48ae-46a0-b6fc-461e7478ea27.png)

**Comment by analoginterface0** [comment]
Remove the `.py` extensions from corresponding executables in **_`bin` directory_** (`~/.local/bin`, `/usr/local/bin` or `/usr/bin`).

For example:
`~/.local/bin/edl.py ==> ~/.local/bin/edl`
`/usr/local/bin/diag.py ==> /usr/local/bin/diag.py`

**Comment by CyberMan571** [comment]
@analoginterface0
Yes, Thanks, works!

 Pip3 problem, solved using this:
 
`sudo ln -sF  /usr/bin/python3.9 /bin/python3`
Also, this project need to  a __main__.py  for to run  python3 -m  "a module"
 
Also, I changed  python3 version with  `update-alternatives` command, but it showed several apt packages, and terminal error, because of mandatory python3.8

**Comment by CyberMan571** [comment]
Unfortunately,
works after change to `edl.py to edl`  but  it has been a problem with diag.py

**Comment by CyberMan571** [comment]
![Screenshot from 2021-09-03 07-12-29](https://user-images.githubusercontent.com/30759335/131965482-16bc5805-03e2-48c8-90ea-982560f1b611.png)
[output_config.txt](https://github.com/bkerler/edl/files/7103967/output_config.txt)

**Comment by CyberMan571** [comment]
logs  and bugs. Actually  the current_dir result must is different.
```
>>> import os, sys, inspect
>>> current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
>>> print(current_dir)
/usr/local/bin
>>> print(current_dir)
/usr/local/bin
>>> nvxml = os.path.join(current_dir, "edl", "Config", "nvitems.xml")
>>> print(nvxml)
/usr/local/bin/edl/Config/nvitems.xml
>>> 
```

**Comment by CyberMan571** [comment]
Reference:
```
https://docs.python.org/3/library/pathlib.html#module-pathlib
https://docs.python.org/3/library/os.path.html#module-os.path
```

**Comment by BudDeuce** [comment]
Did you remove the .py extension after diag?

**Comment by CyberMan571** [comment]
@BudDeuce 
Yes,
I changed  several codes  line in these
I removed py extension in `/EGG-INFO/scripts, usr/local/bin and SOURCES.txt`

![image](https://user-images.githubusercontent.com/30759335/132054061-e5bff555-7908-488f-be78-b49ec0c2fd9d.png)

However
it appears problem `boottodownload` because of `Import "Library.utils" could not be resolved`

![image](https://user-images.githubusercontent.com/30759335/132054350-263b1bcd-6537-4984-a331-a64dd14a3087.png)

**Comment by BudDeuce** [comment]
try adding edl. before Library.utils like this: edl.Library.utils

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/132059338-64e61a44-ed05-4c17-aeb4-93749884b8b9.png)
has no finished
setup.py is broken, each time you install the changes are lost and must be edited.

**Comment by CyberMan571** [comment]
@BudDeuce 
I search solution   without removing ext like in windows

**Comment by bkerler** [comment]
Closing this issue now. It should work fine now after running setup.py as stated in the readme.

**Comment by CyberMan571** [comment]
Excuse me! Bjoern!
I have waited to be able, more info.
I work to be  that is understandable.
No worries! No leave!
Because of I don't reply, sorry!

Bjoern Kerler ***@***.***>, 14 Kas 2021 Paz, 17:57 tarihinde
şunu yazdı:
