### ISSUE TITLE
Cannot run sierrakeygen.py via LiveDVD

### ISSUE THREAD

**Issue by ydanote** [bkerler/edl#135]
I apologize if my stupidity is the problem here (a definite possibility), but when I try to run sierrakeygen.py, I get a No module named 'Library' error.  I am using the LiveDVD thinking that will take out the most variables but I still cannot get it to work.  
Is something missing there?

I am trying to open the lock on a Netgear MR1100-100NAS so I can make some changes via AT commands.

Thank you

<pre><font color="#4E9A06"><b>livedvd@host</b></font>:<font color="#3465A4"><b>/opt/edl</b></font>$ python modem/sierrakeygen.py -l AAAAAAAAAAAA -d MDM9x40
Traceback (most recent call last):
  File &quot;modem/sierrakeygen.py&quot;, line 16, in &lt;module&gt;
    from Library.utils import LogBase
ModuleNotFoundError: No module named &apos;Library&apos;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;modem/sierrakeygen.py&quot;, line 23, in &lt;module&gt;
    from Library.utils import LogBase
ModuleNotFoundError: No module named &apos;Library&apos;
</pre>

**Comment by bkerler** [comment]
Hi, please run a git pull. That was my mistake, I just fixed this bug. thanks for reporting !

**Comment by ydanote** [comment]
That fixed it!  Thank you for the fast response and fix!
How often do you rebuild the LiveDVD?  Not that I need anything further right now, but I will make a new one to have around if it gets updated.

Thank you also for getting me into my MR1100!

**Comment by bkerler** [comment]
I will update the live dvd next week ;)

**Comment by ydanote** [comment]
> 
> 
> I will update the live dvd next week ;)

Wow, great!
Thank you again!
