### ISSUE TITLE
Flash guacamoleb, Library.oppo missing?

### ISSUE THREAD

**Issue by chaosmaster** [bkerler/edl#14]
Trying to flash guacamoleb (op7) results in errors. (dumping works)
looking at the code I assume Library.oppo is needed, but I can't find it anywhere.

**Comment by bkerler** [comment]
Oneplus devices need signed factory tokens similar to xiaomi devices in order to write. As I do not own the private keys for signing, I removed the oppo library for now as it is non working / non functional.

**Comment by bkerler** [comment]
If you need to write partitions, simply oem unlock your device. Edl isn't needed for that.

**Comment by bkerler** [comment]
I've removed the non-working code for now. As soon as Oneplus/Oppo decides to share the keys, I will reimplement the functions. But hopefully they will remove those functions in the future to allow people to unbrick their devices again :(

**Comment by chaosmaster** [comment]
Yeah, I have looked at the MSM tool in IDA and can see that it uses a token and pk.
Since MSMDownloadTool can write, I suppose it contains the keys.
It's not really about needing to write using EDL, it's more about wanting to ;)
Can you share your non working code?

**Comment by bkerler** [comment]
Ah I see. The oppo.py is empty, I just prepared the usage in edl.py based on usb sniffer logs, but if you reverse it successfully I would appreciate your code commit. Otherwise, the old msmdownloadtools for the guacamoleb do not need the signed tokens (only msmdownloadtool > 4.6 needs these)

**Comment by chaosmaster** [comment]
I see, can you share the usb logs then? Are you on IRC by any chance?
The oldest I found was the one in ANDROID+9+OOS+9.5.6+GM57BA+guacamoleb_14_E.12_190621_repack.zip
from which I extracted the firehose-programmer using your ops_decrypt.py.
It identifies itself as V4.0.88.

**Comment by bkerler** [comment]
Yeah, I sometimes lurk around in freenode, nick viperbjk

**Comment by bkerler** [comment]
Newer Oppo or Oneplus devices currently aren't supported as they need signed factory tokens (similar to xiaomi) for writing. Reading however should be possible.

Am 17. Februar 2020 20:28:47 MEZ schrieb Joel Stein <notifications@github.com>:
>Trying to flash guacamoleb (op7) results in errors.
>looking at the code I assume Library.oppo is needed, but I can't find
>it anywhere.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/edl/issues/14

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
