### ISSUE TITLE
unused library error ! 

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#140]
Hi, Friends ;)
I found unused library problem  in EDL package!
For sierrakeygen.py, it is correct named,  but  it occurs a  found no module library problem in enableadb.py or boottodownload.py.
like these
```
import io 
import os 
```

**Comment by CyberMan571** [comment]
i will update  info

**Comment by bkerler** [comment]
Sorry, can you be more specific what the problem is ?
