### ISSUE TITLE
LiveDVD questions

### ISSUE THREAD

**Issue by F1CU** [bkerler/edl#141]
Hi,

1. Are there any objections to installing your Live DVD on disk?
2. If the answer to the first question is no and you can easily install it on the disk, how to enable internet support? The kernel that is in the image should have no problem with ethernet support, unfortunately it is not in my case. Have you interfered with the Ethernet support? My network card is Killer Ethernet E2200, Mobo MSI Z97 Gaming 5
3. Does GRUB remain in the painting?

**Comment by HighlanderUkUk** [comment]
Sorry a bit off topic, but we're is link for live dvd?

**Comment by F1CU** [comment]
> Sorry a bit off topic, but we're is link for live dvd?

https://drive.google.com/file/d/1VUK0toC6I0jhJ4ZTFPREhSXFTkSe9_gl/view?usp=sharing

**Comment by CyberMan571** [comment]
@F1CU 
is your used objection word ?(that(if false, sorry)) disapproval?  
your answer, simply is, yes  and installable to disk.

Killer Ethernet E2200 issues is for old Linux kernel and no problem in new Linux kernels

**Comment by bkerler** [comment]
The livedvd already has a 5.10 kernel, guess you are missing the proper kernel modules. I will make a new livedvd very soon, installing it is just fine.

**Comment by bkerler** [comment]
Also the livedvd has minimal network support, you may need to install ubuntu networkmanager etc. first

**Comment by CyberMan571** [comment]
Please run  and send both;
```
lspci
ifconfig
```

**Comment by CyberMan571** [comment]
Also run,
`sudo  dmesg | grep 3c:00.0`
3c:00.0 is PCI bus path or address

**Comment by bkerler** [comment]
Closing this issue now.
