### ISSUE TITLE
force to need,  a   valid GPT partition file.  

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#142]
![Image](https://user-images.githubusercontent.com/30759335/132153144-17aaea1b-20bd-4e51-b152-c8f25fc41b0a.png)
![image](https://user-images.githubusercontent.com/30759335/132153153-fbaf8e22-366c-4cd2-818b-7022c501ae82.png)
![image](https://user-images.githubusercontent.com/30759335/132153166-0eb3f489-ae14-41db-8fa6-a4807fa4f6a3.png)
If it uses first gpt.bin file, edl.py  writes file as successful, however by  second file has appeared read back verify problem.
Like Detected Volume:GPT, I want to make modification for gpt_main0_thrid.bin.
How to make it?

**Comment by CyberMan571** [comment]
@bkerler 
Hi Dear Friends,
among us, my Friends, to know one  or not know one. In a future day, I  can meet up with you!
I send the files to you @bkerler  you can look to GPT files? Please!  Please look at these?

**Comment by CyberMan571** [comment]
![Image](https://user-images.githubusercontent.com/30759335/132258902-4a64c89b-3d97-4185-ba46-b19fa766ccc5.png)
@bkerler 
EDL app write successfully when end sector of this GPT file is 4294967295.

**Comment by bkerler** [comment]
I think that after writing gpt you need to reboot the phone as the da seems to read the gpt at the beginning.

**Comment by CyberMan571** [comment]
> I think that after writing gpt you need to reboot the phone as the da seems to read the gpt at the beginning.
Gpt_main0_valid.bin is  blank but detected GPT volume by your android MR. 
it needs to add android partitions. I try it with gdisk, however it gives error, so no successfully writing, it got failure.

**Comment by CyberMan571** [comment]
> Also writing the gpt the whole flash is said to be wiped (that's what mtk stated in some source code), so I guess you will need to use wf and not w option

I write with wf option using Gpt_main0_valid.bin, however blank.
In phone is Qualcomm.
