### ISSUE TITLE
9x07 secboot challenge unlock 

### ISSUE THREAD

**Issue by kashifbharwana** [bkerler/edl#144]
[sec.zip](https://github.com/bkerler/edl/files/7119430/sec.zip)
[tz.zip](https://github.com/bkerler/edl/files/7119433/tz.zip)

how remove secboot 1 or sing modem.img

**Comment by bkerler** [comment]
Sorry what do you mean ? Please give more details, which device, etc.

**Comment by kashifbharwana** [comment]
> Sorry what do you mean ? Please give more details, which device, etc.

Sir this device lock secure boot 3 if change modem.img device speed slow and flash via fastboot show flashing error or if flash sbl tz rpm or sec.dat other mdm 9207 device device lock

**Comment by kashifbharwana** [comment]
And read this article 
https://www.pianshen.com/article/56301935559/

**Comment by bkerler** [comment]
Sorry, only qualcomm or oems can sign. Clearly no issue of my tool, closing this issue.
