### ISSUE TITLE
Does not work on klte

### ISSUE THREAD

**Issue by EfxBDhT8** [bkerler/edl#154]
Hi, I have a Samsung Galaxy S5 and just like this issue https://github.com/bkerler/edl/issues/59 it gets stuck on any command. The debug log repeats this

xmlsend:0x1000
Timed out
bytearray(b'')
cmd_read_buffer:0x200
Timed out
bytearray(b'')
cmd_read_buffer:0x200
Timed out
bytearray(b'')
cmd_read_buffer:0x200
Timed out
bytearray(b'')
cmd_read_buffer:0x200
Timed out
bytearray(b'')
cmd_read_buffer:0x200
Timed out
bytearray(b'')

Is there any way for me to use this program?

**Comment by bkerler** [comment]
You will need a correct signed loader. Also samsung protects some partitions from being written in their signed loaders.
