### ISSUE TITLE
edl script doesn't work under windows

### ISSUE THREAD

**Issue by SevralT** [bkerler/edl#160]
Hello! I installed edl on macOS 12 Monterey Beta 7 on MacBook M1 (arm64). All dependencies installed but I have this traceback.
```Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.52 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
Traceback (most recent call last):
  File "./edl.py", line 362, in <module>
    base.run()
  File "./edl.py", line 255, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "./edl.py", line 177, in doconnect
    self.cdc.connected = self.cdc.connect()
  File "/Users/alexander/Desktop/edl/edl/Library/usblib.py", line 252, in connect
    self.device = usb.core.find(idVendor=vid, idProduct=pid, backend=self.backend)
  File "/Users/alexander/Library/Python/3.8/lib/python/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available```

**Comment by SevralT** [comment]
> Hi :) Edl is untested under macos, but you need to install libusb and pyusb

I already have installed this software

**Comment by metametapod** [comment]
I ran into this issue, which ended up being due to installing `libusb` with Homebrew but using `pyenv` for Python. This fixed it:

https://stackoverflow.com/a/30580166

Also see:

https://stackoverflow.com/questions/32756815/how-does-one-get-python-to-find-libusb-pyusb-needs-it-for-a-backend
