### ISSUE TITLE
TypeError: can't concat NoneType to bytes

### ISSUE THREAD

**Issue by thetechdudemc** [bkerler/edl#165]
Connected first device in EDL and did `python edl.py rl dumps --skip=modem --genxml` and this worked, it created all the partition dumps successfully

I then connected the second device to flash with these dumps in EDL and did `python edl.py wl dumps` and got this

....main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara -
------------------------
HWID:              0x000480e100000000 (MSM_ID:0x000480e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MDM9207"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x62c41a84

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Trying loader: C:\Users\watch\edl\edl\..\Loaders\qualcomm\patched\mdm9x07\000480e100000000_cc3153a80293939b_enprg_peek.bin
sahara - Uploading loader C:\Users\watch\edl\edl\..\Loaders\qualcomm\patched\mdm9x07\000480e100000000_cc3153a80293939b_enprg_peek.bin ...
Streaming - Successfully uploaded programmer :)
Streaming - HELLO protocol version: 3
Streaming - Chipset: 9x07
Streaming - Base address of the NAND controller: 079b0000
Streaming - Sector size: 516 bytes
Streaming - Spare bytes: 2 bytes
Streaming - Defective block marker position: spare+6
Streaming - The total size of the flash memory = 2048 blocks (512 MB)
Streaming - Flash memory: Toshiba KSLCMBL2VA2M2A, NAND 512MiB 1.8V 8-bit
Streaming - Page size: 4096 bytes (8 sectors)
Streaming - The number of pages in the block: 64
Streaming - OOB size: 256 bytes
Streaming - ECC: BCH, 8 bit
Streaming - ЕСС size: 2 bytes
Successfully uploaded programmer :)
Traceback (most recent call last):
  File "edl.py", line 362, in <module>
    base.run()
  File "edl.py", line 353, in run
    sc.handle_streaming(cmd, options)
  File "C:\Users\watch\edl\edl\Library\streaming_client.py", line 366, in handle_streaming
    if self.streaming.enter_flash_mode():
  File "C:\Users\watch\edl\edl\Library\streaming.py", line 173, in enter_flash_mode
    self.send_ptable(ptable, 0)  # 1 for fullflash
  File "C:\Users\watch\edl\edl\Library\streaming.py", line 229, in send_ptable
    cmdbuf = b"\x19" + pack("<B", mode) + parttable
TypeError: can't concat NoneType to bytes

**Comment by bkerler** [comment]
Depends on the device, Closing this issue now.
