### ISSUE TITLE
Firehose - [LIB]: Nop failed. with new loader op9

### ISSUE THREAD

**Issue by baboulinet05** [bkerler/edl#172]
Hello,

after seeing the news on the loader i decided to reflash and now i have this error message. any opinions?

![Sans titre](https://user-images.githubusercontent.com/1727418/138738716-35a356c4-75d0-488d-be52-38c8c0eeec26.png)

thanks

**Comment by baboulinet05** [comment]
nothing works I give up

**Comment by bkerler** [comment]
As already written, please get the right edl specific for your phone (on my test device, only the ddr loader one worked)
