### ISSUE TITLE
main - Unknown mode. Aborting. [Redmi 7]

### ISSUE THREAD

**Issue by deyvs02** [bkerler/edl#175]
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

......main - Device detected :)
main - Unknown mode. Aborting.

**Comment by bkerler** [comment]
As it says, the firehose loader seems to be wrong.
