### ISSUE TITLE
Some command line argument cannot be parsed

### ISSUE THREAD

**Issue by ek9852** [bkerler/edl#177]
While ago, there was a change from argparser to docopt, which is bad.
Right now many options are broken unless they are explicitly added to the each line in the docopt description.
e.g.the skipstorageinit command argument is not working anywhere unless we added that into each subcommand lines :

    edl xml <xmlfile> [--loader=filename] [--debugmode] [--skipresponse] [--vid=vid] [--pid=pid] [--devicemodel=value]
to
    edl xml <xmlfile> [--skipstorageinit] [--loader=filename] [--debugmode] [--skipresponse] [--vid=vid] [--pid=pid] [--devicemodel=value]
    for all edl subcommands

**Comment by bkerler** [comment]
Feel free to post a pr ;)
