### ISSUE TITLE
firehose for HW_ID     : 0009A0E100200000

### ISSUE THREAD

**Issue by ligteltelecom** [bkerler/edl#179]
[prog_emmc_firehose_8953_ddr.zip](https://github.com/bkerler/edl/files/7446990/prog_emmc_firehose_8953_ddr.zip)
have Someone this firehose for share?
Loader not match

```
Getting device info......
Serial No.: 0xC0CE9D7F
HW_ID     : 0009A0E100200000
MSM ID    : 0x0009A0E1, SDM450-Qualcomm Snapdragon 450
MODEL_ID  : 0x0000
OEM_ID    : 0x0020 - SAMSUNG
PBL Ver   : 00000000
PK HASH   : 3ccefae4cacf8160ef95a9c7d10c9aa7aa7e9664b75c5238df67a3c4e273bee2
```

**Comment by rebainoor** [comment]
For what smart phone is it ?

**Comment by ligteltelecom** [comment]
> For what smart phone is it ?

Samsung A02S SM-A025M

**Comment by rebainoor** [comment]
I Think already have it but i will send tomorrow

**Comment by ligteltelecom** [comment]
> I Think already have it but i will send tomorrow

Thx

**Comment by rebainoor** [comment]
sorry but i dont have the exacte loader 
but witch bit have this mobile ?

**Comment by bkerler** [comment]
Please ask such stuff in the Loaders repo, as it's edlclient unrelated. Closing this now.

**Comment by YasinSalah2001** [comment]
Anyone has a20s loaders been looking for it for days
