### ISSUE TITLE
Missleading supported functions.

### ISSUE THREAD

**Issue by screwer** [bkerler/edl#18]
Device: Xiaomi Redmi 5+ (tiffany)
Loader: 000460E100000000_57158eaf1814d78f_FHPRG (97ef3f33ce7c28225dee6950243dd6f31c0c90757e6f5bd4a8cba04dc1479b3a)

edl.py reports:
> __main__ - Supported functions:
> -----------------
> program,write,read,patch

But i can see "peek" and "poke" inside loader. So i tried patch 'check_cmd' to always True. And now 'unsupported' commands seems like working:

> Library.usblib - TX: <?xml version="1.0" ?><data><peek address64="655824" size_in_bytes="4" /></data>
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e3c646174613e3c6c6f672076616c75653d22496e76616c696420706172616d657465727322202f3e3c2f646174613e
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e3c646174613e3c726573706f6e73652076616c75653d224e414b22202f3e3c2f646174613e
> Library.usblib - TX: <?xml version="1.0" ?><data><peek address64="0xa01d0" SizeInBytes="0x4" /></data>
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e3c646174613e3c6c6f672076616c75653d225573696e67206164647265737320303030613031643022202f3e3c2f646174613e
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e3c646174613e3c6c6f672076616c75653d22307833302030783330203078333020307830302022202f3e3c2f646174613e
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e3c646174613e3c726573706f6e73652076616c75653d2241434b22202f3e3c2f646174613e
> Sec_Boot0 PKHash-Index:0 OEM_PKHash: True Auth_Enabled: True Use_Serial: False
> Sec_Boot1 PKHash-Index:0 OEM_PKHash: True Auth_Enabled: True Use_Serial: False
> Sec_Boot2 PKHash-Index:0 OEM_PKHash: True Auth_Enabled: True Use_Serial: False
> Sec_Boot3 PKHash-Index:0 OEM_PKHash: False Auth_Enabled: False Use_Serial: False
> Secure boot enabled.

**Comment by bkerler** [comment]
Yeah ... that's something I wanted to fix for a long time. Time to do it now :)

**Comment by bkerler** [comment]
Fixed with commit 036bc63
