### ISSUE TITLE
fhloaderparse impovement needed

### ISSUE THREAD

**Issue by rebainoor** [bkerler/edl#180]
If Many loaders (firehose) have same HWID and same pkHash but deferent size (versions)  only one and last parsed mbn will be saved in loaders folder
N/B : Firehose loaders have updated versions V1;V2;V3.....

**Comment by rebainoor** [comment]
Best way if Firehose have same HWID and same PKHASH and deferent size to rename it to V1;V2;V3.....

**Comment by bkerler** [comment]
Sorry, but this doesn't make any sense. It's a decision of the vendors like Samsung or oneplus to use different versions and they don't name their revisions. So you will have to use and rename the loaders manually as there cannot by any autodetection applied.
