### ISSUE TITLE
oneplus.py not working.

### ISSUE THREAD

**Issue by seci20** [bkerler/edl#185]
Hi master. Whats problem ? 

>  Traceback (most recent call last):
>   File "C:\2\edl\edlclient\Library\Modules\oneplus.py", line 22, in <module>
>     from edlclient.Library.utils import LogBase
> ModuleNotFoundError: No module named 'edlclient'

**Comment by bkerler** [comment]
You need to follow the readme and use python3 setup.py install

**Comment by seci20** [comment]
thanks master.
