### ISSUE TITLE
OP8t auth error. (sniff data have)

### ISSUE THREAD

**Issue by seci20** [bkerler/edl#186]
Hi master whats problem ? 

C:\2\edl>python edl w boot_a boot.img --memory=ufs --devicemodel=19805
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Trying with no loader given ...
main - Waiting for the device

> C:\2\edl>python edl w boot_a boot.img --memory=ufs --devicemodel=19805
> Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
> main
> main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
> main - Trying with no loader given ...
> main - Waiting for the device
> main - Device detected :)
> main - Mode detected: sahara
> Device is in EDL mode .. continuing.
> sahara -
> ------------------------
> HWID:              0x000c30e100514d6d (MSM_ID:0x000c30e1,OEM_ID:0x0051,MODEL_ID:0x4d6d)
> CPU detected:      "SM8250:CD90-PH805-1A"
> PK_HASH:           0x7c15a98db4e70963715f51c8da39c1e66fc1c3334e95f4c6a5627da6a49c842f
> Serial:            0xfe7acbda
> 
> sahara - Detected loader: C:\2\edl\edlclient\..\Loaders\oneplus\000c30e100514d6d_7c15a98db4e70963_fhprg_op8_op8tmo_op8t_op8ttmo.bin
> sahara - Uploading loader C:\2\edl\edlclient\..\Loaders\oneplus\000c30e100514d6d_7c15a98db4e70963_fhprg_op8_op8tmo_op8t_op8ttmo.bin ...
> Successfully uploaded programmer :)
> firehose - Chip serial num: 4269460442 (0xfe7acbda)
> firehose_client - Target detected: SM8250:CD90-PH805-1A
> firehose - TargetName=
> firehose - MemoryName=UFS
> firehose - Version=
> firehose_client - Supported functions:
> -----------------
> program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,gethwversion,getrfversion,getprjversion,eraseuserdata,sha256init,sha256final,demacia,setprojmodel,getddrt
> ype,ERROR: 0x1370 r_data:0x20,ERROR: 0x1342 r_data:0x1,ERROR: 0x1366 r_data:0x3,ERROR: 0x1365 r_data:0xb5,demacia,setprojmodel
> firehose
> firehose - [LIB]: ←[31msetprojmodel token="B933C0A1BDDDAF3B1040D31891FCB7ACA3E1926FDFD6841563218D97742420B2297B15AE15D2737E073B4BC712132E671A083299F3A8BE82548A3EF2B3410B85B84B22C4E89763C60C3CB91FDBE6F29C382779C01F942F69FF9648E79CC11370FBD0C2FE9C
> 96F85703B3DC2FCD48B32D866D7401415305955AD500151CA2A7BE1CF587B67AB195347EB193AB42BAD56B51546C405086579C58084565A71AAC198272300D5A4E649499EF1E11CAC2C1C4AEFCF4F786C4E5CE3C9B96CD6F4C25E269FB375676F11E7A65ADB1D780F3F3587DEA1B3029979F7C233ECD7BD974681
> CAC12A325C5FAE7A7918418E0067EAAEEABA4293EF8ECBE329AC2FAC81C06820E" pk="2KCOy9SeHi7oY3Qn" failed.←[0m
> firehose
> firehose - [LIB]: ←[31mbytearray(b'<?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="ERROR: SN: 4269460442,4269460442" /></data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<response value="NAK" model_check="1" auth_token_verify="
> 0" /></data>')←[0m
> Setprojmodel failed.
> {'value': 'NAK', 'model_check': '1', 'auth_token_verify': '0'}

Sniff comport data.

https://drive.google.com/file/d/1xWHvVlCeaXW1DYGbUGQ7gJWunbvD5jGT/view?usp=sharing

**Comment by seci20** [comment]
?

**Comment by bkerler** [comment]
I will have a closer look tomorrow. Most probably the device model id doesn't match.

**Comment by seci20** [comment]
I'm throwing the software for this model in the msm download tool. The project name is the same as the model name I commanded. I noticed that the calculation algorithm is different each time.

**Comment by bkerler** [comment]
I've just confirmed on a 8t, it works fine as expected (on prjid 19805). Maybe the edl loader you are using doesn't match your hw revision ?

**Comment by seci20** [comment]
> I've just confirmed on a 8t, it works fine as expected (on prjid 19805). Maybe the edl loader you are using doesn't match your hw revision ?

It happens when I throw the software named kebab_15_O.12_201110.The model name says kb2000 but I couldn't find it in the model list. When I looked at the notes, I saw the kebab model code and I made it according to that model.

**Comment by bkerler** [comment]
I've confirmed it to work on 19805. Closing this issue now. You will need to find the right prjid for your device (See installed system default.prop) and the right edl to make it work.
