### ISSUE TITLE
its support mi 10 ?

### ISSUE THREAD

**Issue by esakarya** [bkerler/edl#188]
HWID:              0x000c30e100720000 (MSM_ID:0x000c30e1,OEM_ID:0x0072,MODEL_ID:0x0000)
PK_HASH:           0x1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda46
Serial:            0xdbb678d3
SBL Version:       0x00000001

this printgpt comig from old edl-master version. current version doesnt show anything. 
when i try run any command just stop command with .main - Device detected :)
i am on windows 11, can any one help me ?

**Comment by bkerler** [comment]
continuing at #160
