### ISSUE TITLE
Streaming Mode - not a bug - request for more info

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#189]
Guys, I have a device which is in Streaming mode. In this mode, I can sand a firehose or aboot for example?
What's the purpose of this streaming mode?
My device is a Zenfone Live L1.

```
alcomm Sahara / Firehose Client V3.52 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in streaming mode, uploading loader
sahara - Device serial : 0x50b6e87f
Error, couldn't find suitable enprg/nprg loader :(
```

**Comment by Aquarian-Age** [comment]
I have the same problem
ze552kl

**Comment by bkerler** [comment]
You're in debug mode. Means that sbl/xbl/abl crashed. Remove battery, short emmc dat0 pin with gnd, connect usb. If you see the 9008 port, reinsert battery, then use my script to fix sbl/xbl/abl.
