### ISSUE TITLE
Error checking in 'cmd_peek'

### ISSUE THREAD

**Issue by screwer** [bkerler/edl#19]
Device: OnePlus6
Loader: 6000000000010000_dd7c5f2e53176bee_FHPRG.bin (2c67b51e1d24b57fb9f93a90f5da209f14732d70dfbed19e8a076f41ecc04550)

Note: failed to detect target name, so i patch it in firehose.connect, at the place "Unknown".

Issue: poke & peek also exists in programmer, but there is funny limitation:
> Peek is disabled on secure boot devices

Limitation is very funny because "poke" has no any similar and executed well. (But poke in your tool want to check written data and broke on verifying peek)

So, peek return error at first response packet:
> \<?xml version="1.0" encoding="UTF-8" ?\>
> \<data\>
> \<log value="ERROR: Failed to run the last command -1" /\>\</data\>

but code does not handle it (error handling take place on next packets only):
> Library.firehose - Peek: Address(0x300000),Size(0x3c000)
> Library.usblib - TX: <?xml version="1.0" ?><data><peek address64="3145728" size_in_bytes="245760" /></data>
> 
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX: > 3c3f786d6c2076657273696f6e3d22312e302220656e636f64696e673d225554462d3822203f3e0a3c646174613e0a3c6c6f672076616c75653d224552524f523a204661696c656420746f2072756e20746865206c61737420636f6d6d616e64202d3122202f3e3c2f646174613e
> Library.usblib - cmd_peek:0x1000
> Library.usblib - RX:
> Traceback (most recent call last):
>   File "edl.py", line 1645, in <module>
>     main()
>   File "edl.py", line 412, in main
>     handle_firehose(args, cdc, sahara, verbose)
>   File "edl.py", line 1255, in handle_firehose
>     if fh.cmd_peek(v[0][0], v[0][1], filename, True):
>   File "E:\.edl\tools\edl\Library\firehose.py", line 837, in cmd_peek
>     rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
> IndexError: list index out of range

**Comment by bkerler** [comment]
Ouch. Didn't expect poke to still work (normally shouldn't). Thanks, will fix this one for sure.

**Comment by bkerler** [comment]
Commit 8a466de should address this issue, can you test ?
