### ISSUE TITLE
Exit EDL mode on PIXEL 2016?

### ISSUE THREAD

**Issue by ExSport** [bkerler/edl#190]
Hello guys
Is it possible to exit EDL mode on Pixel 2016 which is in EDL only? Mobile went to EDL during charging so I am trying to exit it somehow.
Is it possible with this or other tools? It seems mobile was reset to EDL because of "corrupted" charging cable as it worked without issues but after cable connection mobile started to freeze and then black display only (QDLoader 9008 when connected to PC)
Thank you for right direction and sorry for maybe dumb question but already googled whole week how to fix it but without success. Don't want to loose another weeks/months if there is no option here...
Thanks!

**Comment by bkerler** [comment]
Most probably the usb cable has fried the emmc. Or are you able to run printgpt and see all partitions ?

**Comment by ExSport** [comment]
How it can happen? :(
Unfortunately it says device detected but unknown mode, aborting... whatever I tried printgpt or reset via livedvd.
Anything else I can test?
Thank you very much!

**Comment by bkerler** [comment]
Try to remove the battery and reinsert it, this might help. Closing this now, as it's no issue with the script as it seems.
