### ISSUE TITLE
Flash a partition with BIN file

### ISSUE THREAD

**Issue by zaiplanet** [bkerler/edl#193]
Nokia 8000 4G
I can not write recovery partiion again with .bin stock recovery image file :(
I don't have recovery partition .img file :(

**Comment by bkerler** [comment]
there is no need to use the .img ending. Just use the .bin file you have.

**Comment by zaiplanet** [comment]
> there is no need to use the .img ending. Just use the .bin file you have.

yes, i completed write with a bin file
Thx for your reply!
