### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by Alexoko12** [bkerler/edl#194]
Hi,

I got an ZeroDivisionError when dumping the userdata of my CAT B35.

from file: Library/firehorse.py (release 3.52)
Line176: throughput=(((datasize)/(tdiff)))

I fixed it simply with:
if tdiff == 0:
    tdiff = 0.001

kind regards
Alexoko

**Comment by bkerler** [comment]
Hi, many thanks for the hint :)
Please try commit 9892de2

**Comment by Alexoko12** [comment]
👍
