### ISSUE TITLE
error while installing required package 

### ISSUE THREAD

**Issue by Sandeepa167** [bkerler/edl#196]
here is error logs ===>>>

ERROR: Command errored out with exit status 1:
   command: 'C:\Users\\AppData\Local\Programs\Python\Python39-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"'; __file__='"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\\AppData\Local\Temp\pip-wheel-xc0m2s9a'
       cwd: C:\Users\\AppData\Local\Temp\pip-install-9x6wk9s7\pylzma_ac46cf6b2edc473abab4b95c02af2510\
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.9
  copying py7zlib.py -> build\lib.win32-3.9
  running build_ext
  adding support for multithreaded compression
  building 'pylzma' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pylzma
  Running setup.py clean for pylzma
Failed to build pylzma
Installing collected packages: pylzma, pycryptodome, lxml, keystone-engine, docopt, colorama, capstone
    Running setup.py install for pylzma ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\\AppData\Local\Programs\Python\Python39-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"'; __file__='"'"'C:\\Users\\\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-bwwe6gaf\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\\AppData\Local\Programs\Python\Python39-32\Include\pylzma'
         cwd: C:\Users\\AppData\Local\Temp\pip-install-9x6wk9s7\pylzma_ac46cf6b2edc473abab4b95c02af2510\
    Complete output (10 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.9
    copying py7zlib.py -> build\lib.win32-3.9
    running build_ext
    adding support for multithreaded compression
    building 'pylzma' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\\AppData\Local\Programs\Python\Python39-32\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\e\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"'; __file__='"'"'C:\\Users\\e\\AppData\\Local\\Temp\\pip-install-9x6wk9s7\\pylzma_ac46cf6b2edc473abab4b95c02af2510\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-bwwe6gaf\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\\AppData\Local\Programs\Python\Python39-32\Include\pylzma' Check the logs for full command output.

**Comment by bkerler** [comment]
Hi sorry, but this is out of scope, as it has nothing to do with edlclient. Don't use python from the windows store, grab python from python.org for windows.
