### ISSUE TITLE
oem unlock command how to use?

### ISSUE THREAD

**Issue by Janer1** [bkerler/edl#20]
Unfortunately there is no "config" partition on my device as it is an lg g7, I was wondering how can i 
[g7.txt](https://github.com/bkerler/edl/files/4442171/g7.txt)
unlock it? if i change the config to something else in the py? 
This is the G7 Parition Table

**Comment by bkerler** [comment]
If there is no config partition, it's very likely that this device has a different partition or mechanism to oem unlock. Could be the devinfo, misc or persdata partition, but that would need to be reversed first.

**Comment by bkerler** [comment]
Fixed with commit 036bc63. If supported, it does now feature both devconfig and config partitions (generic solution).
