### ISSUE TITLE
Loader File for Xiaomi Redmi 9T (lime) / Redmi 9 Power

### ISSUE THREAD

**Issue by TheRedHugo** [bkerler/edl#203]
Hey,
after searching for a long time I found out, that the Engineering Firmware seems to contain a loader, which does not require any authentication. I tested this on a Xiaomi Redmi 9T, although the post states, it would also work on a Xiaomi Redmi Power 9

I found this Engineering Firmware [here](https://forum.xda-developers.com/t/engineering-rom-official-official-engineering-firmware-for-lime-redmi-9-power-redmi-9t.4331847/) on XDA. This post is not mine and I just thought it may be useful for people who are also looking for a way to use EDL on these devices.

I've also uploaded the file on GitHub below
[Download edl-loader](https://github.com/bkerler/edl/files/7695875/prog_firehose_ddr.zip)

**Comment by bkerler** [comment]
Thanks for the info :)
