### ISSUE TITLE
How to get or read out a Loader for Google Pixel 2?

### ISSUE THREAD

**Issue by cubotron** [bkerler/edl#204]
After a restart of my Pixel 2 the screen turned black and the phone is in edl mode. There were no modifcation from me I just wanted to restart my phone.

Now I need to recover some files and my calender.

After using the command "python edl printgpt" I get following:

Qualcomm Sahara / Firehose Client V3.1 (c) B.Kerler 2018-2021.
Library.utils - Trying with no loader given ...
Library.utils - Waiting for the device
Library.utils - Device detected :)
Library.utils - Mode detected: sahara
Device is in EDL mode .. continuing.
Library.sahara -
------------------------
HWID:              0x0005e0e100420002 (MSM_ID:0x0005e0e1,OEM_ID:0x0042,MODEL_ID:0x0002)
PK_HASH:           0x748921750a6ec93122dd7803860fe4f660080a937d6ae9b1d6792edd0886c199
Serial:            0x12261dab

Library.sahara - Couldn't find a loader for given hwid and pkhash (0005e0e100420002_748921750a6ec931_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}

It seems i need a specific loader. How can I get a loader for a Pixel 2?

I have another fully working Pixel 2, can I readout somehow the loader from it?

Many thanks

**Comment by cubotron** [comment]
> restart

int

**Comment by cubotron** [comment]
In the qualcomm loaders I have found an "sdm835" loader. If that loader is for a snapdragon 835 I would give it a try. The question is, will the edl command overwrite a software on the the phone?

What happens if I executed the edl command with the wrong loader, will that damage the phone?

**Comment by bkerler** [comment]
no. but it won't work the pk_hash has to match the loader. For google pixel (except the lg based ones), there haven't been any edl loaders released or leaked.
