### ISSUE TITLE
cannot get any loader to work for MR5100

### ISSUE THREAD

**Issue by Thriftguy** [bkerler/edl#205]
I feel dumb having to ask but what loader is working for MR5100 (sdx55) I tried the zte one in the qualcomm/patched folder but I cannot get it to work.
I treid on windows and linux (ubuntu)
I tried with edl and qtools
![image](https://user-images.githubusercontent.com/96356797/146656990-d82f7590-eb55-4b0d-abb7-32a80e1b3cac.png)
it gives error "package with invalid code"
can someone give me an example of the edl command to use for this device to send the loader please?
I am also needing to make a system file for this device to be loaded via fastboot if anyone has one already and could link me to it :)

**Comment by Thriftguy** [comment]
No love here :(
No one knows of any loader in this repo that can work with MR5100? B Kerler do you know?
I see it says tested with MR5100 but does not say what was tested.

**Comment by bkerler** [comment]
Mr5100 only works in streaming, not firehose mode. Sorry but I need to have a look at my notes which loader has been used for it, as I don't own that device

**Comment by Thriftguy** [comment]
Hi
Thanks for the response.
I assume by firehose mode you mean 9008 is that correct?
and streaming mode is the factory download mode ( hold power and plug cable in) is that correct?
There is almost nothing on the web about this model

**Comment by Thriftguy** [comment]
> Mr5100 only works in streaming, not firehose mode. Sorry but I need to have a look at my notes which loader has been used for it, as I don't own that device

Hi please let me know if any loader in this repository will work, thank you.

**Comment by Thriftguy** [comment]
I assume there is no working loader in this repository. I would suggest removing the quote Tested with mr5100 from it so it does not mislead people as it did me.
