### ISSUE TITLE
MemoryError encountered

### ISSUE THREAD

**Issue by falcox** [bkerler/edl#206]
Hi, I'm currently trying to fix my Oneplus 3T that is more a paperweight than a phone now. 

I've downloaded a decrypted bundle from here: https://www.getdroidtips.com/unbrick-oneplus-device/#ONEPLUS-3T (DECRYPTED OOS 5.0.3), unzipped, extracted with your opscrypto.py and now I'm trying to flash everything in my device but I'm encountering this problem:

MemoryError at this line: https://github.com/bkerler/edl/blob/ca33c497f132c7b5efe866cfe75f30f1d7453bea/edlclient/Library/sparse.py#L136

doing some soft debugging seems that chunk_sz is 7809022 and self.blk_sz is 4096.

It's a pretty big value, do you have anything in mind to overcome this issue?

**Comment by bkerler** [comment]
Try to unsparse it manually using simg2img as a temporary workaround

**Comment by ReFil** [comment]
i'm encountering the same issue
tried unsparsing manually but no luck
