### ISSUE TITLE
Please first install libusb_win32 driver from Zadig - windows

### ISSUE THREAD

**Issue by nucleus3** [bkerler/edl#208]
hello, i'm already installed libusb dk64

>python edl --loader=prog_emmc_firehose_8953_ddr.mbn printgpt
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: [33mPlease first install libusb_win32 driver from Zadig[0m
main - Using loader prog_emmc_firehose_8953_ddr.mbn ...
main - Waiting for the device
main - Device detected :)
main - Unknown mode. Aborting.

**Comment by bkerler** [comment]
libusb dk64 won't work, use zadig ones or use serial port for windows.
