### ISSUE TITLE
Does not work for all processes, read gpt, erase, dump - WINDOWS

### ISSUE THREAD

**Issue by deyvs02** [bkerler/edl#210]
this log below is from the edl printgpt command

it recognizes the device then it is in the process endlessly and it doesn't work

[log.txt](https://www.mediafire.com/file/ac9lu96b9p755fl/log.txt/file)
-------------------------------------------------------------------------------------------------
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: [33mPlease first install libusb_win32 driver from Zadig[0m
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000bf0e100720000 (MSM_ID:0x000bf0e1,OEM_ID:0x0072,MODEL_ID:0x0000)
CPU detected:      "SDM439"
PK_HASH:           0x57158eaf1814d78fd2b3105ece4db18a817a08ac664a5782a925f3ff8403d39a
Serial:            0xc7b0173b

sahara - Detected loader: C:\...\edlclient\..\Loaders\xiaomi\EDLAuth\000bf0e100720000_57158eaf1814d78f_fhprg_edlauth_peek.bin
sahara - Uploading loader C:\...\edlclient\..\Loaders\xiaomi\EDLAuth\000bf0e100720000_57158eaf1814d78f_fhprg_edlauth_peek.bin ...
Successfully uploaded programmer :)
firehose_client - Target detected: SDM439
firehose_client
firehose_client - [LIB]: [33mBased on the chipset, we assume eMMC as default memory type..., if it fails, try using --memory" with "UFS","NAND" or "spinor" instead ![0m
firehose - Xiaomi EDL Auth detected.

Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2) 0.00 MB/s

**Comment by macekboris** [comment]
--memory UFS ?

**Comment by deyvs02** [comment]
> --memory UFS ?

yes

**Comment by bkerler** [comment]
VIP programming, that's why it doesn't work.
