### ISSUE TITLE
ZTE MF920V ISSUES

### ISSUE THREAD

**Issue by ozzie786** [bkerler/edl#211]
1) ZTE MF920V shows 3 interfaces in zadig LIST..  DIAGNOSTIC PORT, NMEA, PROPRIETRY MODEM..... WITH THESE DRIVERS RESPECTIVELY:  ZTEusbser6K , ZTEusbnmea , Modem ...  
 WHICH DRIVER(S) NEEDS TO BE REPLACED BY LIBUSB_WIN32...???
2) QDLOADER 9008 DRIVER IS INSTALLED BUT WHERE IT WILL SHOW?
3) edl COMMAND WORKS BUT DIDNT FIND MY DEVICE....
4) adb reboot edl is not working because no device found....
i am working in windows 10...

**Comment by bkerler** [comment]
Edl is currently broken for windows, but it will be fixed soon.

**Comment by bkerler** [comment]
For zte modem devices you need to use the diag interface orweb interface to enter edl
