### ISSUE TITLE
msm8916 No suitable loader found :(

### ISSUE THREAD

**Issue by 1113870631** [bkerler/edl#215]
It is ok before , if there is something rong with my ubuntu  

HWID:              0x007050e100000000 (MSM_ID:0x007050e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x1c025827

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_e64bdf8cf35bd6d6_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_4614048173062ae4_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/lenovo_motorola/007050e100000000_99c8c13e374c34d8_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/lyf/007050e100000000_394a2e47cf830150_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/xiaomi/007050e100000000_278448179ac756a1_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/xiaomi/007050e100000000_50838757eab7c632_fhprg_peek_wt88047.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_8ecf3eaa03f772e2_fhprg_peek.bin
sahara - Trying loader: /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_e64bdf8cf35bd6d6_fhprg_peek.bin
sahara - Uploading loader /usr/local/lib/python3.6/dist-packages/edlclient-3.53-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_e64bdf8cf35bd6d6_fhprg_peek.bin ...
No suitable loader found :(

**Comment by Un1Gfn** [comment]
what device/brand/model

**Comment by 1113870631** [comment]
> **what device/brand/model?**
> 
> if device does NOT have secure boot enabled (à la `Possibly unfused device detected`), get the unsigned kinda-official
> 
> https://releases.linaro.org/96boards/dragonboard410c/qualcomm/firmware/linux-board-support-package-r1034.2.1.zip
> 
> extract `linux-board-support-package-r1034.2.1/loaders/prog_emmc_firehose_8916.mbn`
> 
> then `edl --loader=prog_emmc_firehose_8916.mbn`
