### ISSUE TITLE
LG V60

### ISSUE THREAD

**Issue by Baddad23** [bkerler/edl#216]
This is happening in both WIndows 11 and Livedvd. This is the exact same firehose I use in Qfil. Was thinking it would be compatible with edl.py?? 

C:\Program Files (x86)\edl>edl.py printgpt --memory=ufs --lun=0 --loader=prog__ufs_firehose_sm8250_lge.elf
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Using loader prog__ufs_firehose_sm8250_lge.elf ...
main - Waiting for the device
main - Device detected :)
main - Unknown mode. Aborting.

**Comment by Baddad23** [comment]
BTW, the sm8250 is the correct chipset for this phone, so if there's anymore info that I can provide???

C:\Program Files (x86)\edl>edl.py printgpt --memory=ufs --lun=0 --loader=000c30e100310000_e746e34f737403f4_fhprg.bin
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Using loader 000c30e100310000_e746e34f737403f4_fhprg.bin ...
main - Waiting for the device
main - Device detected :)
main - Unknown mode. Aborting.

And then there's this without specifying the loader.

C:\Program Files (x86)\edl>edl.py reset
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main
main - [LIB]: ←[33mPlease first install libusb_win32 driver from Zadig←[0m
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Unknown mode. Aborting.

**Comment by bkerler** [comment]
The answer is simple: don't use windows. Libusb with windows is currently very broken. In my last tests I couldn't make it work at all. Use linux and I guess it will work fine.

**Comment by bkerler** [comment]
Edl will normally send a hello package on first connection. For a unknown reason under windows, this first message is suppressed (this wasn't the case on old window releases and zadig drivers). This is why it currently can't work under windows. Sorry.

**Comment by bkerler** [comment]
With the livedvd it should work fine as long as you don't run it under vm. Also remember to restart the edl mode after each failure, as otherwise the connection will fail.

**Comment by Baddad23** [comment]
Thanks for getting back. Tried in livedvd and am now getting:

vedvd@host:/opt/edl$ edl printgpt --memory=ufs --lun=0 --loader=000c30e100310000_e746e34f737403f4_fhprg.bin
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main - Using loader 000c30e100310000_e746e34f737403f4_fhprg.bin ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000c30e100310000 (MSM_ID:0x000c30e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "SM8250:CD90-PH805-1A"
PK_HASH:           0xe746e34f737403f40212cf29f0c0cab9f1038aa8bce6c097e82cc93213020edb
Serial:            0xb6bad6c2

sahara - Uploading loader 000c30e100310000_e746e34f737403f4_fhprg.bin ...
sahara
sahara - [LIB]: [Errno 2] No such file or directory: '000c30e100310000_e746e34f737403f4_fhprg.bin'

livedvd@host:/opt/edl$ edl printgpt --memory=ufs --lun=0
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000c30e100310000 (MSM_ID:0x000c30e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "SM8250:CD90-PH805-1A"
PK_HASH:           0xe746e34f737403f40212cf29f0c0cab9f1038aa8bce6c097e82cc93213020edb
Serial:            0xb6bad6c2

sahara - Found possible loader: /usr/local/lib/python3.8/dist-packages/edlclient-3.53-py3.8.egg/edlclient/../Loaders/LG/000a50e100310000_e746e34f737403f4_fhprg_lg_g8x.bin
sahara - Uploading loader /usr/local/lib/python3.8/dist-packages/edlclient-3.53-py3.8.egg/edlclient/../Loaders/LG/000a50e100310000_e746e34f737403f4_fhprg_lg_g8x.bin ...
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
'NoneType' object is not subscriptable
No suitable loader found :(

**Comment by Baddad23** [comment]
Please forget second error cause it pick up the lg_g8x loader

**Comment by Baddad23** [comment]
Please respond. The following error ([Errno 2] No such file or directory: '000c30e100310000_e746e34f737403f4_fhprg.bin'),
is the result of running edl using the loader you included in your recently updated "Loaders" directory. This was all done on a newly created Ubuntu install on an old laptop of mine. NO WINDOWS INVOLVED.


edl$ edl printgpt --memory=ufs --lun=0 --loader=000c30e100310000_e746e34f737403f4_fhprg.bin
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main - Using loader 000c30e100310000_e746e34f737403f4_fhprg.bin ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...............
....main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000c30e100310000 (MSM_ID:0x000c30e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "SM8250:CD90-PH805-1A"
PK_HASH:           0xe746e34f737403f40212cf29f0c0cab9f1038aa8bce6c097e82cc93213020edb
Serial:            0xff08b1ae

sahara - Uploading loader 000c30e100310000_e746e34f737403f4_fhprg.bin ...
sahara
sahara - [LIB]: [Errno 2] No such file or directory: '000c30e100310000_e746e34f737403f4_fhprg.bin'
