### ISSUE TITLE
Support of sierra RC series in sierrakeygen planned?

### ISSUE THREAD

**Issue by Whinegum** [bkerler/edl#219]
Hi,

I just tried out the sierrakeygen in order to get the challenge response for the Sierra RC7620 which is based on the qualcomm MDM9607 baseline.

AT!OPENLOCK?                                                                                                                
0001,!OPENLOCK,F0671EF8C90666D27E25413263341D21E7E3829DB5DE27C5FC4FA96EF21ADD92,0003,7Q1473303001F015

I tried your tool with the device parameter "MDM9x07" and I inserted "F0671EF8C90666D27E25413263341D21E7E3829DB5DE27C5FC4FA96EF21ADD92" as challenge

Ether I did somethin wrong or not the whole MDM9x07 baseline is supported, yet.
Any ideas?

Thanks and kind regards.

**Comment by bkerler** [comment]
Sorry, they changed the algo again. Support isn't planned right now.
