### ISSUE TITLE
Infinite "Timed out" and errors in the log without debug mode.

### ISSUE THREAD

**Issue by BudDeuce** [bkerler/edl#227]
I heard about the rewrite of EDL and was excited because I was waiting for an update that can potentially fix my issue from August. Progress has been made but there are new errors too. I will upload both logs to show you the problems described in the title.
[debug_log.txt](https://github.com/bkerler/edl/files/7982624/debug_log.txt)
[normal_log.txt](https://github.com/bkerler/edl/files/7982625/normal_log.txt)

**Comment by bkerler** [comment]
Thanks, I will have a look.

**Comment by Tryzen-0** [comment]
Same issue when trying with Samsung Galaxy Ace GT-S5830 running Snapdragon S1 MSM7227

**Comment by BudDeuce** [comment]
Sorry to say this, but QFIL is now working for me, I used this as an alternative to QFIL.

For everyone looking for the files needed to unlock the bootloader/root, here they are:
[g7one.zip](https://github.com/bkerler/edl/files/9237845/g7one.zip)

Credits to [GMSS75](https://forum.xda-developers.com/m/gmss75.11866315/) for the guide with the files needed to help me recover my phone from the red triangle of death: https://forum.xda-developers.com/t/lg-g7-one-bootloader-unlock-how-to.4421917/
