### ISSUE TITLE
can't use any command 

### ISSUE THREAD

**Issue by 1113870631** [bkerler/edl#230]
jsut like this ,is anything rong ?   

             
`edl                                                       
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x007050e100000000 (MSM_ID:0x007050e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x1c025827

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_4614048173062ae4_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/lenovo_motorola/007050e100000000_99c8c13e374c34d8_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/lyf/007050e100000000_394a2e47cf830150_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/xiaomi/007050e100000000_278448179ac756a1_fhprg_peek.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/xiaomi/007050e100000000_50838757eab7c632_fhprg_peek_wt88047.bin
sahara - Possible loader available: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_8ecf3eaa03f772e2_fhprg_peek.bin
sahara - Trying loader: /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
sahara - Protocol version: 2.1
sahara - Uploading loader /usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
edl ➤ edl printgpt                            
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - logbuf@0x0801CDB8 fh@0x08019C20
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
edl ➤    `

**Comment by yjun123** [comment]
I have a msm8916 device too, same error/problem when using edl 3.60 version, but revert to edl 3.53, command, for example `edl printgpt`, It works!

**Comment by 1113870631** [comment]
> I have a msm8916 device too, same error/problem when using edl 3.60 version, but revert to edl 3.53, command, for example `edl secureboot`, It works!
> 
> edl 3.60: https://pastebin.com/p5qDhrNs edl 3.53: https://pastebin.com/6j4DNfX6

ok i will have a try thanks

**Comment by bkerler** [comment]
Does it mean it just hangs ? Can you provide a full debug log ?

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?

Just like upstairs yjun123 said I used edl 3.53 it's ok ,the   latest version is not ok

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?

there is some log 
![2022-03-23 20-51-03 的屏幕截图](https://user-images.githubusercontent.com/61228813/159703436-62da01bc-5628-4112-8abe-9d5d1e9b40db.png)
![2022-03-23 20-51-30 的屏幕截图](https://user-images.githubusercontent.com/61228813/15970345
![2022-03-23 20-52-31 的屏幕截图](https://user-images.githubusercontent.com/61228813/159703550-a6fd2743-ef4d-4032-b4cb-4442dd1324fb.png)
5-2e063c83-4e95-4fc2-868f-4441389dbd5e.png)
[log.txt](https://github.com/bkerler/edl/files/8333116/log.txt)

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?
there is the log i use the command edl printgpt 

`CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
Timed out
Timed out
Timed out
Timed out
Timed out
Timed out
Timed out
Timed out
Timed out
Timed out
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 293, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 207, in doconnect\n    resp = self.sahara.connect()\n']
TX:<?xml version="1.0" ?><data><nop /></data>
read:0x200
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 293, in run\n    conninfo = self.doconnect(loop)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 207, in doconnect\n    resp = self.sahara.connect()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/sahara.py", line 131, in connect\n    res = self.cdc.read(timeout=1)\n']
RX:<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" /></data>
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 375, in run\n    if fh.connect(sahara):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose_client.py", line 109, in connect\n    if self.firehose.configure(0):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 848, in configure\n    rsp = self.xmlsend(connectcmd)\n']
TX:<?xml version="1.0" encoding="UTF-8" ?><data><configure MemoryName="eMMC" Verbose="0" AlwaysValidate="0" MaxDigestTableSizeInBytes="2048" MaxPayloadSizeToTargetInBytes="1048576" ZLPAwareHost="1" SkipStorageInit="0" SkipWrite="0"/></data>
read:0x200
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 375, in run\n    if fh.connect(sahara):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose_client.py", line 109, in connect\n    if self.firehose.configure(0):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 848, in configure\n    rsp = self.xmlsend(connectcmd)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 246, in xmlsend\n    tmp = self.cdc.read(timeout=None)\n']
RX:<?xml version="1.0" encoding="UTF-8" ?><data><log value="Host's payload to target size is too large" /></data>
read:0x200
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 375, in run\n    if fh.connect(sahara):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose_client.py", line 109, in connect\n    if self.firehose.configure(0):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 848, in configure\n    rsp = self.xmlsend(connectcmd)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 246, in xmlsend\n    tmp = self.cdc.read(timeout=None)\n']
RX:<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0801BDC8 fh@0x08018C30" /></data>
read:0x200
['  File "/usr/local/bin/edl", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'edlclient==3.60\', \'edl\')\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script\n    self.require(requires)[0].run_script(script_name, ns)\n', '  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script\n    exec(code, namespace, namespace)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 380, in <module>\n    base.run()\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/EGG-INFO/scripts/edl", line 375, in run\n    if fh.connect(sahara):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose_client.py", line 109, in connect\n    if self.firehose.configure(0):\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 848, in configure\n    rsp = self.xmlsend(connectcmd)\n', '  File "/usr/local/lib/python3.6/dist-packages/edlclient-3.60-py3.6.egg/edlclient/Library/firehose.py", line 246, in xmlsend\n    tmp = self.cdc.read(timeout=None)\n']
RX:<?xml version="1.0" encoding="UTF-8" ?><data><response value="NAK" MinVersionSupported="1" MemoryName="eMMC" MaxPayloadSizeFromTargetInBytes="4096" MaxPayloadSizeToTargetInBytes="16384" MaxPayloadSizeToTargetInBytesSupported="16384" MaxXMLSizeInBytes="4096" Version="1" TargetName="8916" /></data>
`

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?

![2022-03-23 20-51-03 的屏幕截图](https://user-images.githubusercontent.com/61228813/159704932-949f8d75-7d3c-486e-a016-1f90881ef7ec.png)

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?

and more log 
![2022-03-23 21-02-01 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705539-dc11eee8-2052-4d4e-a775-a7a9732de0c0.png)
![2022-03-23 21-02-20 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705551-58d947d5-7165-459c-9246-88e2154b884b.png)
![2022-03-23 21-02-27 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705556-645aa314-a481-49e2-a530-90bcc195d064.png)
![2022-03-23 21-02-34 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705563-3fa41309-827b-4cd0-b7f4-d37d093ab6e7.png)
![2022-03-23 21-02-46 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705569-4428ccb8-d4f7-4ffb-88e0-1ab1bd60719f.png)
![2022-03-23 21-02-54 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705575-b49fde95-b918-43da-a9ca-b321de1de259.png)
![2022-03-23 21-03-02 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705579-b6bdf85e-519e-42d5-8e52-6a522d18c82c.png)
![2022-03-23 21-03-10 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705584-586e2350-54dd-4f72-9307-2756c5d7108b.png)

**Comment by 1113870631** [comment]
> Does it mean it just hangs ? Can you provide a full debug log ?

more 
![2022-03-23 21-02-01 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706146-36801fb1-9f58-4ab9-97c8-4a7dae52b926.png)

**Comment by 1113870631** [comment]
> > Does it mean it just hangs ? Can you provide a full debug log ?
> 
> ![2022-03-23 20-51-03 的屏幕截图](https://user-images.githubusercontent.com/61228813/159704932-949f8d75-7d3c-486e-a016-1f90881ef7ec.png) ![2022-03-23 20-51-30 的屏幕截图](https://user-images.githubusercontent.com/61228813/159705014-3a9e58d6-9f62-4a08-9f3b-a378723cb844.png) [log.txt](https://github.com/bkerler/edl/files/8333154/log.txt)

more 

`
![2022-03-23 21-02-01 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706380-6df48193-1205-4bc1-b033-efe6b81da3bf.png)
![2022-03-23 21-02-20 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706392-91eeba3a-0215-492d-8481-43077bb01f22.png)
![2022-03-23 21-02-27 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706397-7b55f31e-d0fa-4b55-9a8b-d25855356646.png)
![2022-03-23 21-02-34 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706400-05a694fc-4a70-478a-892f-321605635ac0.png)
![2022-03-23 21-02-46 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706407-2e0582f0-c511-46f5-9d28-ed84e4eb7192.png)
![2022-03-23 21-02-54 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706412-d67a065f-12db-4bdd-8a18-04c23e3e7e8d.png)
![2022-03-23 21-03-02 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706415-5194856b-ccab-4de7-8262-2c557377c606.png)
![2022-03-23 21-03-10 的屏幕截图](https://user-images.githubusercontent.com/61228813/159706425-f9b5c859-6dd7-4044-8c29-6e7fc7af1d1f.png)
`

**Comment by mrichar1** [comment]
Experiencing the same issue with an MSM8909 device. Last 'good' commit is: d5ff2d474a185a0c0df09c74dfa24eb7cfe6e9e5 - anything after that drops out as described above.

**Comment by 1113870631** [comment]
> Experiencing the same issue with an MSM8909 device. Last 'good' commit is: [d5ff2d4](https://github.com/bkerler/edl/commit/d5ff2d474a185a0c0df09c74dfa24eb7cfe6e9e5) - anything after that drops out as described above.

OK thank you very much

**Comment by AlxndrJhn** [comment]
I am also experiencing a hanging application

```
pi@raspberrypi:~/bayer/edl $ edl
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
```

hangs afterwards.

to fix this I did the following in the cloned repo

```
git reset --hard d5ff2d474a185a0c0df09c74dfa24eb7cfe6e9e5
python setup.py build
sudo python setup.py install
```

**Comment by B83C** [comment]
Same issue here with MSM8937 which is fixed with the reversion of the commit

**Comment by TheSpecialist666** [comment]
> 

Maaaaan I can't thank you enough for this!!!!! This fixed my issue as well

**Comment by 1113870631** [comment]
git reset --hard d5ff2d474a185a0c0df09c74dfa24eb7cfe6e9e5
python setup.py build
sudo python setup.py install
