### ISSUE TITLE
Add Patch 9X5X chipset new bootloaders

### ISSUE THREAD

**Issue by AliRazaManzoor** [bkerler/edl#231]
i have found huawei e5788 original bootloaders it is base upon qualcomm 9x5x chipset ,i try all bootloaders in your folder loaders/qualcomm/9x5x/enprg_9x55p.mbn it not work , so i have original bootloaders ,loader is attached please patch bootloaders and add in loader/qualcomm/9x5x/ folder .
[bootloaderimage_e5788.zip](https://github.com/bkerler/edl/files/8052900/bootloaderimage_e5788.zip)

**Comment by bkerler** [comment]
Is the device unfused ? If it's fused, patching won't work

**Comment by AliRazaManzoor** [comment]
yes it is unfused .tr and patch and upload in related section .

**Comment by bkerler** [comment]
[e5788_patched.zip](https://github.com/bkerler/edl/files/11178430/e5788_patched.zip)
Here you go.

**Comment by Z9044234820** [comment]
Where/how did you find the E5788 loader? My E5788 is currently bricked, and It does not seem to work for me.
