### ISSUE TITLE
Please add Loader for Oppo A74 4G (SDM662)

### ISSUE THREAD

**Issue by kingilein** [bkerler/edl#234]
root@host:/opt/edl# edl printgpt --memory=ufs --lun=0
Qualcomm Sahara / Firehose Client V3.53 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x0014d0e100510000 (MSM_ID:0x0014d0e1,OEM_ID:0x0051,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0x49445e14621312dfeccd4389f267e6b71674ddd36b1bc41d1f605aa991d14ad6
Serial:            0x4b461bf8

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (0014d0e100510000_49445e14621312df_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}
root@host:/opt/edl# 

Loader for Oppo A74 4G

**Comment by bkerler** [comment]
Hi, even if I would add a loader for Oppo, they're VIP protected. So no edl tool will be usable, sorry.
