### ISSUE TITLE
ModuleNotFoundError: No module named 'termios'

### ISSUE THREAD

**Issue by macekboris** [bkerler/edl#239]
Capstone library is missing (optional).
Keystone library is missing (optional).
Traceback (most recent call last):
  File "C:\Users\Boris Maček\edl\edl", line 133, in <module>
    from edlclient.Library.Connection.seriallib import serial_class
  File "C:\Users\Boris Maček\edl\edlclient\Library\Connection\seriallib.py", line 6, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

Python on win10

**Comment by macekboris** [comment]
It's only available for linux :(

**Comment by Baddad23** [comment]
I suggest you DL the livedvd and create the usb drive using rufus. Boot the newly created usb drive and copy the edl folder to a windows drive. Reboot into Windows and copy the usb edl folder that you just saved to the location of your original windows edl install. Probably is a good idea to rename the original to something like "edl old".  Then give it a try. 

The entire windows install process is a mess. I'll just say it took a while for me to get my windows' "Bkerler edl" up an running. In the end I had to use the Edl folder off of my livedvd 2  usb drive.

**Comment by RenateUSB** [comment]
Just comment out the two lines.
#import termios
#termios.tcflush(self.fd, termios.TCIFLUSH)

**Comment by macekboris** [comment]
Thx !

**Comment by bkerler** [comment]
I will provide a bug fix for that, thx for the info !

**Comment by bkerler** [comment]
Should be solved with commit 5227493
