### ISSUE TITLE
I used it to recover OP 9 PRO. It gives the error "edl.py does not exist". Ubuntu, Windows. chosen

### ISSUE THREAD

**Issue by wise1453** [bkerler/edl#243]
I am visually impaired. I have OP 9 Pro LE2120 Phone. My phone crashed. I can't use anything other than EDL. I'm trying to recover with MSM. Sahara throws Params errors. I discovered your EDL tools. I tried it on UBUNTU and Windows 10. "The edl.py file does not exist." even though I did everything in both. I get an error. I'm looking at the EDL folder. There is a file called EDL. But it has no extension. Nothing else. I have installed all the requirements. I am running UBUNTU as subsystem. I also tried with MAC. There are OP 9 files inside the files. There is no OP 9 Pro. This also surprised me. I need to repair my Firehose file. the phone is establishing a connection with the computer. 9008 port is active. The phone disconnects every 18 seconds. This causes a sahara error or a params error. It is the MSM Download Tools program that brings the phone to this state. The program failed during the initial recovery. Then the phone crashed. Please help me. I also looked at your explanation. I've read it many times. There is no detailed explanation. There is a general purpose redirect. I looked for ways to solve my problem. I saw a member's thread on the XDA forum. He solved it. But, I can't. Please help me.

edl.py does not exist. What am I missing? I do all the commands the same way.

**Comment by bkerler** [comment]
Hi, use edl instead of edl.py and it should work fine.

**Comment by EduardoA3677** [comment]
> 
Hello I have the same problem as you, did you solve it?, and could you tell me your telegram to talk
