### ISSUE TITLE
The 'pylzma' distribution was not found and is required by edlclient

### ISSUE THREAD

**Issue by zenminimalist** [bkerler/edl#245]
I get the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pylzma' distribution was not found and is required by edlclient`

I tried  **pip install pylzma** but get this:

`DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pylzma in /usr/local/lib/python3.9/site-packages (0.5.0)`

Any ideas how to fix this? I tried reinstalling pylzma, uninstalling it and running a edl command. Same problem...

**Comment by bkerler** [comment]
That might happen if your python install is too new (like 3.10). I'm not sure where I use pylzma, I will have a look if it is replaceable.

**Comment by dengshuangjang** [comment]
delete it in file requirements.txt.

**Comment by RayPS** [comment]
Same issue but `pip install pylzma` worked for me.

**Comment by Moon379** [comment]
Hey brother i am facing same issue can you help me how to solve this

**Comment by kroon040** [comment]
Here stiil same issue on debian bookworm. It is nog in de requirments.txt but still the error

**Comment by zipzagster** [comment]
same issue

**Comment by zabrewer** [comment]
I have run into this issue on both debian and macOS and have resolved on both. If you have run into it, there are a few ways to resolve:
 
1) First, go into setup.py and find the line with 'pylzma' (line 30) - delete it or comment it out with a leading #.  This package is not used and does not appear in the requirements.txt

 2) setup.py is no longer recommended.  instead of installing with setup.py it's recommended to use pip.  While in the same directory as setup.py, requirements.txt, and pyproject.toml run:

`pip3 install .`

If you have already followed the README instructions, you may need to remove the wheels that were installed for this to work - this various depending on distribution/OS and python version.  You may need to research.  If you use virtual environments like I do, this can be as simple as deleting the virtual environment directory and re-creating it, then activating the virtual env and folowing steps 1 and 2 that I listed above.  If you re-run the setup commands that failed in your original steps, the python CLI should give some indication of where it is building the various wheels for this project's dependencies.

**Comment by BlairSadewitz** [comment]
Is this dependency still needed?

**Comment by abdedarghal111** [comment]
Hi, I am having the pylzma issue. 

- I am on arch linux.
- I tried pip, pip3, pyenv, yay and I can't install it. 
- It looks like it is a gcc compilation problem but I don't have the enought knowedge to solve it. 
- pylzma it looks like it is needed when reading data from the device.
- Here my stacktrace when run `sudo python3 setup.py install | tee instalationLog.txt`: [instalationLog.txt](https://github.com/user-attachments/files/17474951/instalationLog.txt)
- Here is the interesting part:
```
self.initialize_options()
/tmp/easy_install-rxe3mhpw/pylzma-0.5.0/setup.py:105: UnsupportedPlatformWarning: Multithreading is not supported on the platform "linux",
please contact mail@joachim-bauch.de for more informations.
  warn("""\
src/pylzma/pylzma.c: En la función ‘PyInit_pylzma’:
src/pylzma/pylzma.c:296:5: aviso: ‘PyEval_InitThreads’ es obsoleto [-Wdeprecated-declarations]
  296 |     PyEval_InitThreads();
      |     ^~~~~~~~~~~~~~~~~~
En el fichero incluido desde /usr/include/python3.12/Python.h:95,
                 desde src/pylzma/pylzma.c:26:
/usr/include/python3.12/ceval.h:132:37: nota: se declara aquí
  132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
src/pylzma/pylzma_aes.c:158:5: error: la inicialización de ‘long int’ desde ‘void *’ crea un entero desde un puntero sin una conversión [-Wint-conversion]
  158 |     NULL,                                /* printfunc  tp_print;   */
      |     ^~~~
src/pylzma/pylzma_aes.c:158:5: nota: (cerca de la inicialización de ‘CAESDecrypt_Type.tp_vectorcall_offset’)
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by gabrielkaiiio** [comment]
É por isso que odeio o Linux, se fosse no Windows em 4 cliques o meu problema estaria resolvido. Essa é praticamente a unica ferramenta, do linux, que consegue fleshar uma ROM via Brom nos modelo xiaomi sem apresentar centenas de erros como aquela porcaria do SPflashTool, que não flesha nunca, sempre tem um erro.
