### ISSUE TITLE
Oppo prjid 19672

### ISSUE THREAD

**Issue by WinKarbik** [bkerler/edl#26]
Could you add Realme X2 support? Now I try to erase userdata, but nothing happen. When manually added 19672 in list of support, it stucks here:
`HWID:              0x000e60e100510000 (MSM_ID:0x000e60e1,OEM_ID:0x0051,MODEL_ID:0x0000)
PK_HASH:           0x32942e378adbc21376abb8b83a681e579bfebf5926c5bdc53b08f35738147041
Serial:            0x706d7079
SBL Version:       0x00000000

Library.sahara - Detected loader: Loaders/000E60E100510000_32942e378adbc213_FHPRG.bin
Successfully uploaded programmer :)
Library.firehose - INFO: Chip serial num: 1886220409 (0x706d7079)
Library.firehose - 
Library.firehose - TargetName=
Library.firehose - MemoryName=eMMC
Library.firehose - Version=
__main__ - Supported functions:
-----------------
`
Dnt know why autodetect use eMMC, as I know there UFS used< but with manually chosed ufs still dnt work:

`
HWID:              0x000e60e100510000 (MSM_ID:0x000e60e1,OEM_ID:0x0051,MODEL_ID:0x0000)
PK_HASH:           0x32942e378adbc21376abb8b83a681e579bfebf5926c5bdc53b08f35738147041
Serial:            0x706d7079
SBL Version:       0x00000000

Library.sahara - Detected loader: Loaders/000E60E100510000_32942e378adbc213_FHPRG.bin
Successfully uploaded programmer :)
Library.firehose - INFO: Chip serial num: 1886220409 (0x706d7079)
Library.firehose - 
Library.firehose - TargetName=
Library.firehose - MemoryName=ufs
Library.firehose - Version=
__main__ - Supported functions:
-----------------
`

**Comment by bkerler** [comment]
Sorry to say, but oppo uses vip programming, which only allows to send signed binaries using prehashes which edl doesn't support right now.
