### ISSUE TITLE
Error: Range Restricted

### ISSUE THREAD

**Issue by FranciscoManzanilla** [bkerler/edl#267]
Hi, good afternoon. I've the next problem
frankdev@frankdev-Inspiron-3505:~/Escritorio/sa/edl$ edl rl dumps --memory=emmc --lun=0 --skip=userdata,vendor_a --loader=Loaders/g10.elf
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader Loaders/g10.elf ...
main - Waiting for the device ...
main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x001360e102e80000 (MSM_ID:0x001360e1,OEM_ID:0x02e8,MODEL_ID:0x0000)
CPU detected:      "kamorta"
PK_HASH:           0xabbcc86fe393b13d59e2a2ec944af26da3fa3d4b2a1ccd2fb383c73e0fffc30d
Serial:            0xcf341a89

sahara - Protocol version: 2.1
sahara - Uploading loader Loaders/g10.elf ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose - INFO: Binary build date: Jan 28 2022 @ 13:31:37
firehose - INFO: Binary build date: Jan 28 2022 @ 13:31:37 
firehose - INFO: Chip serial num: 3476298377 (0xcf341a89)
firehose - INFO: Supported Functions (17):
firehose - INFO: program
firehose - INFO: read
firehose - INFO: nop
firehose - INFO: patch
firehose - INFO: configure
firehose - INFO: setbootablestoragedrive
firehose - INFO: erase
firehose - INFO: power
firehose - INFO: firmwarewrite
firehose - INFO: getstorageinfo
firehose - INFO: benchmark
firehose - INFO: emmc
firehose - INFO: ufs
firehose - INFO: fixgpt
firehose - INFO: getsha256digest
firehose - INFO: getvar
firehose - INFO: dump
firehose - INFO: End of supported functions 17
firehose
firehose - [LIB]: Couldn't detect MaxPayloadSizeFromTargetinBytes
firehose
firehose - [LIB]: Couldn't detect TargetName
firehose - TargetName=Unknown
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose - Storage report:
firehose - total_blocks:122142720
firehose - block_size:512
firehose - page_size:512
firehose - num_physical:4
firehose - manufacturer_id:19
firehose - serial_num:572539329
firehose - fw_version:4
firehose - mem_type:eMMC
firehose - prod_name:S0J9K8
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,getvar,dump
firehose_client - Dumping partition xbl_a with sector count 10240 as dumps/xbl_a.bin.
firehose - 
Reading from physical partition 0, sector 131072, sectors 10240
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2800) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x2800 of 0x2800, ) 30.48 MB/s
firehose_client - Dumped partition xbl_a with sector count 10240 as dumps/xbl_a.bin.
firehose_client - Dumping partition xbl_b with sector count 10240 as dumps/xbl_b.bin.
firehose - 
Reading from physical partition 0, sector 141312, sectors 10240
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2800) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x2800 of 0x2800, ) 30.98 MB/s
firehose_client - Dumped partition xbl_b with sector count 10240 as dumps/xbl_b.bin.
firehose_client - Dumping partition xbl_config_a with sector count 256 as dumps/xbl_config_a.bin.
firehose - 
Reading from physical partition 0, sector 151552, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 32.33 MB/s
firehose_client - Dumped partition xbl_config_a with sector count 256 as dumps/xbl_config_a.bin.
firehose_client - Dumping partition xbl_config_b with sector count 256 as dumps/xbl_config_b.bin.
firehose - 
Reading from physical partition 0, sector 151808, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 32.74 MB/s
firehose_client - Dumped partition xbl_config_b with sector count 256 as dumps/xbl_config_b.bin.
firehose_client - Dumping partition tz_a with sector count 8192 as dumps/tz_a.bin.
firehose - 
Reading from physical partition 0, sector 152064, sectors 8192
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2000) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x2000 of 0x2000, ) 31.46 MB/s
firehose_client - Dumped partition tz_a with sector count 8192 as dumps/tz_a.bin.
firehose_client - Dumping partition tz_b with sector count 8192 as dumps/tz_b.bin.
firehose - 
Reading from physical partition 0, sector 160256, sectors 8192
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x2000) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x2000 of 0x2000, ) 30.12 MB/s
firehose_client - Dumped partition tz_b with sector count 8192 as dumps/tz_b.bin.
firehose_client - Dumping partition rpm_a with sector count 1024 as dumps/rpm_a.bin.
firehose - 
Reading from physical partition 0, sector 168448, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 34.70 MB/s
firehose_client - Dumped partition rpm_a with sector count 1024 as dumps/rpm_a.bin.
firehose_client - Dumping partition rpm_b with sector count 1024 as dumps/rpm_b.bin.
firehose - 
Reading from physical partition 0, sector 262144, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 35.83 MB/s
firehose_client - Dumped partition rpm_b with sector count 1024 as dumps/rpm_b.bin.
firehose_client - Dumping partition hyp_a with sector count 1024 as dumps/hyp_a.bin.
firehose - 
Reading from physical partition 0, sector 393216, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 36.72 MB/s
firehose_client - Dumped partition hyp_a with sector count 1024 as dumps/hyp_a.bin.
firehose_client - Dumping partition hyp_b with sector count 1024 as dumps/hyp_b.bin.
firehose - 
Reading from physical partition 0, sector 394240, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 37.21 MB/s
firehose_client - Dumped partition hyp_b with sector count 1024 as dumps/hyp_b.bin.
firehose_client - Dumping partition cmnlib_a with sector count 1024 as dumps/cmnlib_a.bin.
firehose - 
Reading from physical partition 0, sector 395264, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 38.63 MB/s
firehose_client - Dumped partition cmnlib_a with sector count 1024 as dumps/cmnlib_a.bin.
firehose_client - Dumping partition cmnlib_b with sector count 1024 as dumps/cmnlib_b.bin.
firehose - 
Reading from physical partition 0, sector 396288, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 37.66 MB/s
firehose_client - Dumped partition cmnlib_b with sector count 1024 as dumps/cmnlib_b.bin.
firehose_client - Dumping partition cmnlib64_a with sector count 1024 as dumps/cmnlib64_a.bin.
firehose - 
Reading from physical partition 0, sector 397312, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 37.98 MB/s
firehose_client - Dumped partition cmnlib64_a with sector count 1024 as dumps/cmnlib64_a.bin.
firehose_client - Dumping partition cmnlib64_b with sector count 1024 as dumps/cmnlib64_b.bin.
firehose - 
Reading from physical partition 0, sector 398336, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 37.73 MB/s
firehose_client - Dumped partition cmnlib64_b with sector count 1024 as dumps/cmnlib64_b.bin.
firehose_client - Dumping partition keymaster_a with sector count 1024 as dumps/keymaster_a.bin.
firehose - 
Reading from physical partition 0, sector 399360, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 36.26 MB/s
firehose_client - Dumped partition keymaster_a with sector count 1024 as dumps/keymaster_a.bin.
firehose_client - Dumping partition keymaster_b with sector count 1024 as dumps/keymaster_b.bin.
firehose - 
Reading from physical partition 0, sector 400384, sectors 1024
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x400) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x400 of 0x400, ) 36.93 MB/s
firehose_client - Dumped partition keymaster_b with sector count 1024 as dumps/keymaster_b.bin.
firehose_client - Dumping partition prov_a with sector count 512 as dumps/prov_a.bin.
firehose - 
Reading from physical partition 0, sector 401408, sectors 512
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x200) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x200 of 0x200, ) 34.11 MB/s
firehose_client - Dumped partition prov_a with sector count 512 as dumps/prov_a.bin.
firehose_client - Dumping partition prov_b with sector count 512 as dumps/prov_b.bin.
firehose - 
Reading from physical partition 0, sector 401920, sectors 512
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x200) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x200 of 0x200, ) 34.81 MB/s
firehose_client - Dumped partition prov_b with sector count 512 as dumps/prov_b.bin.
firehose_client - Dumping partition abl_a with sector count 2048 as dumps/abl_a.bin.
firehose - 
Reading from physical partition 0, sector 402432, sectors 2048
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x800) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x800 of 0x800, ) 37.50 MB/s
firehose_client - Dumped partition abl_a with sector count 2048 as dumps/abl_a.bin.
firehose_client - Dumping partition abl_b with sector count 2048 as dumps/abl_b.bin.
firehose - 
Reading from physical partition 0, sector 404480, sectors 2048
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x800) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x800 of 0x800, ) 39.29 MB/s
firehose_client - Dumped partition abl_b with sector count 2048 as dumps/abl_b.bin.
firehose_client - Dumping partition uefisecapp_a with sector count 4096 as dumps/uefisecapp_a.bin.
firehose - 
Reading from physical partition 0, sector 406528, sectors 4096
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x1000) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x1000 of 0x1000, ) 32.90 MB/s
firehose_client - Dumped partition uefisecapp_a with sector count 4096 as dumps/uefisecapp_a.bin.
firehose_client - Dumping partition uefisecapp_b with sector count 4096 as dumps/uefisecapp_b.bin.
firehose - 
Reading from physical partition 0, sector 410624, sectors 4096
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x1000) 0.00 MBProgress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x1000 of 0x1000, ) 31.67 MB/s
firehose_client - Dumped partition uefisecapp_b with sector count 4096 as dumps/uefisecapp_b.bin.
firehose_client - Dumping partition devcfg_a with sector count 256 as dumps/devcfg_a.bin.
firehose - 
Reading from physical partition 0, sector 414720, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 32.93 MB/s
firehose_client - Dumped partition devcfg_a with sector count 256 as dumps/devcfg_a.bin.
firehose_client - Dumping partition devcfg_b with sector count 256 as dumps/devcfg_b.bin.
firehose - 
Reading from physical partition 0, sector 414976, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 31.95 MB/s
firehose_client - Dumped partition devcfg_b with sector count 256 as dumps/devcfg_b.bin.
firehose_client - Dumping partition qupfw_a with sector count 160 as dumps/qupfw_a.bin.
firehose - 
Reading from physical partition 0, sector 415232, sectors 160
Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0xA0 of 0xA0, ) 31.45 MB/s
firehose_client - Dumped partition qupfw_a with sector count 160 as dumps/qupfw_a.bin.
firehose_client - Dumping partition qupfw_b with sector count 160 as dumps/qupfw_b.bin.
firehose - 
Reading from physical partition 0, sector 415392, sectors 160
Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0xA0 of 0xA0, ) 29.39 MB/s
firehose_client - Dumped partition qupfw_b with sector count 160 as dumps/qupfw_b.bin.
firehose_client - Dumping partition storsec_a with sector count 256 as dumps/storsec_a.bin.
firehose - 
Reading from physical partition 0, sector 415552, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 32.06 MB/s
firehose_client - Dumped partition storsec_a with sector count 256 as dumps/storsec_a.bin.
firehose_client - Dumping partition storsec_b with sector count 256 as dumps/storsec_b.bin.
firehose - 
Reading from physical partition 0, sector 415808, sectors 256
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x100) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x100 of 0x100, ) 31.96 MB/s
firehose_client - Dumped partition storsec_b with sector count 256 as dumps/storsec_b.bin.
firehose_client - Dumping partition ddr with sector count 2048 as dumps/ddr.bin.
firehose - 
Reading from physical partition 0, sector 416064, sectors 2048
Done |--------------------------------------------------|   0.0% Read (Sector 0x0 of 0x800) 0.00 MB/Progress: |██████████████████████████████████████████████████| 100.0% Read (Sector 0x800 of 0x800, ) 38.39 MB/s
firehose_client - Dumped partition ddr with sector count 2048 as dumps/ddr.bin.
firehose_client - Dumping partition modem_a with sector count 368640 as dumps/modem_a.bin.
firehose - 
Reading from physical partition 0, sector 418112, sectors 368640
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=418112, num_sectors=368640']
firehose_client - Dumping partition modem_b with sector count 368640 as dumps/modem_b.bin.
firehose - 
Reading from physical partition 0, sector 786752, sectors 368640
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=786752, num_sectors=368640']
firehose_client - Dumping partition bluetooth_a with sector count 2048 as dumps/bluetooth_a.bin.
firehose - 
Reading from physical partition 0, sector 1155392, sectors 2048
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1155392, num_sectors=2048']
firehose_client - Dumping partition bluetooth_b with sector count 2048 as dumps/bluetooth_b.bin.
firehose - 
Reading from physical partition 0, sector 1157440, sectors 2048
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1157440, num_sectors=2048']
firehose_client - Dumping partition dsp_a with sector count 131072 as dumps/dsp_a.bin.
firehose - 
Reading from physical partition 0, sector 1159488, sectors 131072
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1159488, num_sectors=131072']
firehose_client - Dumping partition dsp_b with sector count 131072 as dumps/dsp_b.bin.
firehose - 
Reading from physical partition 0, sector 1290560, sectors 131072
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1290560, num_sectors=131072']
firehose_client - Dumping partition boot_a with sector count 196608 as dumps/boot_a.bin.
firehose - 
Reading from physical partition 0, sector 1421632, sectors 196608
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1421632, num_sectors=196608']
firehose_client - Dumping partition boot_b with sector count 196608 as dumps/boot_b.bin.
firehose - 
Reading from physical partition 0, sector 1618240, sectors 196608
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1618240, num_sectors=196608']
firehose_client - Dumping partition dtbo_a with sector count 49152 as dumps/dtbo_a.bin.
firehose - 
Reading from physical partition 0, sector 1814848, sectors 49152
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1814848, num_sectors=49152']
firehose_client - Dumping partition dtbo_b with sector count 49152 as dumps/dtbo_b.bin.
firehose - 
Reading from physical partition 0, sector 1864000, sectors 49152
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1864000, num_sectors=49152']
firehose_client - Dumping partition vendor_boot_a with sector count 196608 as dumps/vendor_boot_a.bin.
firehose - 
Reading from physical partition 0, sector 1966080, sectors 196608
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=1966080, num_sectors=196608']
firehose_client - Dumping partition vendor_boot_b with sector count 196608 as dumps/vendor_boot_b.bin.
firehose - 
Reading from physical partition 0, sector 2162688, sectors 196608
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2162688, num_sectors=196608']
firehose_client - Dumping partition ssd with sector count 16 as dumps/ssd.bin.
firehose - 
Reading from physical partition 0, sector 2359296, sectors 16
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2359296, num_sectors=16']
firehose_client - Dumping partition utags with sector count 1024 as dumps/utags.bin.
firehose - 
Reading from physical partition 0, sector 2490368, sectors 1024
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2490368, num_sectors=1024']
firehose_client - Dumping partition utagsBackup with sector count 1024 as dumps/utagsBackup.bin.
firehose - 
Reading from physical partition 0, sector 2491392, sectors 1024
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2491392, num_sectors=1024']
firehose_client - Dumping partition kpan with sector count 16384 as dumps/kpan.bin.
firehose - 
Reading from physical partition 0, sector 2492416, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2492416, num_sectors=16384']
firehose_client - Dumping partition dhob with sector count 64 as dumps/dhob.bin.
firehose - 
Reading from physical partition 0, sector 2508800, sectors 64
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2508800, num_sectors=64']
firehose_client - Dumping partition msadp with sector count 512 as dumps/msadp.bin.
firehose - 
Reading from physical partition 0, sector 2621440, sectors 512
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2621440, num_sectors=512']
firehose_client - Dumping partition persist with sector count 65536 as dumps/persist.bin.
firehose - 
Reading from physical partition 0, sector 2752512, sectors 65536
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2752512, num_sectors=65536']
firehose_client - Dumping partition prodpersist with sector count 16384 as dumps/prodpersist.bin.
firehose - 
Reading from physical partition 0, sector 2818048, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2818048, num_sectors=16384']
firehose_client - Dumping partition metadata with sector count 32768 as dumps/metadata.bin.
firehose - 
Reading from physical partition 0, sector 2834432, sectors 32768
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2834432, num_sectors=32768']
firehose_client - Dumping partition misc with sector count 2048 as dumps/misc.bin.
firehose - 
Reading from physical partition 0, sector 2867200, sectors 2048
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2867200, num_sectors=2048']
firehose_client - Dumping partition frp with sector count 1024 as dumps/frp.bin.
firehose - 
Reading from physical partition 0, sector 2869248, sectors 1024
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2869248, num_sectors=1024']
firehose_client - Dumping partition cid with sector count 256 as dumps/cid.bin.
firehose - 
Reading from physical partition 0, sector 2883584, sectors 256
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2883584, num_sectors=256']
firehose_client - Dumping partition logo_a with sector count 32768 as dumps/logo_a.bin.
firehose - 
Reading from physical partition 0, sector 2883840, sectors 32768
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2883840, num_sectors=32768']
firehose_client - Dumping partition logo_b with sector count 32768 as dumps/logo_b.bin.
firehose - 
Reading from physical partition 0, sector 2916608, sectors 32768
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=2916608, num_sectors=32768']
firehose_client - Dumping partition carrier with sector count 32768 as dumps/carrier.bin.
firehose - 
Reading from physical partition 0, sector 3014656, sectors 32768
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3014656, num_sectors=32768']
firehose_client - Dumping partition devinfo with sector count 8 as dumps/devinfo.bin.
firehose - 
Reading from physical partition 0, sector 3145728, sectors 8
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3145728, num_sectors=8']
firehose_client - Dumping partition apdp with sector count 512 as dumps/apdp.bin.
firehose - 
Reading from physical partition 0, sector 3145736, sectors 512
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3145736, num_sectors=512']
firehose_client - Dumping partition spunvm with sector count 16384 as dumps/spunvm.bin.
firehose - 
Reading from physical partition 0, sector 3276800, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3276800, num_sectors=16384']
firehose_client - Dumping partition logfs with sector count 16384 as dumps/logfs.bin.
firehose - 
Reading from physical partition 0, sector 3407872, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3407872, num_sectors=16384']
firehose_client - Dumping partition vbmeta_a with sector count 128 as dumps/vbmeta_a.bin.
firehose - 
Reading from physical partition 0, sector 3424256, sectors 128
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424256, num_sectors=128']
firehose_client - Dumping partition vbmeta_b with sector count 128 as dumps/vbmeta_b.bin.
firehose - 
Reading from physical partition 0, sector 3424384, sectors 128
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424384, num_sectors=128']
firehose_client - Dumping partition vbmeta_system_a with sector count 128 as dumps/vbmeta_system_a.bin.
firehose - 
Reading from physical partition 0, sector 3424512, sectors 128
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424512, num_sectors=128']
firehose_client - Dumping partition vbmeta_system_b with sector count 128 as dumps/vbmeta_system_b.bin.
firehose - 
Reading from physical partition 0, sector 3424640, sectors 128
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424640, num_sectors=128']
firehose_client - Dumping partition limits with sector count 8 as dumps/limits.bin.
firehose - 
Reading from physical partition 0, sector 3424768, sectors 8
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424768, num_sectors=8']
firehose_client - Dumping partition uefivarstore with sector count 1024 as dumps/uefivarstore.bin.
firehose - 
Reading from physical partition 0, sector 3424776, sectors 1024
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3424776, num_sectors=1024']
firehose_client - Dumping partition modemst1 with sector count 5120 as dumps/modemst1.bin.
firehose - 
Reading from physical partition 0, sector 3538944, sectors 5120
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3538944, num_sectors=5120']
firehose_client - Dumping partition modemst2 with sector count 5120 as dumps/modemst2.bin.
firehose - 
Reading from physical partition 0, sector 3544064, sectors 5120
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3544064, num_sectors=5120']
firehose_client - Dumping partition fsg_a with sector count 131072 as dumps/fsg_a.bin.
firehose - 
Reading from physical partition 0, sector 3549184, sectors 131072
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3549184, num_sectors=131072']
firehose_client - Dumping partition fsg_b with sector count 131072 as dumps/fsg_b.bin.
firehose - 
Reading from physical partition 0, sector 3680256, sectors 131072
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3680256, num_sectors=131072']
firehose_client - Dumping partition fsc with sector count 256 as dumps/fsc.bin.
firehose - 
Reading from physical partition 0, sector 3811328, sectors 256
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3811328, num_sectors=256']
firehose_client - Dumping partition hw with sector count 16384 as dumps/hw.bin.
firehose - 
Reading from physical partition 0, sector 3932160, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=3932160, num_sectors=16384']
firehose_client - Dumping partition sp with sector count 16384 as dumps/sp.bin.
firehose - 
Reading from physical partition 0, sector 4063232, sectors 16384
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=4063232, num_sectors=16384']
firehose_client - Dumping partition padA with sector count 1280 as dumps/padA.bin.
firehose - 
Reading from physical partition 0, sector 4079616, sectors 1280
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=4079616, num_sectors=1280']
firehose_client - Dumping partition super with sector count 20054016 as dumps/super.bin.
firehose - 
Reading from physical partition 0, sector 4080896, sectors 20054016
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=4080896, num_sectors=20054016']
firehose_client - Dumping partition padB with sector count 768 as dumps/padB.bin.
firehose - 
Reading from physical partition 0, sector 24134912, sectors 768
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=24134912, num_sectors=768']
firehose_client - Dumping partition userdata with sector count 98007007 as dumps/userdata.bin.
firehose - 
Reading from physical partition 0, sector 24135680, sectors 98007007
firehose
firehose - [LIB]: ['INFO: handler read allowed', 'INFO: Calling handler for read', 'ERROR: range restricted: lun=0, start_sector=24135680, num_sectors=98007007']

**Comment by RenateUSB** [comment]
Your device is locked.
