### ISSUE TITLE
Please first install libusb_win32 driver from Zadig

### ISSUE THREAD

**Issue by xinextialmatrix** [bkerler/edl#268]
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main
main - [LIB]: Please first install libusb_win32 driver from Zadig
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
DeviceClass - USBError(5, 'Input/Output Error')
Device is in Sahara error state, please reboot the device.
main - Mode detected: error
Connection detected, quiting.

i install lib filter already but still the problem pesist what could be wrong?
im trying to use it on my oppo a5 2020

**Comment by bkerler** [comment]
Since the last bigger update of windows 10/11, libusb isn't working properly anymore, means the hello pkt isn't sent. Please use linux instead or use the serial port option.
