### ISSUE TITLE
xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by scottzhao313** [bkerler/edl#27]
Hi

I can connect to Nokia 8110 4G, but I could not run -printgpt or -w command, it popped up following errors:

scottzhao@scottzhao-ubuntu:~/edl$ python3 edl.py -loader 8110.mbn -printgpt

Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2019.
Using loader 8110.mbn ...
Waiting for the device
..........Device detected :)
Mode detected: Sahara
------------------------
HWID:              0x000940e100420050 (MSM_ID:0x000940e1,OEM_ID:0x0042,MODEL_ID:0x0050)
PK_HASH:           0x1357fdaeabb7becbe49095f000d9d3dadf198885106d98598cac6d1b9b2edb3a
Serial:            0x14d04a0f
SBL Version:       0x00000000

Successfully uploaded programmer :)
TargetName=MSM8909
MemoryName=eMMC
Version=1

Reading from physical partition 0, sector 0, sectors 32

Traceback (most recent call last):
  File "edl.py", line 419, in <module>
    main()
  File "edl.py", line 197, in main
    data = fh.cmd_read_buffer(args.lun, 0, 0x4000 // cfg.SECTOR_SIZE_IN_BYTES)
  File "/home/scottzhao/edl/Library/firehose.py", line 241, in cmd_read_buffer
    rsp=self.xmlsend(data)
  File "/home/scottzhao/edl/Library/firehose.py", line 73, in xmlsend
    resp = self.xml.getresponse(data)
  File "/home/scottzhao/edl/Library/firehose.py", line 16, in getresponse
    tree = ET.fromstring(line, parser=parser)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 5

Firstly I thought my python 3.6.10 is too old, then I switched to python 3.7.8. but errors are same.

Any suggestions?

My PC is Ubuntu 18.04LTS, Python 3.7.8

Thanks

**Comment by bkerler** [comment]
Can you do the same with --debugmode and then send me the log.txt ?

**Comment by bkerler** [comment]
Fixed with commit 036bc63
