### ISSUE TITLE
Oneplus 10 Pro - unpack requires a buffer of 4 bytes in get_serial_num()

### ISSUE THREAD

**Issue by 0xBAADF0OD** [bkerler/edl#274]
Macbook Pro, Intel, OSX 12.2.1
Python 3.8.9
edl 3.6.0 (git pulled 4/14/2022)
Multiple data cables / ports tried

Attempted with OnePlus loader from MSM, as well as no loader, same error.

```
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader 1.elf ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...............
..............
..............
.........main - Device detected :)
sahara - Protocol version: 3.1
main - Mode detected: sahara
Traceback (most recent call last):
  File "/usr/local/bin/edl", line 4, in <module>
    __import__('pkg_resources').run_script('edlclient==3.60', 'edl')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/3.8/site-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 380, in <module>
    base.run()
  File "/Library/Python/3.8/site-packages/edlclient-3.60-py3.8.egg/EGG-INFO/scripts/edl", line 328, in run
    sahara_info = self.sahara.cmd_info()
  File "/Library/Python/3.8/site-packages/edlclient-3.60-py3.8.egg/edlclient/Library/sahara.py", line 210, in cmd_info
    self.serial = self.cmdexec_get_serial_num()
  File "/Library/Python/3.8/site-packages/edlclient-3.60-py3.8.egg/edlclient/Library/sahara.py", line 174, in cmdexec_get_serial_num
    return unpack("<I", res)[0]
struct.error: unpack requires a buffer of 4 bytes

```

Update: The contents of _res_ that's causing the error is ```00000000: AE F5 45 31 32 04 00 00                           ..E12...```

**Comment by Kenora-I** [comment]
Have your tried redownloading the package?

**Comment by 0xBAADF0OD** [comment]
> 

Yes, I also tried in a debian vm, exact same results.

**Comment by 0xBAADF0OD** [comment]
Just another note, I started looking at FTLibQCom.dll, the HELLO response seems to be 0x30.
![image](https://user-images.githubusercontent.com/6748851/163748493-5fff044d-70b3-4573-9099-007a8cfe65f8.png)

And reset_sahara_state_machine now appears to be 0x08
![image](https://user-images.githubusercontent.com/6748851/163748571-52696564-e814-4a01-9154-ecc5d74d5850.png)

Compared to the old 0x02 for HELLO_RSP and 0x07 for RESET_REQ

**Comment by 0xBAADF0OD** [comment]
> @0xBAADF0OD were you able to get the edl tool working with the OnePlus 10 Pro? I see there was a new loader uploaded for the phone 8 days ago, but I'm getting an unpack error as well.

Unfortunately no, the loader existing doesn't change the fact that the protocol implemented in the project is not compatible with the new version, and until that's done it wouldn't work.

**Comment by bkerler** [comment]
Can you please use usbcap to record the communication and upload the pcap ? I'm aware of the new version and I'd like to add support.

**Comment by 0xBAADF0OD** [comment]
Hey @bkerler , sorry but afaik the community didn't get a user-accessible version of the MSM tool, so I wasn't able to run it or record a pcap, at least for the OnePlus 10 series. Maybe there is another phone on Sahara 3.x out there with a leaked unbrick tool.

**Comment by bkerler** [comment]
the serial number issues has been fixed with commit [5584cdc](https://github.com/bkerler/edl/commit/5584cdcd7ba177cc3b9a227000f731282f6e653e)

**Comment by bkerler** [comment]
The protocol 3.1 means that the protocol version is 3 and the min supported version is 1. So normally version 1 should stll work. But oneplus is now owned by oppo and oppo usually uses VIP Programming, which means that every packet has to be signed before execution .

**Comment by P-D-A** [comment]
> The protocol 3.1 means that the protocol version is 3 and the min supported version is 1. So normally version 1 should stll work. But oneplus is now owned by oppo and oppo usually uses VIP Programming, which means that every packet has to be signed before execution .

![1662374448427](https://user-images.githubusercontent.com/20209313/188832569-0de60a98-3cda-4ff6-a528-9f1a8e7aa8af.png)
That's just the way it is
[prog_firehose_ddr.elf from OnePlus 10 Pro](https://mega.nz/folder/zAci1YrZ#-gNY7OJ3IsOo-SY6kV4VXQ/file/KIdXnKbQ)

**Comment by hackslashX** [comment]
Okay, so I did some packet sniffing, and I think I found the sign token. I'm dumping the response from user authorization. I still need someone with a bricked phone to flash his device and capture packets to validate the findings. For now, posting the tokens below if they're helpful.

### Request:
```
POST https://service-sg.myoppo.com/api/tools/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: MsmDownloadTool_v2.0.69_oneplus
Host: service-sg.myoppo.com
Content-Length: 853
Cache-Control: no-cache

app_id=TOOL&timestamp=1663686290&sign=3ba67700dd28f80f54fe341666c8a916&s_msg=VTYOEJTcFl0A7lBugQohN7hraQ69X2qfu4C1K4oCApYLcBMrC5w0HzQuHBAt%2FT7A
DY96zfMdbawA0JRFTNrYR1baZofuzfTX%2BkCmRqhOScNW6faPDPTQrmqlyUSbekLp
%2BcGuNyc4IJfn%2BlfyFIAtlglhda058cssD6bln6DyjBZwZxvBo9hCvTgughsX67IT
yYjXQ87rc%2Fua7mhsNs0bZi5UCx5il7CmF58gPOPOATKC6SV6Cwgl%2FpV1LMXV8E1%2F
P9BwdLFlQZinbdxLL3hsaGVlaOB%2B8n7P939bWcMZaSXZ4zdspxoT65j7t7oFtzte
SYsM7JqqawznCaYVzZGawaq9LHJOlkhi4eBCH632HhqA0DMIjj9Dvq8kRK%2Bg1ElM
2uIqq5Zl%2F9AQDxxlBLO%2B6l5SdyYjLaRgKQenCDfA9j9gJKb8TAlrenyc1vOQWf49
VHQCR4a2lizrvMgg%2BFM1dEPnAZQbRqK6zfY0sTjkQYxtu4%2FG4Ogn84eGX5Ttjb8k
IzjtGoVVyUEw2XeDyLyBfZIoNLB5w9n0mC0ZNrJtDlvsKnB1lwn4D783Q%2Bj%2BtK28
sYJW5g%2BtkWV%2Fzcz%2FBeOsx8zSmVWexlTDkDmCd6bC4LIZrOUqA8p6sZ0ylpWkVUTv
8PeTyYV7Zqsk1Ba3ZYnS3HpXh52d43pe49tNgl5gkUc%3D&s_msg_md_5=ff208e0ddfdb2e762c5f102f7fa8da95
```
### 
Response:
```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 521
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-IIS/8.5
X-AspNet-Version: 4.0.30319
Date: Tue, 20 Sep 2022 15:04:51 GMT

{"Data":{"response":{"message":"0000","token":"db67f796-f52a-4e6a-9009-b5c862a11a0f","status":"0","countryname":"EG","usertype":"7","signData":"Y4/hX/0r6/eeIcIh8l4mZSEp0Q91t5ea3PS91BPc6DoRwY5wkIIVhDIMCE0bvtjf+eF2LvhpHGP6/YUmbxet7wpFXwU4O/816SJe6v/4PDGm5s6ea+uuGaJhuOR2l1cfwexuB8Avajk3LyWoz7K7rL3wsUEqvG5tPk+YR8yP+9Fpm1zJnVhxSBAZoPNVFXYNX1oh2wOPcTdK/DtDo9dKt0QCdbugC2nyT25S+Ax6e+FyqgHCWWIn6zqs29mU3R52wtdMdDk9LSkrpMsMakB/kDvyUOzqX66NrZYL48YOQtqj2q2tSwk6D+uWUw6jZPXgEKXsAAvklySi9KvJJMTyEA=="}},"ErrorCode":0,"Message":null}
```

**Comment by hackslashX** [comment]
> Can you please use usbcap to record the communication and upload the pcap ? I'm aware of the new version and I'd like to add support.

@bkerler if helpful: https://drive.google.com/file/d/1cODW4L-OZUnHTkbKSrMIynQFO4rYu_6P/view?usp=sharing

**Comment by bkerler** [comment]
Yes, indeed very helpful. Thx !
