### ISSUE TITLE
Mode detection fails with Samsung GT-I9195

### ISSUE THREAD

**Issue by plettich** [bkerler/edl#275]
Hi,
i have a bricked Galaxy S4 mini which identifies as an USB device "05c6:9008".
When running `edl` i get:
```
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: error
Connection detected, quiting.
```
In debug mode, after a bunch of errors during initializing the loader db, i get timeouts in the `connect` function:
https://github.com/bkerler/edl/blob/3cf3324209d1c581750556c970597dafbd1e4550/edlclient/Library/sahara.py#L109
For the first `read` here:
https://github.com/bkerler/edl/blob/3cf3324209d1c581750556c970597dafbd1e4550/edlclient/Library/sahara.py#L111
After sending the XML data here:
https://github.com/bkerler/edl/blob/3cf3324209d1c581750556c970597dafbd1e4550/edlclient/Library/sahara.py#L131
And after sending the special bytes i `read` a `0x200` here:
https://github.com/bkerler/edl/blob/3cf3324209d1c581750556c970597dafbd1e4550/edlclient/Library/sahara.py#L143
which fails in the end and returns the error mode.

Is there any further documentation on how to talk to the device? Or is it already beyond fixing?
Thanks

**Comment by bkerler** [comment]
you need a samsung signed loader, that's why it's failing.
