### ISSUE TITLE
boot ISO from grub

### ISSUE THREAD

**Issue by aIecxs** [bkerler/edl#277]
I have copy of re_livedvdV3.iso on fat32 hard disk. I can boot the ISO from grub2 but all I get is Ubuntu welcome screen, there is no user "user" and after setting up "user" there is no edl installed.

This is how I boot the ISO. What did I wrong?

`/boot/grub2/grub.cfg`

```
menuentry "Re Live DVD V3" {
     savedefault
     set isofile="re_livedvdV3.iso"
     loopback loop (hd0,3)/$isofile
     linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=/${isofile}
     initrd (loop)/casper/initrd.gz
}
```

furthermore the screen resolution is too high so I couldn't see anything on my old monitor. I recommend 1024x768 as default for a "ready to use" DVD

**Comment by bkerler** [comment]
sorry, I can't assist with any issues. the LiveDVD v4 actually has 1024x768 as screen setting. LiveDVD v3 isn't recommended anymore.
