### ISSUE TITLE
Error: Couldn't write partition

### ISSUE THREAD

**Issue by ReFil** [bkerler/edl#278]
I'm trying to unbrick a 3t but irrelevant of the decrypted firmware i try to flash or the partitions i try to flash at some point it alwys errors out with 
Couldn't write partition. Either wrong memorytype given or no gpt partition.

**Comment by skyblaster** [comment]
If it helps to troubleshoot this issue, here is my lun0 partition table.
[rawprogram0.txt](https://github.com/bkerler/edl/files/8578174/rawprogram0.txt)

**Comment by skyblaster** [comment]
I ended up using QFIL to restore my phone.

@ReFil, if you're still having trouble, I noticed that with QFIL, I had to reboot the phone (Vol+, Vol-, and Power simultaneously), and then initiate the "Download" immediately after Windows detected the 9008 device.

Perhaps there is a short window after boot that is affecting edl and QFIL equally here.

**Comment by dzid26** [comment]
There is a bug that this message will display whether flashing was successful or not. 


When `edl wl` option is used, it needs to point to each lun folder that was obtained with `edl rl`.
For example:
```
#!/bin/bash 
DUMP_FOLDER="../dump/"

./edl wl "$DUMP_FOLDER/lun1" --lun=1 --memory=ufs
./edl wl "$DUMP_FOLDER/lun2" --lun=2 --memory=ufs
./edl wl "$DUMP_FOLDER/lun3" --lun=3 --memory=ufs
./edl wl "$DUMP_FOLDER/lun4" --lun=4 --memory=ufs
./edl wl "$DUMP_FOLDER/lun5" --lun=5 --memory=ufs
./edl wl "$DUMP_FOLDER/lun0" --lun=0 --memory=ufs # main partition 120GB last - takes >3h
```

**Comment by drmouss** [comment]
can someboby help me find this /sd765/0000000000720000_1bebe3863a6781db_fhprg.bin need this file

**Comment by imyxh** [comment]
> There is a bug that this message will display whether flashing was successful or not.
> 
> When `edl wl` option is used, it needs to point to each lun folder that was obtained with `edl rl`. For example:

Found it: https://github.com/bkerler/edl/blob/cef0076e1d4d29c1887c51786eb588503657b907/edlclient/Library/firehose_client.py#L766-L789

Indentation issue. Opening PR in a sec.
