### ISSUE TITLE
"sahara [LIB]" Error No Matter What I Do

### ISSUE THREAD

**Issue by GitHubQueenn** [bkerler/edl#284]
Any idea why the prog_emmc_firehose_8917_ddr.mbn that works for the MSM8937 UMX U693CL phone would not work for the newer U696CL model that uses the same 8937? The 8917 Firehose 100% works for the 693CL. Been at this for days, was able to unlock bootloader on the 696CL and fastboot is fully intact (but it says Secure:on), but whether I use Linux EDL or Windows QFIL, I always get the "sahara [LIB]" error that's above.

For more info: https://forum.xda-developers.com/t/android-wont-show-up-as-usb-device-on-virtualbox-after-putting-phone-in-adb-edl-mode.4445079/post-86891179

**Comment by bkerler** [comment]
most probably the reason is : it's signed differently. Just compare the loader hash with the pk hash. if they don't match, it's likely it won't work (except the device is unfused, but very unlikely)
