### ISSUE TITLE
No supported functions detected, configuring qc generic commands

### ISSUE THREAD

**Issue by Sucharek233** [bkerler/edl#286]
Hi, I have an issue with all the commands. Just to say, this might be an issue with the phone.
It's a Xiaomi Redmi 3 (codename ido). Whenever I try to run any command, it just says `No supported functions detected, configuring qc generic commands`.
If I don't specify the memory type, it prints: `firehose_client - [LIB]: No --memory option set, we assume "UFS" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !`.

Here's the log: [log.txt](https://github.com/bkerler/edl/files/8743550/log.txt).

Edit: I should add I'm on Arch Linux (Manjaro).

**Comment by bkerler** [comment]
just use --memory=emmc and it should work fine.
