### ISSUE TITLE
So my device wasn't turning on and i thought its in edl mode so....

### ISSUE THREAD

**Issue by maximumchar** [bkerler/edl#287]
so I used the command `edl.py printgpt` and it said the following

```
Qualcomm Sahara / Firehose Client V3.1 (c) B.Kerler 2018-2021.
Library.utils - Trying with no loader given ...
Library.utils - Waiting for the device
.Library.utils - Device detected :)
Library.utils - Mode detected: sahara
Device is in streaming mode, uploading loader
Library.sahara - Device serial : 0xefec43ac
Error, couldn't find suitable enprg/nprg loader :(
```

so my device is apparently in streaming mode and I can't find a way to exit from it. If any one knows how to exit from streaming mode please help me.
Thank you

Device : Lenovo TB-X304L

**Comment by HighlanderUkUk** [comment]
What device might help out just a little bit.

**Comment by HighlanderUkUk** [comment]
Sorry just saw device at end of post my bad too many glasses of water

**Comment by bkerler** [comment]
Your device is most probable in 0x900E mode, which means your flash is broken.

**Comment by maximumchar** [comment]
> Your device is most probable in 0x900E mode, which means your flash is broken.

hey thanks for the reply. Any way to get my device out of that mode and reflash my device to normal?
