### ISSUE TITLE
Unknown CPU

### ISSUE THREAD

**Issue by grogcw** [bkerler/edl#289]
Hi !

I'm trying out your edl project in order to try oem unlocking the bootloader of my "special snowflake" device which is a Pioneer XDP-300R (same device as Onkyo DP-X1, both android-based DAC Audiophile players), and your program had an issue finding the CPU model.

It's a Qualcomm Snapdragon 800 [MSM8974], probably vendorised by Pioneer-Onkyo.

Here's the log of the program :

```
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...............
.main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara -
------------------------
HWID:              0x007bb0e100000000 (MSM_ID:0x007bb0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0xac4a468e740b3e5858b68d6eb018c10f8f45dd557c6430a9e7aaace3b5f9f5e4
Serial:            0x11daa8f6

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (007bb0e100000000_ac4a468e740b3e58_[FHPRG/ENPRG].bin) :(
```

I **really** don't know if that's possible to find pioneer's "prog_emmc_firehose_8974.mbn" as no roms are published.

We do have 3 OTA roms for the Onkyo one tho.
See my [XDA-Post](https://forum.xda-developers.com/t/any-help-on-pioneer-xdp-300r-bootloop.3896798/page-2) here :)

In any case, if that's helpful or relevant, I have a fully functional unit, rooted as well as rom backups.

I just was testing in case of bricking, we never know...

Thanks for taking care,

Cheers !

**Comment by bkerler** [comment]
Thanks :) If you find an edl loader, let me know.
