### ISSUE TITLE
LG LMX210EMW - Error uploading firehose error (HELLO_RESP)

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#291]
Do have any idea of what might be causing this error?

------------------------
HWID:              0x009600e100311200 (MSM_ID:0x009600e1,OEM_ID:0x0031,MODEL_ID:0x1200)
CPU detected:      "MSM8909"
PK_HASH:           0xb5baca995aec012db32eb9e49ca340f7d4c26153aaa60c5a82a03f99afc698e3
Serial:            0x1a360eee

Found possible loader: /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/../Loaders/LG/009690e100310000_b5baca995aec012d_fhprg_peek.bin
Found possible loader: /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/../Loaders/LG/009400e100310000_b5baca995aec012d_fhprg.bin
Protocol version: 2.1
Uploading loader /usr/local/lib/python3.8/dist-packages/edlclient-3.60-py3.8.egg/edlclient/../Loaders/LG/009400e100310000_b5baca995aec012d_fhprg.bin ...
32-Bit mode detected.
Firehose mode detected, uploading...
Error: Unknown host error received in HELLO_RESP
[log.txt](https://github.com/bkerler/edl/files/8864548/log.txt)

**Comment by bkerler** [comment]
That means that you need to start edl first, then connect, otherwise the hello package cannot be received.

**Comment by leosol** [comment]
I managed to enter EDL again shorting CMD with 1.8v (see picture)
Without battery, to hold EDL mode, I had to keep shorting those pins. Right after unshorting them, EDL went off.
So, I decided to insert the battery, short CMD with 1.8v and press power. After that, I pressed the power button.
A few seconds later, the phone was conected to the usb cable / PC.
We were able to see that EDL mode was on, even after releasing the short.
For the first time, i thought I could read/dump data, but as you can see in the logs, after the rf command, I`ve got some timeouts and the fone no longer enters edl mode anyway. Seems to be dead. Any advice? Anything that I could have done to save the phone? It was almost dead already, not turning on... boot looping... etc... There is still the chance of chip off it`s memory... ideas?

Thanks anyway!
[log-lgk9-19-07-2022.txt](https://github.com/bkerler/edl/files/9144407/log-lgk9-19-07-2022.txt)

![JTAG-LG](https://user-images.githubusercontent.com/4167122/179839773-78faec6f-01e5-4aae-915a-fce9c56660ab.png)
