### ISSUE TITLE
Edit == > edl e misc  to edl e misc,config,frp (multy comand erase)

### ISSUE THREAD

**Issue by hensycell** [bkerler/edl#292]
# firehose_client.py  with line {794}
elif cmd == "e":
            if not self.check_param(["<partitionname>"]):
                return False
            luns = self.getluns(options)
            partitionname = options["<partitionname>"]
            partitions = partitionname.split(",")
            i = 0
            for partitiona in partitions:
                for lun in luns:
                    data, guid_gpt = self.firehose.get_gpt(lun, int(options["--gpt-num-part-entries"]),
                                                       int(options["--gpt-part-entry-size"]),
                                                       int(options["--gpt-part-entry-start-lba"]))
                    if guid_gpt is None:
                        break
                    if self.firehose.modules is not None:
                       self.firehose.modules.writeprepare()

                    if partitiona in guid_gpt.partentries:
                        partition = guid_gpt.partentries[partitiona]
                        self.printer(
                           f"Erased {partitiona} starting at sector {str(partition.sector)} " +
                           f"with sector count {str(partition.sectors)}.")
                        self.firehose.cmd_erase(lun, partition.sector, partition.sectors)
                    else:
                        self.printer(
                           f"Couldn't erase partition {partitiona}. Either wrong memorytype given or no gpt partition.")
                        return False
                continue        
                self.error(f"Error: Couldn't detect partition: {partitiona}")
                return False
            return True

**Comment by bkerler** [comment]
Added with commit [ad93c98](https://github.com/bkerler/edl/commit/ad93c9840426559ccc76e7613c7ae0b0450b205f)
