### ISSUE TITLE
Edit single command to multy command write file  ( edl w misc,frp,confiq misc.bin,frp.bin,confiq.bin )

### ISSUE THREAD

**Issue by hensycell** [bkerler/edl#293]
# support  windows 7 10 11
# firehose_client.py line(649)

elif cmd == "w":
            if not self.check_param(["<partitionname>", "<filename>"]):
                return False
            partitionname = options["<partitionname>"]
            filename = options["<filename>"]
            filenames = filename.split(",")
            partitionsa = partitionname.split(",")
            if len(partitionsa) != len(filenames):
                self.error("You need to gives as many filenames as given partitionsa.")
                return False
            i = 0
            for partitiona in partitionsa:
                if options["--lun"] is not None:
                    lun = int(options["--lun"])
                else:
                    lun = 0
                startsector = 0
                partfilename = filenames[i]
                i += 1    
                if not os.path.exists(partfilename):
                    self.error(f"Error: Couldn't find file: {partfilename}")
                    return False
                if partitiona.lower() == "gpt":
                    sectors = os.stat(partfilename).st_size // self.firehose.cfg.SECTOR_SIZE_IN_BYTES
                    res = [True, lun, sectors]
                else:
                    res = self.firehose.detect_partition(options, partitiona)
                if res[0]:
                    lun = res[1]
                    sectors = os.stat(partfilename).st_size // self.firehose.cfg.SECTOR_SIZE_IN_BYTES
                    if (os.stat(partfilename).st_size % self.firehose.cfg.SECTOR_SIZE_IN_BYTES) > 0:
                        sectors += 1
                    if partitiona.lower() != "gpt":
                        partition = res[2]
                        if sectors > partition.sectors:
                            self.error(
                            f"Error: {partitiona} has {sectors} sectors but partition only has {partition.sectors}.")
                            return False
                        startsector = partition.sector
                    if self.firehose.modules is not None:
                       self.firehose.modules.writeprepare()
                    self.printer(f"Wrote {partitiona} to sector {str(startsector)}.")
                    if self.firehose.cmd_program(lun, startsector, partfilename):
                       self.printer(f" writing to {partfilename} to sector {str(startsector)}.")
                    else:
                       self.printer(f"Error writing {partitiona} to sector {str(startsector)}.")
                       return False
                else:
                    if len(res) > 0:
                       fpartitions = res[1]
                       self.error(f"Error: Couldn't detect partition: {partitiona}\nAvailable partitions:")
                       for lun in fpartitions:
                            for partition in fpartitions[lun]:
                                if self.cfg.MemoryName == "emmc":
                                    self.error("\t" + partition)
                                else:
                                   self.error(lun + ":\t" + partition)
                                   return False 
            return True

**Comment by bkerler** [comment]
Added in commit 4f84e1ef2b585f2e5b3941ab2bfa23be5fe4d772, next time please write a pr, don't post code in an issue, thanks !
