### ISSUE TITLE
error line 314

### ISSUE THREAD

**Issue by MdSadam** [bkerler/edl#297]
python edl
  File "D:\Software\Tool\vivo_fastboot_windows_v2\edl\edl", line 314
    if len(sahara_connnect) == 3:
IndentationError: unexpected indent

**Comment by deyvs02** [comment]
C:\python edl printgpt
  File "C:\edl", line 314
    if len(sahara_connnect) == 3:
IndentationError: unexpected indent

**Comment by bkerler** [comment]
sorry, but this is unrelated to my code as it seems as the indent is correctly on this git repo.
