### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by ndl54** [bkerler/edl#3]
"Put your loaders into the Loader directory for autodetection. See PutYourLoadersInHere.txt on how to store the loaders correctly to make the autodetection work :)"
"009900E100000000_3be970a8579cac80_FHPRG.bin"
How can i get this "loader" file? Can't find anything about this file on the internet  :(

**Comment by bkerler** [comment]
Hi, just grab any fitting edl loader and rename it to match msmid_pkhash. Sorry I cannot provide propietary loaders but they are very easy to find. just google for 9008 or qfil.

Am 25. Februar 2019 11:07:39 MEZ schrieb ndl54 <notifications@github.com>:
>"Put your loaders into the Loader directory for autodetection. See
>PutYourLoadersInHere.txt on how to store the loaders correctly to make
>the autodetection work :)"
>"009900E100000000_3be970a8579cac80_FHPRG.bin"
>How can i get this "loader" file? Can't find anything about this file
>on the internet  :(
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bkerler/edl/issues/3

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ndl54** [comment]
I get it, thanks :D

**Comment by jmerkin** [comment]
I didn't want to start a new thread for this. I don't quite understand. Where should I find the HWID and the PKHASH? Is the hash just the sha256 of the file? Where should I find the loader? I have a stock firmware zip, if that would have it. There's a file called ".....FHLOSDER....xtt". Would that be it?

**Comment by bkerler** [comment]
That is device specific, and if you run the edl.py without options, it will display those hw fields if the device is in edl mode.

Actually you only need the FHLoader or firehose_prog_emmc or whatever and use the loader option. I already created tools to automatically rename the loaders, they will be published very soon with the release of the new edl version.

**Comment by idnetwork-s** [comment]
hi, how put loader into autoloaders?
