### ISSUE TITLE
DeviceClass - USBError 19

### ISSUE THREAD

**Issue by EUA** [bkerler/edl#302]
My Xiaomi Mi 10 Lite 5G device (monet) just entered EDL mode while trying to play Diablo Immortal...

Using ArchLinux, tried to edl reset command and it continuously disconnects.
Here is the full debug log:

[edl.txt](https://github.com/bkerler/edl/files/8986641/edl.txt)

**Comment by bkerler** [comment]
edl reset is just a reboot, nothing more. Most probably your device is in 900E mode, which means your flash might be broken.
