### ISSUE TITLE
Hisense A9 / Snapdragon 662: Couldn't find a loader for given hwid and pkhash

### ISSUE THREAD

**Issue by RunnyYolk** [bkerler/edl#303]
Trying to extract `boot.img` from a Hisense A9, I get the error `sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (0014d0e100430000_56d3f3c74a52172b_[FHPRG/ENPRG].bin) :(`. I've also tried it with loaders which I think are for other 662 devices, `0014d0e100000000_d40eee56f3194665_FHPRG.bin` and `Qualcomm_662_loader.elf` and one just called `Loader.bin`, but each time I get an error `sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ? type object 'req' has no attribute 'image_id'`

I'm totally clueless about how these loaders come to exist - are they from the manufacturer, or do you reverse engineer them?

Here are the logs I captured from trying different loaders (or no loader at all):

https://pastebin.com/AA9d5Tdh
https://pastebin.com/gXHS9pYN
https://pastebin.com/6e5FeWDc
https://pastebin.com/8dGWFNau
https://pastebin.com/iTd8ZsVH
https://pastebin.com/2esPvxyX
https://pastebin.com/Pvz9YxfE
https://pastebin.com/D47mPKt6

**Comment by RunnyYolk** [comment]
This is what I get from `printgpt` (not sure if it's new info though)

```
python3 edl printgpt
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x0014d0e100430000 (MSM_ID:0x0014d0e1,OEM_ID:0x0043,MODEL_ID:0x0000)
CPU detected:      "SDM662"
PK_HASH:           0x56d3f3c74a52172b18ca2297db00f3feebd23cdfc77decfb34268abca09d9075f89b18f87610ef3fe67f948d4bdf4501
Serial:            0xc0a7b7b9
 
sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (0014d0e100430000_56d3f3c74a52172b_[FHPRG/ENPRG].bin) :(
```

**Comment by RenateUSB** [comment]
Neither "Bengal" or "SDM662" are very specific.
You've got a 0014D0E1 Snapdragon 662 (SM_KAMORTA_H)
The nearest loader is the Qualcomm factory 662, but yours is Hisense so that won't work.
And nobody that I know has even got that to work on 0014d0e100000000 devices.

**Comment by RunnyYolk** [comment]
Thanks for the info. It sounds like it's a dead end until a loader is available - do we have to wait for a loader to come from the Hisense / Qualcomm, or is it possible to reverse-engineer loaders? I'm clueless about where they come from!
