### ISSUE TITLE
Tool just hangs on main

### ISSUE THREAD

**Issue by TheSpecialist666** [bkerler/edl#305]
- FIxed it

**Comment by TheSpecialist666** [comment]
![WTF](https://user-images.githubusercontent.com/90583379/177208620-745b7537-3a1e-41e1-baa8-a80ed7711f52.png)
Sometimes it even throws this error at me. I've tried emmcdl, this tool, etc that should just "work", but clearly don't. I'm starting to believe that these tools are just garbage and don't work on linux.

**Comment by amanf244** [comment]
How you fixed it?
