### ISSUE TITLE
[Feature Request] Implement qfil to use multiple rawprogram and patch files

### ISSUE THREAD

**Issue by Luciogi** [bkerler/edl#311]
Hi! Thanks for this project.

I want to flash miui fastboot rom in PocoM3 using edl qfil emulation, rom contains 6 rawprogram files and 6 patch files. When I put all in one command it does not run , it display command usage.

`edl qfil rawprogram0.xml rawprogram1.xml rawprogram2.xml rawprogram3.xml rawprogram4.xml rawprogram5.xml patch0.xml patch1.xml patch2.xml patch3.xml patch4.xml patch5.xml .`
Edit: If I am doing wrong, correct me.

**Comment by TipzRickyCheung** [comment]
This feature actually already exists, just replace the spaces between the same kinds of file to a comma. Close please.
