### ISSUE TITLE
realme q3s no set active partitions

### ISSUE THREAD

**Issue by allex2** [bkerler/edl#317]
After installing the firmware, there are no active partitions
edl --loader=Loaders/realme/prog_firehose_ddr_fwupdate.elf printgpt --memory=ufs
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader Loaders/realme/prog_firehose_ddr_fwupdate.elf ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
main - Trying to connect to firehose loader ...
firehose - INFO: Binary build date: Aug 12 2021 @ 09:50:43 
firehose - INFO: Chip serial num: 1152761642 (0x44b5bf2a)
firehose - INFO: Supported Functions (15):
firehose - INFO: program
firehose - INFO: read
firehose - INFO: nop
firehose - INFO: patch
firehose - INFO: configure
firehose - INFO: setbootablestoragedrive
firehose - INFO: erase
firehose - INFO: power
firehose - INFO: firmwarewrite
firehose - INFO: getstorageinfo
firehose - INFO: benchmark
firehose - INFO: emmc
firehose - INFO: ufs
firehose - INFO: fixgpt
firehose - INFO: getsha256digest
firehose - INFO: End of supported functions 15
firehose
firehose - [LIB]: Couldn't detect MaxPayloadSizeFromTargetinBytes
firehose
firehose - [LIB]: Couldn't detect TargetName
firehose - TargetName=Unknown
firehose - MemoryName=UFS
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose - Storage report:
firehose - total_blocks:30402560
firehose - block_size:4096
firehose - page_size:4096
firehose - num_physical:6
firehose - manufacturer_id:429
firehose - serial_num:2037279096
firehose - fw_version:043
firehose - mem_type:UFS
firehose - prod_name:H9HQ15AFAMBDAR
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest
firehose
firehose - [LIB]: INFO: Calling handler for read
firehose
firehose - [LIB]: ERROR: Failed to open the UFS Device slot 0 partition 6
firehose
firehose - [LIB]: ERROR: Failed to open the device:3 slot:0 partition:6 error:0
firehose
firehose - [LIB]: ERROR: OPEN handle NULL and no error, weird 344608228
firehose
firehose - [LIB]: ERROR: Failed to open device, type:UFS, slot:0, lun:6 error:3

Parsing Lun 0:

GPT Table:
-------------
ssd:                 Offset 0x0000000000006000, Length 0x0000000000002000, Flags 0x0000000000000000, UUID 31c71020-28eb-1850-daef-fe00b754a8c7, Type 0x2c86e742, Active False
persist:             Offset 0x0000000000008000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID 32120b1a-c0a2-8577-574c-e9e9e2640cc0, Type 0x6c95e238, Active False
misc:                Offset 0x0000000002008000, Length 0x0000000000100000, Flags 0x0000000000000000, UUID 0fdec8a7-b980-c426-9e41-670b4fcf9d22, Type 0x82acc91f, Active False
keystore:            Offset 0x0000000002108000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 2cb9df49-2f56-ffc9-fddf-4271237ec125, Type 0xde7d4029, Active False
frp:                 Offset 0x0000000002188000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 77a2bc44-1ef3-6132-e4ef-e6af74feaf7d, Type 0x91b72d4d, Active False
vbmeta_system_a:     Offset 0x0000000002208000, Length 0x0000000000010000, Flags 0x1000000000000000, UUID eb7011f6-9d2b-2acb-b503-95f2e0dbddca, Type 0x1344859d, Active False
vbmeta_system_b:     Offset 0x0000000002218000, Length 0x0000000000010000, Flags 0x1000000000000000, UUID d081b5a3-5ff7-ef8f-5e66-1a292486e57a, Type 0xfe3ab853, Active False
vbmeta_vendor_a:     Offset 0x0000000002228000, Length 0x0000000000010000, Flags 0x0000000000000000, UUID 1b80f7ab-989e-3c5d-1f4d-73f99c53bdf1, Type 0x5a33b410, Active False
vbmeta_vendor_b:     Offset 0x0000000002238000, Length 0x0000000000010000, Flags 0x0000000000000000, UUID 0b12eb27-5209-f836-b7fc-9ee197d80da3, Type 0xfe3ab853, Active False
metadata:            Offset 0x0000000002248000, Length 0x0000000001000000, Flags 0x0000000000000000, UUID 8a6213b3-82d6-caf0-6c84-2f3255641286, Type 0x988a98c9, Active False
rawdump:             Offset 0x0000000003248000, Length 0x0000000008000000, Flags 0x0000000000000000, UUID 18fa7986-de16-c932-25af-a81b03c14aae, Type 0x66c9b323, Active False
super:               Offset 0x000000000b248000, Length 0x0000000260000000, Flags 0x0000000000000000, UUID ce06bd86-b55b-9982-965c-71afa76e3d34, Type 0x89a12de1, Active False
userdata:            Offset 0x000000026b248000, Length 0x0000001a935b3000, Flags 0x0000000000000000, UUID b0f2c097-fd29-06e5-b01e-2bf4c85720af, Type 0x1b81e7e6, Active False

Total disk size:0x0000001cfe81c000, sectors:0x0000000001cfe81c

Parsing Lun 1:

GPT Table:
-------------
xbl_a:               Offset 0x0000000000006000, Length 0x0000000000600000, Flags 0x1000000000000000, UUID 3619950c-df8a-39b2-6463-2a9e432040ec, Type 0xdea0ba2c, Active False
xbl_config_a:        Offset 0x0000000000606000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 3fd6dbf4-5f66-f8b8-70cf-18b39647cefa, Type 0x5a325ae4, Active False

Total disk size:0x000000000081c000, sectors:0x000000000000081c

Parsing Lun 2:

GPT Table:
-------------
xbl_b:               Offset 0x0000000000006000, Length 0x0000000000600000, Flags 0x1000000000000000, UUID c196eb6d-1999-47be-ceaa-1d2ec4895bbd, Type 0xdea0ba2c, Active False
xbl_config_b:        Offset 0x0000000000606000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 32b3ea87-8f40-72ed-d55d-61b190e7ff90, Type 0x5a325ae4, Active False

Total disk size:0x000000000081c000, sectors:0x000000000000081c

Parsing Lun 3:

GPT Table:
-------------
ALIGN_TO_128K_1:     Offset 0x0000000000006000, Length 0x000000000001a000, Flags 0x1000000000000000, UUID 1886efe8-52d9-022c-c9fe-f4cb963ef988, Type 0xfde1604b, Active False
cdt:                 Offset 0x0000000000020000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 99592f4f-e2f2-22df-d313-ab502ab991ac, Type 0xa19f205f, Active False
ddr:                 Offset 0x0000000000040000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID c7cb3473-c149-495d-01fa-4809dc50cc25, Type 0x20a0c19c, Active False
engineering_cdt_a:   Offset 0x0000000000140000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID e71ce2c9-95a4-0c38-bea6-2d6fd62ceb0c, Type 0x21a0c19c, Active False
ocdt:                Offset 0x0000000000240000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID 113a7cf6-c50a-1972-b2d3-ffa8e3c76904, Type 0x517c596d, Active False
dinfo:               Offset 0x0000000000260000, Length 0x0000000000004000, Flags 0x0000000000000000, UUID 43dc582c-cc73-4457-6475-6c86dde5fcd4, Type 0xe02d0037, Active False
engineering_cdt_b:   Offset 0x0000000000264000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID ef4ed220-c5f3-590a-da03-72a26e64df88, Type 0xb4184eda, Active False

Total disk size:0x000000000201c000, sectors:0x000000000000201c

Parsing Lun 4:

GPT Table:
-------------
aop_a:               Offset 0x0000000000006000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 856e696c-9e67-2f75-17e2-3df712c74973, Type 0xd69e90a5, Active False
tz_a:                Offset 0x0000000000086000, Length 0x0000000000400000, Flags 0x1000000000000000, UUID 59076a8e-0e9d-9d09-3355-9a876d6f0f5b, Type 0xa053aa7f, Active False
hyp_a:               Offset 0x0000000000486000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 9a23fac0-5238-f51b-d0f2-53e3f7f4c6a4, Type 0xe1a6a689, Active False
modem_a:             Offset 0x0000000000c86000, Length 0x000000000dc00000, Flags 0x1000000000000000, UUID 2659ed9b-41a2-0b2d-cafe-d746f1ea1710, Type EFI_BASIC_DATA, Active False
bluetooth_a:         Offset 0x000000000e886000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 4226167c-4e74-9c96-fdbd-9dcde5fd6749, Type 0x6cb747f1, Active False
mdtpsecapp_a:        Offset 0x000000000ea86000, Length 0x0000000000400000, Flags 0x1000000000000000, UUID d311386e-aa21-29b5-5fa4-a89c9acd8e38, Type 0xea02d680, Active False
mdtp_a:              Offset 0x000000000ee86000, Length 0x0000000002000000, Flags 0x1000000000000000, UUID 2268801a-c1ea-c404-8909-35514d23134a, Type 0x3878408a, Active False
abl_a:               Offset 0x0000000010e86000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID a7f51a78-3546-720c-a889-9966f7991a1a, Type 0xbd6928a1, Active False
dsp_a:               Offset 0x0000000010f86000, Length 0x0000000004000000, Flags 0x1000000000000000, UUID 4dc47e69-79f7-3c88-1d72-aa1403d2cff5, Type 0x7efe5010, Active False
keymaster_a:         Offset 0x0000000014f86000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID b7a02c09-9d75-e891-2d32-a253c71da98c, Type 0xa11d2a7c, Active False
boot_a:              Offset 0x0000000015006000, Length 0x000000000c000000, Flags 0x0000000000000000, UUID d59dab18-f56a-20fa-5a0e-d99a9d21eade, Type 0x20117f86, Active False
devcfg_a:            Offset 0x0000000021006000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID 77d709cf-de2f-7178-843b-e07b01c93424, Type 0xf65d4b16, Active False
qupfw_a:             Offset 0x0000000021026000, Length 0x0000000000014000, Flags 0x0000000000000000, UUID 2ee7b5e2-7b4a-b2a6-e367-1313003d4d28, Type 0x21d1219f, Active False
vbmeta_a:            Offset 0x000000002103a000, Length 0x0000000000010000, Flags 0x1000000000000000, UUID 30082574-82fa-7e04-26e9-b7672b66aeed, Type 0x4b7a15d6, Active False
dtbo_a:              Offset 0x000000002104a000, Length 0x0000000001800000, Flags 0x0000000000000000, UUID c2cc2b3b-ea74-a3a2-4cd6-dd4aaf375edd, Type 0x24d0d418, Active False
uefisecapp_a:        Offset 0x000000002284a000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 4da3bf0b-50dc-d8c6-e7b8-f678b8fc3417, Type 0xbe8a7e08, Active False
imagefv_a:           Offset 0x0000000022a4a000, Length 0x0000000000200000, Flags 0x0000000000000001, UUID 3efc06d7-f3f2-6f52-c95b-4ddfb95a1570, Type 0x17911177, Active False
shrm_a:              Offset 0x0000000022c4a000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 7cdee473-fd43-94aa-158b-99df25b0f6a4, Type 0xcb74ca22, Active False
vm-bootsys_a:        Offset 0x0000000022c6a000, Length 0x0000000010625000, Flags 0x0000000000000000, UUID 5d464987-1d15-e836-84a5-a04631d7d09a, Type 0x7b034c58, Active False
multiimgoem_a:       Offset 0x000000003328f000, Length 0x0000000000008000, Flags 0x1000000000000000, UUID a8f91806-80f0-38f3-9ad5-6621b5b83fe5, Type 0xe126a436, Active False
cpucp_a:             Offset 0x0000000033297000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID db2dca70-20e0-2b94-a814-6f60533bfcd4, Type 0x1e8615bd, Active False
featenabler_a:       Offset 0x0000000033397000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID 729112a0-aa57-ea64-82e6-41cc29b83e0b, Type 0x741813d2, Active False
vendor_boot_a:       Offset 0x00000000333b7000, Length 0x000000000c000000, Flags 0x0000000000000000, UUID b5edaf0f-6cad-9fa4-6ec9-cfc73f6c3475, Type 0x6d286a7f, Active False
qmcs:                Offset 0x000000003f3b7000, Length 0x0000000001e00000, Flags 0x0000000000000000, UUID 26585249-5979-7c31-72d4-08742e3635d7, Type 0x358740b1, Active False
qweslicstore_a:      Offset 0x00000000411b7000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID f846c803-dd19-73b4-c8e4-33b8bae2b8de, Type 0x7bab3c93, Active False
splash_a:            Offset 0x00000000411f7000, Length 0x00000000020a4000, Flags 0x0000000000000000, UUID 6a777cca-03e0-9801-8671-d1dbfedc5626, Type 0xad99f201, Active False
oplus_sec_a:         Offset 0x000000004329b000, Length 0x0000000000a00000, Flags 0x0000000000000000, UUID 4ab96dde-9d06-b666-e3ec-eae67f19994b, Type 0xe11dda6a, Active False
aop_b:               Offset 0x0000000043c9b000, Length 0x0000000000080000, Flags 0x0000000000000000, UUID 341f8861-57c6-ea39-29c4-5c8e26b0b985, Type 0x77036cd4, Active False
tz_b:                Offset 0x0000000043d1b000, Length 0x0000000000400000, Flags 0x0000000000000000, UUID 45c8af1d-5f8d-1562-b4cb-bd4977bdbdcf, Type 0x77036cd4, Active False
hyp_b:               Offset 0x000000004411b000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 33d03311-052d-63a4-dcab-8046381f551d, Type 0x77036cd4, Active False
modem_b:             Offset 0x000000004491b000, Length 0x000000000dc00000, Flags 0x1000000000000000, UUID 1898d3d5-b5a4-70d4-e180-ad2d749cae27, Type 0x77036cd4, Active False
bluetooth_b:         Offset 0x000000005251b000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID 2c3cff7f-eeba-a48e-1bdb-1c73165fd6e3, Type 0x77036cd4, Active False
mdtpsecapp_b:        Offset 0x000000005271b000, Length 0x0000000000400000, Flags 0x1000000000000000, UUID 5ca439a8-3351-76a9-07cf-a72e212c52b3, Type 0x77036cd4, Active False
mdtp_b:              Offset 0x0000000052b1b000, Length 0x0000000002000000, Flags 0x1000000000000000, UUID a3aa9067-ec6a-5bfd-0c8e-eedc568496f0, Type 0x77036cd4, Active False
abl_b:               Offset 0x0000000054b1b000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID 833ee902-d38a-184d-ad58-b63141a03f96, Type 0x77036cd4, Active False
dsp_b:               Offset 0x0000000054c1b000, Length 0x0000000004000000, Flags 0x1000000000000000, UUID 1f399828-f52d-40dd-de73-60a8188b6fcb, Type 0x77036cd4, Active False
keymaster_b:         Offset 0x0000000058c1b000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 8b92365c-24ab-d8f7-a77c-389b17e26fc6, Type 0x77036cd4, Active False
devcfg_b:            Offset 0x0000000058c9b000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID f889a238-d80a-0a63-e576-7508c763e3e2, Type 0x77036cd4, Active False
qupfw_b:             Offset 0x0000000058cbb000, Length 0x0000000000014000, Flags 0x0000000000000000, UUID d45c8e89-b715-6b63-0329-97936bb791f6, Type 0x77036cd4, Active False
vbmeta_b:            Offset 0x0000000058ccf000, Length 0x0000000000010000, Flags 0x1000000000000000, UUID 73aafe7f-2a19-f508-e20e-4875f2c4448f, Type 0x77036cd4, Active False
dtbo_b:              Offset 0x0000000058cdf000, Length 0x0000000001800000, Flags 0x0000000000000000, UUID abe5db98-95d9-9910-2f48-a71b97ede502, Type 0x77036cd4, Active False
uefisecapp_b:        Offset 0x000000005a4df000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 4c04a652-4d44-252e-515f-1bdfe33f36ff, Type 0x77036cd4, Active False
imagefv_b:           Offset 0x000000005a6df000, Length 0x0000000000200000, Flags 0x0000000000000001, UUID e970ad00-90a7-484e-0457-9d0dfb2628a0, Type 0x77036cd4, Active False
shrm_b:              Offset 0x000000005a8df000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID d8f30d78-6add-09ed-b591-972b9d6deee5, Type 0x77036cd4, Active False
vm-bootsys_b:        Offset 0x000000005a8ff000, Length 0x0000000010625000, Flags 0x0000000000000000, UUID 9533f99f-7af8-9af7-2b57-a8c456c37a46, Type 0x77036cd4, Active False
multiimgoem_b:       Offset 0x000000006af24000, Length 0x0000000000008000, Flags 0x1000000000000000, UUID 0632f3e1-6441-b040-e7be-fc259f318d43, Type 0x77036cd4, Active False
cpucp_b:             Offset 0x000000006af2c000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID 9818fb10-27af-6871-28dc-5cfbf80f467c, Type 0x77036cd4, Active False
featenabler_b:       Offset 0x000000006b02c000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID 7b756c78-a9b1-5ec8-d122-67388738ac95, Type 0x77036cd4, Active False
qweslicstore_b:      Offset 0x000000006b04c000, Length 0x0000000000040000, Flags 0x1000000000000000, UUID 1756d0d7-5bf2-3cc1-80f2-bdb974f07d6a, Type 0x77036cd4, Active False
splash_b:            Offset 0x000000006b08c000, Length 0x00000000020a4000, Flags 0x0000000000000000, UUID 84591560-a2c7-cc95-55e8-5fbd25779ef0, Type 0x77036cd4, Active False
oplus_sec_b:         Offset 0x000000006d130000, Length 0x0000000000a00000, Flags 0x0000000000000000, UUID e023483d-e52b-a5af-a9c1-592adef64f8b, Type 0x77036cd4, Active False
devinfo:             Offset 0x000000006db30000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID 04bcd1d9-3813-1a14-db01-8e139d6d4fd5, Type 0x65addcf4, Active False
dip:                 Offset 0x000000006db31000, Length 0x0000000000100000, Flags 0x1000000000000000, UUID e3d3e984-d58a-26b9-f461-26220e225666, Type 0x4114b077, Active False
apdp:                Offset 0x000000006dc31000, Length 0x0000000000040000, Flags 0x0000000000000000, UUID fb88e0be-462d-b8c4-d830-79e47c447a82, Type 0xe6e98da2, Active False
limits:              Offset 0x000000006dc71000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID 0aa1ce72-aaeb-4c47-d4a5-d8e4101d765c, Type 0x10a0c19c, Active False
limits-cdsp:         Offset 0x000000006dc72000, Length 0x0000000000001000, Flags 0x1000000000000000, UUID 3cc17e89-77f5-ca02-85ab-7c9b5cac5623, Type 0x545d3707, Active False
logfs:               Offset 0x000000006dc73000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID e003931c-df57-2b3f-79b8-75c60fb2b521, Type 0xbc0330eb, Active False
logdump:             Offset 0x000000006e473000, Length 0x0000000004000000, Flags 0x0000000000000000, UUID adaa8203-2717-de9a-95a7-454f05f5c38a, Type 0x5af80809, Active False
modemdump:           Offset 0x0000000072473000, Length 0x0000000012c00000, Flags 0x0000000000000000, UUID 660d2397-d675-d3cf-048c-4ddcec2db77b, Type 0x9877e289, Active False
storsec:             Offset 0x0000000085073000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 37648f78-fdd2-3fc2-d999-d5639ccd5f3a, Type 0x2db45fe, Active False
uefivarstore:        Offset 0x0000000085093000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID b351a659-6071-9fa2-0872-b57e124782ce, Type 0x165bd6bc, Active False
secdata:             Offset 0x0000000085113000, Length 0x0000000000007000, Flags 0x1000000000000000, UUID 83a506cb-ab2c-c1bd-5762-f2fa0eef3056, Type 0x76cfc7ef, Active False
vm-data:             Offset 0x000000008511a000, Length 0x00000000020a4000, Flags 0x0000000000000000, UUID 84899e48-0301-c810-da04-e3058e79b61e, Type 0x21adb864, Active False
mdcompress:          Offset 0x00000000871be000, Length 0x0000000001400000, Flags 0x1000000000000000, UUID e18bedc9-ee3d-8be0-2f7d-7df6f066ff27, Type 0xc6a5a9f5, Active False
connsec:             Offset 0x00000000885be000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 70684d62-f693-5309-bd6d-980bc37048a3, Type 0x6a716f7c, Active False
tzsc:                Offset 0x00000000885de000, Length 0x0000000000020000, Flags 0x1000000000000000, UUID 3ec74e21-2dc0-4449-6645-130789dec429, Type 0x478dea49, Active False
spunvm:              Offset 0x00000000885fe000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID 9d057121-8bd3-7145-9fb3-97e1514658e4, Type 0xe42e2b4c, Active False
rtice:               Offset 0x000000008a5fe000, Length 0x0000000000080000, Flags 0x1000000000000000, UUID 169af69f-f9df-701f-403c-d9699ea297cd, Type 0xe396d1ea, Active False
boot_b:              Offset 0x000000008a67e000, Length 0x000000000c000000, Flags 0x0000000000000000, UUID 4e329b5e-566a-0634-1a2b-020b8f0b513f, Type 0x77036cd4, Active False
vendor_boot_b:       Offset 0x000000009667e000, Length 0x000000000c000000, Flags 0x0000000000000000, UUID 53d775d4-7a61-32e0-17d7-6c1779579a30, Type 0x77036cd4, Active False
apdp_full:           Offset 0x00000000a267e000, Length 0x0000000000040000, Flags 0x0000000000000000, UUID 067d8ab6-757e-0a9e-b70d-c607fb3ec5d4, Type 0x114d49de, Active False

Total disk size:0x00000000a4c1c000, sectors:0x00000000000a4c1c

Parsing Lun 5:

GPT Table:
-------------
ALIGN_TO_128K_2:     Offset 0x0000000000006000, Length 0x000000000001a000, Flags 0x1000000000000000, UUID 07e4c558-3bbe-12ff-d7bc-f2b945ff05f7, Type 0x6891a3b7, Active False
oplusdycnvbk:        Offset 0x0000000000020000, Length 0x0000000001400000, Flags 0x0000000000000000, UUID c7c249d7-1fec-2b01-7d8b-b10e7b854daf, Type 0x9a6db5c7, Active False
oplusstanvbk_a:      Offset 0x0000000001420000, Length 0x0000000001400000, Flags 0x0000000000000000, UUID 1c1af1f8-e7b9-092c-0d13-2f43a98ff6ff, Type 0x3c2edd33, Active False
modemst1:            Offset 0x0000000002820000, Length 0x0000000000300000, Flags 0x0000000000000000, UUID eac46d1d-eb70-f8ef-d200-06ae575718b2, Type 0xebbeadaf, Active False
modemst2:            Offset 0x0000000002b20000, Length 0x0000000000300000, Flags 0x0000000000000000, UUID 7778bc1d-5df6-bd38-3e78-e3ea9488abec, Type 0xa288b1f, Active False
fsg:                 Offset 0x0000000002e20000, Length 0x0000000000300000, Flags 0x1000000000000000, UUID aa445ba9-05d1-eb83-b973-6057691be91e, Type 0x638ff8e2, Active False
fsc:                 Offset 0x0000000003120000, Length 0x0000000000020000, Flags 0x0000000000000000, UUID f014fd2b-cf80-3157-f989-849e39c953be, Type 0x57b90a16, Active False
mdm1m9kefs3:         Offset 0x0000000003140000, Length 0x0000000000200000, Flags 0x1000000000000000, UUID eb2b30c7-3273-56fb-e3b5-96a3d53b3281, Type 0xbf64fb9c, Active False
mdm1m9kefs1:         Offset 0x0000000003340000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 03abfa7b-ff57-cd89-bd45-9f9595375f84, Type 0x2290be64, Active False
mdm1m9kefs2:         Offset 0x0000000003540000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID 5a5d3fcf-8e17-5a03-3809-ca9bf9362197, Type 0x346c26d1, Active False
mdm1m9kefsc:         Offset 0x0000000003740000, Length 0x0000000000001000, Flags 0x0000000000000000, UUID 7b62135a-84b5-99b4-1e80-0a4fb6c5bd14, Type 0x5cb43a64, Active False
mdm1oemnvbktmp:      Offset 0x0000000003741000, Length 0x0000000000200000, Flags 0x0000000000000000, UUID a7a57b99-e368-9cdb-99be-39c167ac2177, Type 0xebbeadae, Active False
oplusreserve1:       Offset 0x0000000003941000, Length 0x0000000000800000, Flags 0x0000000000000000, UUID 6d334a1f-840f-014c-f7ba-8ff33d9ae6e0, Type 0xcc5060f0, Active False
oplusreserve2:       Offset 0x0000000004141000, Length 0x0000000010000000, Flags 0x0000000000000000, UUID b16a1c0d-14b5-7602-5f5f-e3b08505f93f, Type 0x918d1b9c, Active False
oplusreserve3:       Offset 0x0000000014141000, Length 0x0000000004000000, Flags 0x0000000000000000, UUID 447ca89d-d724-64b6-9fbc-d71e86a56834, Type 0x3c94aa5b, Active False
oplusreserve4:       Offset 0x0000000018141000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID c84cb304-0f1f-d2c1-991d-a8f55dc42cdb, Type 0x93979d8a, Active False
oplusreserve5:       Offset 0x000000001a141000, Length 0x0000000004000000, Flags 0x0000000000000000, UUID 6323ed89-946f-a2d4-e840-d791738d094e, Type 0x56ff8b14, Active False
DRIVER:              Offset 0x000000001e141000, Length 0x0000000002000000, Flags 0x0000000000000000, UUID 92f4f72d-17ef-9cbf-02dd-dd2f9539544b, Type 0x4a6838, Active False
oplusstanvbk_b:      Offset 0x0000000020141000, Length 0x0000000001400000, Flags 0x0000000000000000, UUID 9a573cf3-ea0e-8393-ebdd-fe172a41e296, Type 0x77036cd4, Active False

Total disk size:0x000000002441c000, sectors:0x000000000002441c

firehose
firehose - [LIB]: INFO: Calling handler for read
firehose
firehose - [LIB]: ERROR: Failed to open the UFS Device slot 0 partition 6
firehose
firehose - [LIB]: ERROR: Failed to open the device:3 slot:0 partition:6 error:0
firehose
firehose - [LIB]: ERROR: OPEN handle NULL and no error, weird 344608228
firehose
firehose - [LIB]: ERROR: Failed to open device, type:UFS, slot:0, lun:6 error:3
allexbast@allexbast-W170ER:/media/allexbast/74f1bb32-419e-d801-30f0-bb32419ed801/edl$

**Comment by allex2** [comment]
Understood. My phone was bricked. Restored from a dump. Everything is working. Thanks for your program. Without it, I could not restore the phone.

**Comment by iisnsb** [comment]
How did you solve it? I need help.
