### ISSUE TITLE
edl print gpt error

### ISSUE THREAD

**Issue by dengshuangjang** [bkerler/edl#320]
libusb-win32 device

E:\AAA\edl-master>python  QualCommLong.py
17:30:20: 错误: Unable to set default locale: 'unsupported locale setting'
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader E:\AAA\edl-master\Loaders+\prog_emmc_firehose_8916.mbn ...
main - Waiting for the device
main - Device detected :)
DeviceClass - USBError(None, b'libusb0-dll:err [_usb_reap_async] reaping request failed, win err
or: \xc1\xac\xb5\xbd\xcf\xb5\xcd\xb3\xc9\xcf\xb5\xc4\xc9\xe8\xb1\xb8\xc3\xbb\xd3\xd0\xb7\xa2\xbb
\xd3\xd7\xf7\xd3\xc3\xa1\xa3\r\n\n')
DeviceClass - USBError(None, b'libusb0-dll:err [_usb_reap_async] timeout error\n')
DeviceClass - USBError(None, b'libusb0-dll:err [_usb_reap_async] timeout error\n')
Device is in Sahara error state, please reboot the device.
main - Mode detected: error
Connection detected, quiting.

**Comment by dengshuangjang** [comment]
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main
main - [LIB]: Please first install libusb_win32 driver from Zadig
main - Using loader E:\AAA\edl-master\Loaders+\prog_emmc_firehose_8916.mbn ...
main - Waiting for the device
main - Device detected :)
DeviceClass - Warning !
main - Mode detected: sahara
Traceback (most recent call last):
  File "E:\AAA\edl-master\edl", line 391, in <module>
    base.run()
  File "E:\AAA\edl-master\edl", line 374, in run
    sc.handle_streaming(cmd, options)
  File "E:\AAA\edl-master\edlclient\Library\streaming_client.py", line 79, in handle_streaming
DeviceClass - SerialException("GetOverlappedResult failed (PermissionError(13, '连到系统上的设备没有发挥作用。', None, 31))")
    if self.streaming.connect(mode):
  File "E:\AAA\edl-master\edlclient\Library\streaming.py", line 781, in connect
    i = resp[1]
IndexError: index out of range

**Comment by bkerler** [comment]
Windows driver issue.
