### ISSUE TITLE
Build issue under Debian 11 Python3 gives ImportError "No module named setuptools"

### ISSUE THREAD

**Issue by Mercedes-Joy** [bkerler/edl#324]
While following the Linux (Debian/Ubuntu/Mint/etc) install procedure from the README file I encounter the following error in the build process on the final step - sudo python setup.py install -
`sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools`

**Comment by dudeitssm** [comment]
Can you replace that `python` with `python3` instead? 
That is what I did on a Debian container with USB passed through and it worked for me.

**Comment by diamant3** [comment]
try these commands

python3
``sudo apt-get install python3-setuptools``
``sudo pip3 install setuptools``

python2.x or older version
``sudo apt-get install python-setuptools``
``sudo pip install setuptools``
