### ISSUE TITLE
msm8916 usb wifi dongle PBL dump error

### ISSUE THREAD

**Issue by madushan1000** [bkerler/edl#326]
When I try to dump the pbl of [this device](https://hackaday.com/2022/08/03/hackable-20-modem-combines-lte-and-pi-zero-w2-power/), I get an error around 75%. I tried other loaders too, same error. the resulting pbl file has a lot of zeros at the end so I'm guessing it's still usable. 
Is there a way to verify if the loader is running in EL3? 
```
❯ ../../edl/edl pbl pbl.bin.1
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x007050e100000000 (MSM_ID:0x007050e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x0ed7cc48

sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4614048173062ae4_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/xiaomi/007050e100000000_278448179ac756a1_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/xiaomi/007050e100000000_50838757eab7c632_fhprg_peek_wt88047.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_8ecf3eaa03f772e2_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_394a2e47cf830150_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/lenovo_motorola/007050e100000000_99c8c13e374c34d8_fhprg_peek.bin
sahara - Trying loader: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose
firehose - [LIB]: !DEBUG! rsp.data: 'bytearray(b'<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0801BDA8 fh@0x08018C10" /></data>')'
firehose - TargetName=MSM8916
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose_client - Supported functions:
-----------------
firehose - Peek: Address(0x100000),Size(0x1ffb0)
Progress: |██████████████████████████████████████------------|  75.0% Complete                                                                  Traceback (most recent call last):
  File "/home/mnishant/Dev/my/routers/msm8916/../../edl/edl", line 391, in <module>
    base.run()
  File "/home/mnishant/Dev/my/routers/msm8916/../../edl/edl", line 386, in run
    fh.handle_firehose(cmd, options)
  File "/home/mnishant/Dev/my/edl/edlclient/Library/firehose_client.py", line 389, in handle_firehose
    if self.firehose.cmd_peek(target_name[0][0], target_name[0][1], filename, True):
  File "/home/mnishant/Dev/my/edl/edlclient/Library/firehose.py", line 1449, in cmd_peek
    rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
IndexError: list index out of range

```

**Comment by 185264646** [comment]
> When I try to dump the pbl of [this device](https://hackaday.com/2022/08/03/hackable-20-modem-combines-lte-and-pi-zero-w2-power/), I get an error around 75%. I tried other loaders too, same error. the resulting pbl file has a lot of zeros at the end so I'm guessing it's still usable. Is there a way to verify if the loader is running in EL3?
> 
> ```
> ❯ ../../edl/edl pbl pbl.bin.1
> Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
> main - Trying with no loader given ...
> main - Waiting for the device
> main - Device detected :)
> sahara - Protocol version: 2, Version supported: 1
> main - Mode detected: sahara
> sahara - 
> ------------------------
> HWID:              0x007050e100000000 (MSM_ID:0x007050e1,OEM_ID:0x0000,MODEL_ID:0x0000)
> CPU detected:      "MSM8916"
> PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
> Serial:            0x0ed7cc48
> 
> sahara - Possibly unfused device detected, so any loader should be fine...
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_d36c6073c9c2cb1c_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4614048173062ae4_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/xiaomi/007050e100000000_278448179ac756a1_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/xiaomi/007050e100000000_50838757eab7c632_fhprg_peek_wt88047.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_8ecf3eaa03f772e2_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/qualcomm/factory/msm8916/007050e100000000_394a2e47cf830150_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/longcheer/007050e100000000_3022817d373fd7f9_fhprg_peek.bin
> sahara - Possible loader available: /home/mnishant/Dev/my/edl/edlclient/../Loaders/lenovo_motorola/007050e100000000_99c8c13e374c34d8_fhprg_peek.bin
> sahara - Trying loader: /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin
> sahara - Protocol version: 2, Version supported: 1
> sahara - Uploading loader /home/mnishant/Dev/my/edl/edlclient/../Loaders/cyanogen/007050e100000000_4e3eefa63a67eb7a_fhprg_peek.bin ...
> sahara - 32-Bit mode detected.
> sahara - Firehose mode detected, uploading...
> sahara - Loader successfully uploaded.
> main - Trying to connect to firehose loader ...
> firehose_client
> firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
> firehose
> firehose - [LIB]: !DEBUG! rsp.data: 'bytearray(b'<?xml version="1.0" encoding="UTF-8" ?><data><log value="logbuf@0x0801BDA8 fh@0x08018C10" /></data>')'
> firehose - TargetName=MSM8916
> firehose - MemoryName=eMMC
> firehose - Version=1
> firehose - Trying to read first storage sector...
> firehose - Running configure...
> firehose_client - Supported functions:
> -----------------
> firehose - Peek: Address(0x100000),Size(0x1ffb0)
> Progress: |██████████████████████████████████████------------|  75.0% Complete                                                                  Traceback (most recent call last):
>   File "/home/mnishant/Dev/my/routers/msm8916/../../edl/edl", line 391, in <module>
>     base.run()
>   File "/home/mnishant/Dev/my/routers/msm8916/../../edl/edl", line 386, in run
>     fh.handle_firehose(cmd, options)
>   File "/home/mnishant/Dev/my/edl/edlclient/Library/firehose_client.py", line 389, in handle_firehose
>     if self.firehose.cmd_peek(target_name[0][0], target_name[0][1], filename, True):
>   File "/home/mnishant/Dev/my/edl/edlclient/Library/firehose.py", line 1449, in cmd_peek
>     rdata = self.xml.getlog(tmp)[0].replace("0x", "").replace(" ", "")
> IndexError: list index out of range
> ```

Use lk2nd to dump pbl, or you can use `edl dump` to read raw memory, with a smaller size, the real size of PBL is much less than 96KB anyway.

**Comment by bkerler** [comment]
I've fixed the issue.
