### ISSUE TITLE
MSM8996AU Loader

### ISSUE THREAD

**Issue by blackfa1con** [bkerler/edl#328]
Hello
I have a new hardware with MSM8996A ( Automotive ) 

SerialNumber: 0x77d98234
MSM_HW_ID: 0x000710e1
OEM_PK_HASH: 0xeed1b3f779f75d4500d87debc24b6ea3ddb36dadb082deb8b30243aa1230d3fb
SBL SW Version: 0x00000000

I can't find any loader that match this ID : 0x000710e1
Can i know if there is any loader out there for this CPU or can i pull the loader from clean emmc dump?

**Comment by bkerler** [comment]
Most probably you will get the loader only from the vendor (if at all), sorry.
