### ISSUE TITLE
Question about EDL Auth

### ISSUE THREAD

**Issue by wolverine998** [bkerler/edl#331]
Where is the authentication implemented, in the firehose programer or the PBL? Is it possible to bypass the authentication, and if it's implemented in programmer, can it be patched?

**Comment by Zibri** [comment]
I just tried that.. yes it' implemented in the programmer and I bypassed it trivially, but the edl hangs...
Now I have to check if it is itself checking for integrity or something else...
Even changing a single string (not the debug strings) causes the same behaviour.

**Comment by wolverine998** [comment]
I Will inspect it too, but i don't know what to edit, which parts, and what program to use to inspect programmer code. Can the programmer be reversed to readable code?

**Comment by bkerler** [comment]
It's implemented in the firehose loader, but the firehose loader is rsa signed and verified by the Bootrom, thus you will need the rsa private key to sign it if you want to modify the loader.

**Comment by Zibri** [comment]
> It's implemented in the firehose loader, but the firehose loader is rsa signed and verified by the Bootrom, thus you will need the rsa private key to sign it if you want to modify the loader.

true. I wonder if we can bruteforce the key using a distributed system...
it would be great.

**Comment by qiurigao** [comment]
> 它是在 firehose 加载程序中实现的，但 firehose 加载程序是由 Bootrom 进行 rsa 签名和验证的，因此，如果要修改加载程序，则需要 rsa 私钥对其进行签名。



> It's implemented in the firehose loader, but the firehose loader is rsa signed and verified by the Bootrom, thus you will need the rsa private key to sign it if you want to modify the loader.

How to view the signature information of the firehose loader file, such as the public key?
