### ISSUE TITLE
[Q] What does this do?

### ISSUE THREAD

**Issue by Person0z** [bkerler/edl#332]
Hey, so my device is not entirely "bricked" I hear the USB disconnect and reconnect- that's how I know it's not bricked. Now, my device is stuck in EDL because one plus software is dog. Would this just get me out of EDL or wipe my whole phone?

**Comment by bkerler** [comment]
Depends on the oneplus model. With newer oneplus such as oneplus 10, you're out of luck as they use VIP programming, making non-factory usage impossible.

**Comment by Person0z** [comment]
> Depends on the oneplus model. With newer oneplus such as oneplus 10, you're out of luck as they use VIP programming, making non-factory usage impossible.

I'm on the 8T

**Comment by bkerler** [comment]
That should work.
