### ISSUE TITLE
It works on linux but....

### ISSUE THREAD

**Issue by Zibri** [bkerler/edl#334]
On Xiaomi Redmi Note 10 Pro, the detected bootloader is wrong and hangs.
I used the file from the installed rom and it works but obviously needs authentication.
I reversed the elf file and removed the authentication check but edl hangs again.
So I had a doubt and I changed a string leaving the original code. And it HANGS.
So I think even EDL is checked for integrity...
What now?

**Comment by bkerler** [comment]
Game over. Welcome to the new world of remote auth and VIP Programming. These days, EDL mostly only works for unfused devices :(
