### ISSUE TITLE
Time out loop

### ISSUE THREAD

**Issue by animaxtor** [bkerler/edl#335]
I'm trying to get out of edl mode with the following command:

`edl --loader=prog_firehose_ddr.elf`

But  it doesn't go beyond "Device detected":

`Capstone library is missing (optional).`
`Keystone library is missing (optional).`
`Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.`
`main - Using loader prog_firehose_ddr.elf ...`
`main - Waiting for the device`
`main - Device detected :)`

If I unplug the device I get an error: 

`Capstone library is missing (optional).`
`Keystone library is missing (optional).`
`Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.`
`main - Using loader prog_firehose_ddr.elf ...`
`main - Waiting for the device`
`main - Device detected :)`
`DeviceClass - USBError(5, 'Input/Output Error')`
`Device is in Sahara error state, please reboot the device.`
`main - Mode detected: error`
`Connection detected, quiting.`

If I add --debugmode I get a Time out error Loop

`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: Timed out`
`DeviceClass`
`DeviceClass - [LIB]: [Errno 110] Operation timed out`
`DeviceClass`
`DeviceClass - [LIB]: [Errno 110] Operation timed out`
`DeviceClass`
`DeviceClass - [LIB]: [Errno 110] Operation timed out`

**Comment by AdaPoolPoop** [comment]
I have the same problem with OnePlus 9 Pro TMO. I tried Linux first (need to create logs.txt or it'll keep failing), windows and the livedvd and still get the issue

**Comment by AdaPoolPoop** [comment]
Updated for the way I solved it^
