### ISSUE TITLE
Multiple loader with same hwid and pkhash gives syntax error

### ISSUE THREAD

**Issue by mahdihasnat** [bkerler/edl#336]
when `--debugmode` is enabled, following error occurs multiple times:
```
loader_utils - [LIB]: 'str' object has no attribute 'append'
```
From my understanding this error message is created from following code ( loader_db.py:56):
``` python
	self.loaderdb[mhwid][pkhash].append(fn)
```
It happens if there are multiple loader file with same hwid and pkhash.
Now, `loaderdb[mhwid][pkhash]` is 'str' type.
If we want to store multiple file name(fn variable) in `loaderdb[mhwid][pkhash]`, then we should be used list of str.

Can this error be solved?

**Comment by bkerler** [comment]
Solved with commit [f0844a2](https://github.com/bkerler/edl/commit/f0844a265a4a0cef41aeb213181b64c97be815c2). A List would mean that multiple loader with same hwid and pkhash can be loaded, which doesn't make sense, as there is always just one loader matching one device (and thus hwid + pkhash)
