### ISSUE TITLE
QFIL

### ISSUE THREAD

**Issue by kiam001** [bkerler/edl#34]
<maik@maik-ThinkPad-X250:~/Downloads/edl$ ./qfil.py --log_level info --firehose ../qcom8937_spf1.0_1605052340_qpst/prog_emmc_firehose_8937_ddr.mbn --rawprogram ../qcom8937_spf1.0_1605052340_qpst/rawprogram0.xml --patch ../qcom8937_spf1.0_1605052340_qpst/patch0.xml --imagedir ../qcom8937_spf1.0_1605052340_qpst
[INFO] firehose image: ../qcom8937_spf1.0_1605052340_qpst/prog_emmc_firehose_8937_ddr.mbn
[INFO] rawprogram files: ['../qcom8937_spf1.0_1605052340_qpst/rawprogram0.xml']
[INFO] patch files: ['../qcom8937_spf1.0_1605052340_qpst/patch0.xml']
[INFO] USB device 0x05c6:0x9008
[USB] waiting for device connecting...
Traceback (most recent call last):
  File "./qfil.py", line 120, in <module>
    if cdc.connect():
  File "/home/maik/Downloads/edl/Library/usblib.py", line 155, in connect
    self.log.debug(self.configuration)
AttributeError: 'NoneType' object has no attribute 'debug'

**Comment by bkerler** [comment]
This bug is already known and will be fixed soon after the restructure of the project :)

**Comment by bkerler** [comment]
Fixed with commit 036bc63
