### ISSUE TITLE
Unexpected error on uploading loader

### ISSUE THREAD

**Issue by asro56** [bkerler/edl#342]
My phone is mi9t pro(redmi k20 pro) in edl mode.I want to unbrick my phone and recover my data.Also i used different loader found on some site "prog_ufs_firehose_sdm855_ddr.elf" gives same error.I attached log.

user@livedvd:/opt/edl$ ./edl printgpt --memory=ufs
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
HWID:              0x000a50e100720000 (MSM_ID:0x000a50e1,OEM_ID:0x0072,MODEL_ID:0x0000)
CPU detected:      "SM8150"
PK_HASH:           0x1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe3
Serial:            0x233fa8d0

sahara - Detected loader: /opt/edl/edlclient/../Loaders/xiaomi/EDLAuth/000a50e100720000_1bebe3863a6781db_fhprg_edlauth.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /opt/edl/edlclient/../Loaders/xiaomi/EDLAuth/000a50e100720000_1bebe3863a6781db_fhprg_edlauth.bin ...
sahara - 64-Bit mode detected.
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
type object 'req' has no attribute 'image_id'

**Comment by asro56** [comment]
With debugmode log
user@livedvd:/opt/edl$ ./edl printgpt --memory=ufs --debugmode
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: list index out of range
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8626'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8974'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'mprg8974'
loader_utils
loader_utils - [LIB]: invalid literal for int() with base 16: 'prog'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
loader_utils
loader_utils - [LIB]: 'str' object has no attribute 'append'
main - Trying with no loader given ...
main - Waiting for the device
DeviceClass
DeviceClass - [LIB]: Detaching kernel driver
main - Device detected :)
DeviceClass
DeviceClass - [LIB]: read:0x30
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 295, in run\n    conninfo = self.doconnect(loop)\n', '  File "/opt/edl/./edl", line 211, in doconnect\n    resp = self.sahara.connect()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 111, in connect\n    v = self.cdc.read(length=0xC * 0x4,timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:010000003000000002000000010000000004000000000000000000000000000000000000000000000000000000000000
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 212, in cmd_info\n    if self.enter_command_mode():\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 155, in enter_command_mode\n    if not self.cmd_hello(sahara_mode_t.SAHARA_MODE_COMMAND):\n']
DeviceClass
DeviceClass - [LIB]: TX:020000003000000002000000010000000000000003000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 212, in cmd_info\n    if self.enter_command_mode():\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 157, in enter_command_mode\n    res = self.get_rsp()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 64, in get_rsp\n    data = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:0b00000008000000
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 213, in cmd_info\n    self.serial = self.cmdexec_get_serial_num()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 173, in cmdexec_get_serial_num\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_SERIAL_NUM_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0d0000000c00000001000000
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 213, in cmd_info\n    self.serial = self.cmdexec_get_serial_num()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 173, in cmdexec_get_serial_num\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_SERIAL_NUM_READ)\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 593, in cmd_exec\n    res = self.get_rsp()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 64, in get_rsp\n    data = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:0e000000100000000100000004000000
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 213, in cmd_info\n    self.serial = self.cmdexec_get_serial_num()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 173, in cmdexec_get_serial_num\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_SERIAL_NUM_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0f0000000c00000001000000
DeviceClass
DeviceClass - [LIB]: cmd_exec:0x4
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 213, in cmd_info\n    self.serial = self.cmdexec_get_serial_num()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 173, in cmdexec_get_serial_num\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_SERIAL_NUM_READ)\n']
DeviceClass
DeviceClass - [LIB]: RX:d0a83f23
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 215, in cmd_info\n    self.hwid = self.cmdexec_get_msm_hwid()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 177, in cmdexec_get_msm_hwid\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_MSM_HW_ID_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0d0000000c00000002000000
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 215, in cmd_info\n    self.hwid = self.cmdexec_get_msm_hwid()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 177, in cmdexec_get_msm_hwid\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_MSM_HW_ID_READ)\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 593, in cmd_exec\n    res = self.get_rsp()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 64, in get_rsp\n    data = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:0e000000100000000200000018000000
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 215, in cmd_info\n    self.hwid = self.cmdexec_get_msm_hwid()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 177, in cmdexec_get_msm_hwid\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_MSM_HW_ID_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0f0000000c00000002000000
DeviceClass
DeviceClass - [LIB]: cmd_exec:0x18
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 215, in cmd_info\n    self.hwid = self.cmdexec_get_msm_hwid()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 177, in cmdexec_get_msm_hwid\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_MSM_HW_ID_READ)\n']
DeviceClass
DeviceClass - [LIB]: RX:00007200e1500a0000007200e1500a0000007200e1500a00
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 216, in cmd_info\n    self.pkhash = self.cmdexec_get_pkhash()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 186, in cmdexec_get_pkhash\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_OEM_PK_HASH_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0d0000000c00000003000000
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 216, in cmd_info\n    self.pkhash = self.cmdexec_get_pkhash()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 186, in cmdexec_get_pkhash\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_OEM_PK_HASH_READ)\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 593, in cmd_exec\n    res = self.get_rsp()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 64, in get_rsp\n    data = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:0e000000100000000300000090000000
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 216, in cmd_info\n    self.pkhash = self.cmdexec_get_pkhash()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 186, in cmdexec_get_pkhash\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_OEM_PK_HASH_READ)\n']
DeviceClass
DeviceClass - [LIB]: TX:0f0000000c00000003000000
DeviceClass
DeviceClass - [LIB]: cmd_exec:0x90
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 216, in cmd_info\n    self.pkhash = self.cmdexec_get_pkhash()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 186, in cmdexec_get_pkhash\n    res = self.cmd_exec(exec_cmd_t.SAHARA_EXEC_CMD_OEM_PK_HASH_READ)\n']
DeviceClass
DeviceClass - [LIB]: RX:1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe31bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe31bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe3
sahara - 
------------------------
HWID:              0x000a50e100720000 (MSM_ID:0x000a50e1,OEM_ID:0x0072,MODEL_ID:0x0000)
CPU detected:      "SM8150"
PK_HASH:           0x1bebe3863a6781db4b01086063007334de9e5ca14971c7c4f4358ec9d79cda4692ce5e948c6fd409408f4c919fcadfe3
Serial:            0x233fa8d0

sahara - Detected loader: /opt/edl/edlclient/../Loaders/xiaomi/EDLAuth/000a50e100720000_1bebe3863a6781db_fhprg_edlauth.bin
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 334, in run\n    sahara_info = self.sahara.cmd_info()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 307, in cmd_info\n    self.cmd_modeswitch(sahara_mode_t.SAHARA_MODE_COMMAND)\n']
DeviceClass
DeviceClass - [LIB]: TX:0c0000000c00000003000000
DeviceClass
DeviceClass - [LIB]: read:0x30
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 336, in run\n    resp = self.sahara.connect()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 111, in connect\n    v = self.cdc.read(length=0xC * 0x4,timeout=1)\n']
DeviceClass
DeviceClass - [LIB]: RX:010000003000000002000000010000000004000003000000000000000000000000000000000000000000000000000000
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /opt/edl/edlclient/../Loaders/xiaomi/EDLAuth/000a50e100720000_1bebe3863a6781db_fhprg_edlauth.bin ...
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 341, in run\n    mode = self.sahara.upload_loader()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 511, in upload_loader\n    if not self.cmd_hello(sahara_mode_t.SAHARA_MODE_IMAGE_TX_PENDING):\n']
DeviceClass
DeviceClass - [LIB]: TX:020000003000000002000000010000000000000000000000000000000000000000000000000000000000000000000000
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 341, in run\n    mode = self.sahara.upload_loader()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 519, in upload_loader\n    resp = self.get_rsp()\n', '  File "/opt/edl/edlclient/Library/sahara.py", line 64, in get_rsp\n    data = self.cdc.read()\n']
DeviceClass
DeviceClass - [LIB]: RX:12000000200000000d0000000000000000000000000000004000000000000000
sahara - 64-Bit mode detected.
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
type object 'req' has no attribute 'image_id'
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 370, in run\n    sc.handle_streaming(cmd, options)\n', '  File "/opt/edl/edlclient/Library/streaming_client.py", line 79, in handle_streaming\n    if self.streaming.connect(mode):\n', '  File "/opt/edl/edlclient/Library/streaming.py", line 779, in connect\n    resp = self.send(cmdbuf, True)\n', '  File "/opt/edl/edlclient/Library/streaming.py", line 996, in send\n    return self.hdlc.send_cmd_np(cmd, nocrc)\n', '  File "/opt/edl/edlclient/Library/hdlc.py", line 229, in send_cmd_np\n    return self.send_cmd_base(outdata, 0, nocrc)\n', '  File "/opt/edl/edlclient/Library/hdlc.py", line 218, in send_cmd_base\n    if self.send_unframed_buf(packet, prefixflag):\n']
DeviceClass
DeviceClass - [LIB]: TX:11001200a0e30000c1e50140a0e31eff2fe14bd97e
DeviceClass
DeviceClass - [LIB]: read:0x200
DeviceClass
DeviceClass - [LIB]: ['  File "/opt/edl/./edl", line 387, in <module>\n    base.run()\n', '  File "/opt/edl/./edl", line 370, in run\n    sc.handle_streaming(cmd, options)\n', '  File "/opt/edl/edlclient/Library/streaming_client.py", line 79, in handle_streaming\n    if self.streaming.connect(mode):\n', '  File "/opt/edl/edlclient/Library/streaming.py", line 779, in connect\n    resp = self.send(cmdbuf, True)\n', '  File "/opt/edl/edlclient/Library/streaming.py", line 996, in send\n    return self.hdlc.send_cmd_np(cmd, nocrc)\n', '  File "/opt/edl/edlclient/Library/hdlc.py", line 229, in send_cmd_np\n    return self.send_cmd_base(outdata, 0, nocrc)\n', '  File "/opt/edl/edlclient/Library/hdlc.py", line 220, in send_cmd_base\n    return self.receive_reply_nocrc()\n', '  File "/opt/edl/edlclient/Library/hdlc.py", line 174, in receive_reply_nocrc\n    tmp = self.cdc.read(timeout=timeout)\n']
DeviceClass
DeviceClass - [LIB]: RX:04000000100000000d00000008000000
DeviceClass
DeviceClass - [LIB]: Timed out
DeviceClass
DeviceClass - [LIB]: Timed out

**Comment by bkerler** [comment]
I assume you are using an outdated version of python.
