### ISSUE TITLE
Not recognizing file/partition names, Killed when writing userdata

### ISSUE THREAD

**Issue by UniqueActive** [bkerler/edl#343]
I am attemping to completely re-flash my OnePlus 6T that I somehow managed to brick, since fastboot flashing gives errors about flashing critical partitions (yes it is unlocked :shrug: ) and the msm tool did not work in my QEMU VM, recognized the device as connected but gave the Sahara error that it couldnt receive a response or something.

I decrypted a stock .ops image with the oppo_decrypt tool to a folder called "extracted" and am using the following command to flash the extracted files to the OP6T:

`./edl wl extracted --memory=UFS --loader=Loaders/oneplus/0008b0e10051459b_dd7c5f2e53176bee_fhprg_op6t.bin`

Unfortunately I have two issues here; as the title indicates, userdata flashing stops about 60% of the way with the output "Killed". When adding `--skip=userdata`, I have the second issue, which is that some files are not found in the partition table it seems. For example the "param" partition with its corresponding file "param.bin" caused the error wrong memory format or gpt partition does not exist, or something along those lines. However flashing it with `./edl w param extracted/param.bin --lun=0 --memory=UFS --loader=<same as before>` works perfectly, which makes me think this is an issue of the tool.

Do you have an idea why it may be unable to find some partitions, and what the issue with the userdata image may be? One thing I noticed is that it says the following:

```
firehose - [LIB]: Couldn't detect MaxPayloadSizeFromTargetinBytes
firehose
firehose - [LIB]: Couldn't detect TargetName
firehose - TargetName=Unknown

```

Are these two things related? Thanks very much in advance!

**Comment by nilsdev** [comment]
Can confirm I have the exact same situation (OnePlus 8t)

**Comment by bkerler** [comment]
If you flash critical partitions like tz, make sure to reboot the device after flashing. Otherwise, flashing anything else will fail. Or use wf for writing a full flash instead.
