### ISSUE TITLE
edl does not detect special 9008 device

### ISSUE THREAD

**Issue by cuynu** [bkerler/edl#350]
My Sony Xperia XZ2 has been bricked because switch to slot that contain nothing, and now i want use edl to switch active slot to B but edl does not detect my device
![image](https://user-images.githubusercontent.com/90895715/200190381-a56e3ff9-d4ec-47fa-830e-6dc755cdd018.png)

**Comment by RenateUSB** [comment]
Try adding `[0x0fce, 0xade5, -1],` to `default_ids` in edlclient/Config/usb_ids.py

**Comment by cuynu** [comment]
> Try adding `[0x0fce, 0xade5, -1],` to `default_ids` in edlclient/Config/usb_ids.py

Thank you so much, my device was detected, but there is no loader
