### ISSUE TITLE
Unknown mode. Aborting.

### ISSUE THREAD

**Issue by Loscope** [bkerler/edl#351]
I don´t know what i need to do to revive my phone it does not boot to fastboot, edl, adb or recovery.
Accidently flashed my system in boot slot B (my boot slot was A) and now it can connect to pc but show that is in Unknown mode and already installed zadig drivers
![Screenshot 2022-11-08 215916](https://user-images.githubusercontent.com/75727237/200684843-ad6701a5-d4ff-44d9-8ad8-cedc560f900a.png)

**Comment by bkerler** [comment]
I assume you have a vid of 0x900E, which is crash mode. You need to short emmc dat0 to gnd in order to get 0x9008 to flash anything (remove short once you see usb vid 0x9008.
