### ISSUE TITLE
Oneplus 7 Pro GM1913 Timed out error after detection [bizarre EDL bug]

### ISSUE THREAD

**Issue by elliot-holley** [bkerler/edl#352]
hello
I have a Op7pro GM1913 that appears to have had some serious diddling done with it. 
[log.txt](https://github.com/bkerler/edl/files/9995774/log.txt) heres what edl makes of it. you can see that it is able to read the memory in the command i tried about 100 lines down. 
the device shows no sign of life at all besides showing up as the usual 9008 serial port on both windows and linux. all msmdownloadtools state that GetUfsInfo failed. and advice would be appreciated!

**Comment by bkerler** [comment]
means issues with the ufs flash.
