### ISSUE TITLE
Permission Denied when reading partitions

### ISSUE THREAD

**Issue by SR72-Blackbird** [bkerler/edl#355]
I am having an issue where whenever I am trying to read a partition to an image file or read the entire phone to a flash.bin file, it gives me something along the lines of this
`firehose - [LIB]: ['range restricted: physical_partition_number=0, start_sector=0, num_sectors=61071360', 'Permission denied ']`

However, it does print the GPT table just fine, and gives me a lot of information about the phone, but for some reason I can't read partitions.
It would be greatly appreciated if someone could help me with this as I am trying to recover data from the phone.

**Comment by SR72-Blackbird** [comment]
I have a Moto X4. Did you ever solve the error. I also ran `--memory=emmc` but that didn't solve it. I am somewhat new to Android and would appreciate all the help I can get.

**Comment by RenateUSB** [comment]
Could this be related to "VIP" (Validated Image Programming)?
Check your loader for occurrences of the text "VIP".
```
VIP is enabled, receiving the signed table of size %d
Number of VIP hashes %d on initial table
VIP table contains more than %d hashes, %d/%d=%d
VIP hash table accepted %d packet %d
VIP data verified table %d packet %d
Last packet received, re-initializing VIP %d %d
```
Looking at the loader repository, about a third have VIP stuff.
OTOH, I'm using one loader with VIP in it on another device and it works flawlessly.

**Comment by RenateUSB** [comment]
"range restricted" is to be found only in Lenovo/Motorola Firehose loaders.

**Comment by RenateUSB** [comment]
I'm looking into the code, but I did some more checking too.
On my device:
```
     0     255  can read (GPT)
   256  131071  can't read (after GPT, before first partition)
131072  418111  can read (xbl_a to ddr, p1 to p29)
418112          can't read (modem_a and further partitions. p30 to p77)
```
So, it's definitely doing this based on the GPT that it loaded.
But why blacklist boot and allow xbl and abl?

**Comment by RenateUSB** [comment]
I'm getting closer.
I can see the table for allowed accesses. This is for eMMC, there's another for UFS.
```
           LUN               Start             Count
[000083b8] 00000000 00000000 00000000 00000000 00000100 00000000 // gpt
[000083d0] 00000000 00000000 ffffffdf ffffffff 00000021 00000000 // last 33 blocks
[000083e8] 00000000 00000000 00020000 00000000 00045940 00000000 // xbl_a - storsec_b
[00008400] 00000000 00000000 00065940 00000000 00000800 00000000 // ddr
[00008418] 00000001 00000000 00000001 00000000 00000001 00000000 // LUN 1???
```
There is a routine that tests whether this device is "secure" and bypasses this range checking if not.
It calls something that looks? like it's in ROM code?

**Comment by RenateUSB** [comment]
I made a trivial, one byte (spelling) change to my loader and of course it failed to load.
The thing is, I can't reconcile the SHA256 hashes of the program segments with the hashes in program segment 1.
So I can't generate new hashes

I can verify the hashes on another loader I use for another device.
I can make a spelling change, generate a new hash and the modified loader loads fine.
Of course this is because this device is not SecureBoot and although it needs correct hashes it doesn't check the signing.

**Comment by RenateUSB** [comment]
Well, clearly Motorola has some specific lock.
```
fastboot oem partition sha256 boot_a
(bootloader) Command restricted!
```
I looked at the abl code. To be unrestricted you have to have `CID==0xff` or a bit set that gets set when you flash something special.

**Comment by bkerler** [comment]
Closing this now, as it's indeed motorola locking us out.
