### ISSUE TITLE
Qc_diag

### ISSUE THREAD

**Issue by rhamadhany** [bkerler/edl#356]
can you add qcn backup and restore feature to qc_diag? like in qpst or qfil.. I've been looking around for such a tool for linux and found nothing, a or do you already have such a tool?? i don't have windows anymore for now because my pc doesn't turn on anymore so i just use linux on android with otg.. and qc_diag running normally on my distro .. thanks

**Comment by bkerler** [comment]
the issue is that I don't know the structure of the qcn files. If you know how they are structured, I can add qcn backup and restore.
