### ISSUE TITLE
error while installing requirements 

### ISSUE THREAD

**Issue by AliRazaManzoor** [bkerler/edl#357]
Running setup.py install for pylzma ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pylzma did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      copying py7zlib.py -> build\lib.win-amd64-3.9
      running build_ext
      adding support for multithreaded compression
      building 'pylzma' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pylzma

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by suleramaa** [comment]
install Microsoft Visual C++ latest

**Comment by AliRazaManzoor** [comment]
Microsoft Windows [Version 10.0.19044.2251]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Revskills\Desktop\edl\edl>pip3 install -r requirements.txt
Collecting wheel
  Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
Collecting pyusb>=1.1.0
  Using cached pyusb-1.2.1-py3-none-any.whl (58 kB)
Requirement already satisfied: pyserial>=3.4 in c:\users\revskills\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 3)) (3.5)
Collecting docopt>=0.6.2
  Using cached docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting pylzma>=0.5.0
  Using cached pylzma-0.5.0.tar.gz (4.2 MB)
  Preparing metadata (setup.py) ... done
Collecting pycryptodome
  Using cached pycryptodome-3.16.0-cp35-abi3-win_amd64.whl (1.7 MB)
Collecting lxml>=4.6.1
  Using cached lxml-4.9.1-cp39-cp39-win_amd64.whl (3.6 MB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: usb in c:\users\revskills\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 9)) (0.0.83.dev0)
Collecting capstone
  Using cached capstone-4.0.2-py2.py3-none-win_amd64.whl (896 kB)
Collecting keystone-engine
  Using cached keystone_engine-0.9.2-py2.py3-none-win_amd64.whl (1.4 MB)
Installing collected packages: pylzma, keystone-engine, docopt, wheel, pyusb, pycryptodome, lxml, colorama, capstone
  DEPRECATION: pylzma is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pylzma ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pylzma did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      copying py7zlib.py -> build\lib.win-amd64-3.9
      running build_ext
      adding support for multithreaded compression
      building 'pylzma' extension
      creating build\temp.win-amd64-3.9
      creating build\temp.win-amd64-3.9\Release
      creating build\temp.win-amd64-3.9\Release\src
      creating build\temp.win-amd64-3.9\Release\src\pylzma
      creating build\temp.win-amd64-3.9\Release\src\sdk
      creating build\temp.win-amd64-3.9\Release\src\sdk\C
      creating build\temp.win-amd64-3.9\Release\src\compat
      C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPY_SSIZE_T_CLEAN=1 -DWITH_COMPAT=1 -DPYLZMA_VERSION=0.5.0 -DCOMPRESS_MF_MT=1 -Isrc/sdk/C -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include /Tcsrc/pylzma/pylzma.c /Fobuild\temp.win-amd64-3.9\Release\src/pylzma/pylzma.obj
      pylzma.c
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pylzma

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Users\Revskills\Desktop\edl\edl>

**Comment by suleramaa** [comment]
install lmxl package

**Comment by suleramaa** [comment]
install lmxl package

**Comment by V0latyle** [comment]
> install Microsoft Visual C++ latest

I have the same problem.  I have Visual C++ 2015-2022 both x86 and x64 installed, but I get the same error.

**Comment by bkerler** [comment]
just ignore pylzma, it's not needed.
