### ISSUE TITLE
Onyx Leaf 2 - QCS2290 (QCS_AGATTI) - USBError(19, 'No such device (it may have been disconnected)')

### ISSUE THREAD

**Issue by Denisuu** [bkerler/edl#358]
Hi,

I'm trying to Firehose an Onxy Boox - Leaf 2 e-reader device. The chip inside is a QCS2290 (QCS_AGATTI)
[0014d0e100000000_1bebe3863a6781db_fhprg.bin](https://github.com/bkerler/Loaders/raw/main/xiaomi/0014d0e100000000_1bebe3863a6781db_fhprg.bin) contains QCS_AGATTI but I get the message:
`Unknown CPU, please send log as issue to https://github.com/bkerler/edl`

This seems to be the only Loader that returns: `sahara - Loader successfully uploaded.`

```
[denisuu@BLOOGLET edl]$ python edl --loader=0014d0e100000000_1bebe3863a6781db_fhprg.bin printgpt
Capstone library is missing (optional).
Keystone library is missing (optional).
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader 0014d0e100000000_1bebe3863a6781db_fhprg.bin ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x001860e100000000 (MSM_ID:0x001860e1,OEM_ID:0x0000,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:     0xd40eee56f3194665574109a39267724ae7944134cd53cb767e293d3c40497955bc8a4519ff992b031fadc6355015ac87
Serial:  XXXXXXX

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader 0014d0e100000000_1bebe3863a6781db_fhprg.bin ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
firehose - TargetName=
firehose - MemoryName=eMMC
firehose - Version=
firehose - Trying to read first storage sector...
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
^C
```
This error show's thousands of times within seconds if I don´t break out of it as soon as I see it pop-up.

When I don't select a Loader I get some suggestions:
```
sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/model_generic/SDM855LA/000a50e100000000_d40eee56f3194665_fhprg.bin
sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/factory/sc8180x/000b80e100000000_d40eee56f3194665_FHPRG.bin
sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/factory/sdm662/0014d0e100000000_d40eee56f3194665_FHPRG.bin
```

 none of them work. All return the same: 
```
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara
sahara - [LIB]: Error: Cannot receive specified number of program headers
Connection detected, quiting.

```

Any help would be appreciated, thanks!

**Comment by bkerler** [comment]
I've added support for the cpu. However you might need to try several firehose. It might be supported by a 0x14D0E1 (sm6115) loader, but not sure on that.

**Comment by Pyr4mus** [comment]
[prog_firehose_Qcm2290_ddr.zip](https://github.com/bkerler/edl/files/14060276/prog_firehose_Qcm2290_ddr.zip)

Try this

**Comment by Pyr4mus** [comment]
> Hi,
> 
> I'm trying to Firehose an Onxy Boox - Leaf 2 e-reader device. The chip inside is a QCS2290 (QCS_AGATTI) [0014d0e100000000_1bebe3863a6781db_fhprg.bin](https://github.com/bkerler/Loaders/raw/main/xiaomi/0014d0e100000000_1bebe3863a6781db_fhprg.bin) contains QCS_AGATTI but I get the message: `Unknown CPU, please send log as issue to https://github.com/bkerler/edl`
> 
> This seems to be the only Loader that returns: `sahara - Loader successfully uploaded.`
> 
> ```
> [denisuu@BLOOGLET edl]$ python edl --loader=0014d0e100000000_1bebe3863a6781db_fhprg.bin printgpt
> Capstone library is missing (optional).
> Keystone library is missing (optional).
> Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
> main - Using loader 0014d0e100000000_1bebe3863a6781db_fhprg.bin ...
> main - Waiting for the device
> main - Device detected :)
> sahara - Protocol version: 2, Version supported: 1
> main - Mode detected: sahara
> sahara - 
> ------------------------
> HWID:              0x001860e100000000 (MSM_ID:0x001860e1,OEM_ID:0x0000,MODEL_ID:0x0000)
> Unknown CPU, please send log as issue to https://github.com/bkerler/edl
> PK_HASH:     0xd40eee56f3194665574109a39267724ae7944134cd53cb767e293d3c40497955bc8a4519ff992b031fadc6355015ac87
> Serial:  XXXXXXX
> 
> sahara - Protocol version: 2, Version supported: 1
> sahara - Uploading loader 0014d0e100000000_1bebe3863a6781db_fhprg.bin ...
> sahara - 64-Bit mode detected.
> sahara - Firehose mode detected, uploading...
> sahara - Loader successfully uploaded.
> main - Trying to connect to firehose loader ...
> firehose_client
> firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> firehose - TargetName=
> firehose - MemoryName=eMMC
> firehose - Version=
> firehose - Trying to read first storage sector...
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> DeviceClass - USBError(19, 'No such device (it may have been disconnected)')
> ^C
> ```
> 
> This error show's thousands of times within seconds if I don´t break out of it as soon as I see it pop-up.
> 
> When I don't select a Loader I get some suggestions:
> 
> ```
> sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/model_generic/SDM855LA/000a50e100000000_d40eee56f3194665_fhprg.bin
> sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/factory/sc8180x/000b80e100000000_d40eee56f3194665_FHPRG.bin
> sahara - Found possible loader: /usr/lib/python3.10/site-packages/edlclient-3.60-py3.10.egg/edlclient/../Loaders/qualcomm/factory/sdm662/0014d0e100000000_d40eee56f3194665_FHPRG.bin
> ```
> 
> none of them work. All return the same:
> 
> ```
> sahara - 64-Bit mode detected.
> sahara - Firehose mode detected, uploading...
> sahara
> sahara - [LIB]: Error: Cannot receive specified number of program headers
> Connection detected, quiting.
> ```
> 
> Any help would be appreciated, thanks!

[prog_firehose_Qcm2290_ddr.zip](https://github.com/bkerler/edl/files/14060944/prog_firehose_Qcm2290_ddr.zip)

**Comment by RenateUSB** [comment]
How did I miss this??? It works for the Onyx Poke5, probably the Leaf2 also.

**Comment by bkerler** [comment]
Sure :)

**Comment by samuelpintodasilva458-stack** [comment]
Preciso do Firehose para Quectel SC200E / QCM2290 Agatti

HWID: 001850e100000000

PK_HASH: 33817b34be6c7e94 para Quectel SC200E / QCM2290 Agatti

HWID: 001850e100000000

**Comment by RenateUSB** [comment]
I don't see anything for that hash.

**Comment by samuelpintodasilva458-stack** [comment]
> Não vejo nada para esse hash.
Pois é, já procurei na internet e nada ate agora.
