### ISSUE TITLE
EDL is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by ansh-thecrazy** [bkerler/edl#361]
Hi,

I'm running this on windows 8.1 and getting the below error.
_'edl' is not recognized as an internal or external command, operable program or batch file._

 I have performed all the steps properly and am unable to run this. Can someone please help?

**Comment by RenateUSB** [comment]
Try `python edl` or rename it to "edl.py".

**Comment by TheMHD1** [comment]
idid rename it but it says docopt is not installed but it saus it is

C:\Users\Habibi\Downloads\edl>pip3 install docopt
Requirement already satisfied: docopt in c:\users\habibi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.6.2)

C:\Users\Habibi\Downloads\edl>edl.py
Traceback (most recent call last):
  File "C:\Users\Habibi\Downloads\edl\edl.py", line 130, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

**Comment by bkerler** [comment]
try python.exe -m pip install -r requirements.txt

**Comment by Erquint** [comment]
I ran that with `python3` (UWP).
That warned me that the darn UWP subsystem python scripts directory isn't in PATH.
Adjusted the envar, reloaded the shell and it worked.
