### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by wymdv** [bkerler/edl#364]
I installed edl in order to unlock the bootloader of a Qualcomm device.

All requirements were satisfied.

I booted the device into edl mode by adb reboot edl.

When I ran
`edl modules oemunlock enable`

It returned
`Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara -
------------------------
HWID:              0x009400e100000000 (MSM_ID:0x009400e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "MSM8994"
PK_HASH:           0xcc3153a80293939b90d02d3bf8b23e0292e452fef662c74998421adad42a380f
Serial:            0x0209e3d5
sahara - Possibly unfused device detected, so any loader should be fine...
sahara - Possible loader available: /Users/wenyuan/Desktop/Android/adb/edlclient/../Loaders/qualcomm/factory/msm8994/009400e100000000_dbbd98bdc71d24ce_fhprg_peek.bin
sahara - Possible loader available: /Users/wenyuan/Desktop/Android/adb/edlclient/../Loaders/xiaomi/009400e100000000_57158eaf1814d78f_fhprg_peek.bin
sahara - Possible loader available: /Users/wenyuan/Desktop/Android/adb/edlclient/../Loaders/cyanogen/009400e100000000_b0d6c9fc8d2cf585_fhprg_peek.bin
sahara - Trying loader: /Users/wenyuan/Desktop/Android/adb/edlclient/../Loaders/qualcomm/factory/msm8994/009400e100000000_dbbd98bdc71d24ce_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader /Users/wenyuan/Desktop/Android/adb/edlclient/../Loaders/qualcomm/factory/msm8994/009400e100000000_dbbd98bdc71d24ce_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
Traceback (most recent call last):
File "/Users/wenyuan/Desktop/Android/adb/./edl", line 391, in <module>

    base.run()

File "/Users/wenyuan/Desktop/Android/adb/./edl", line 370, in run

if "load_" in mode:

       ^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable`

What could I do to solve this issue and properly unlock the bootloader?

A side question: what is the function of "fhloaderparse" in fhloaderparse examples Loaders?

I was not sure if I properly dropped the loader (oneplus) in the right directory.

Thanks in advance for your advice.

May you need any further information, please do not hesitate to ask me.

Regards,
Wy

**Comment by bkerler** [comment]
Fixed in the current version
