### ISSUE TITLE
Support for SDX65 in latest Netgear MR6400 firmware NTGX65_10.04.13.03

### ISSUE THREAD

**Issue by wojo** [bkerler/edl#366]
Looks like the new firmware NTGX65_10.04.13.03 has changed the key (probably not algo) used for unlock. I still have telnet access, but the sierrakeygen.py tool no longer works.

Was following your posts at https://bkerler.github.io/posts/ but never saw the extraction in pt3 for the mr1100, which I imagine would be similar for the m6, etc.

Do you have a guide on how to extract the key? Not sure what is needed, imagine is the baseband image but I don't have a downloadable version of the firmware, yet. Need to find that (located in Oma settings?).

```
# cat /firmware/verinfo/Ver_Info.txt
{
    "Image_Build_IDs": {
        "aop": "AOP.HO.3.3-00046-OLYMPICAAAAANAZO-1",
        "apps": "LE.UM.5.3.2.r1-06600-SDX65.0-1",
        "boot": "BOOT.MXF.1.1.1-00111-Olympic-1.513758.4",
        "common": "Olympic.LE.1.0.r1-00637-NBOOT.NEFS.PROD-1.513758.4",
        "glue": "GLUE.OLYMPIC_LE.1.0-00278-NOOP_TEST-1",
        "lnx_host": "LE.LNXHOSTSW.1.0-03900-LNXHOSTSW.0-1",
        "modem": "MPSS.DE.1.0-02593-OLYMPIC_GENALL_PACK-1",
        "tz": "TZ.FU.5.15-00043-OLYMPICAAAAANAZT-1",
        "tz_apps": "TZ.APPS.1.15-00031-OLYMPICAAAAANAZT-1",
        "wlan_hsp": "WLAN.HSP.1.1.3-00087.1-QCAHSPSWPL_V1_V2_SILICONZ_LITE-1"
    },
    "Metabuild_Info": {
        "Meta_Build_ID": "Olympic.LE.1.0.r1-00637-NBOOT.NEFS.PROD-1.513758.4",
        "Product_Flavor": "[None]",
        "Time_Stamp": "2022-10-05 07:02:53"
    },
    "Version": "1.0"
}
```

**Comment by KirkPerilloux** [comment]
Yes. Please.  Let me know how I can help.

**Comment by bkerler** [comment]
Without the firmware for the NTGX65, I don't see any chance to add/reverse the new algorithm, sorry.

**Comment by wojo** [comment]
> Without the firmware for the NTGX65, I don't see any chance to add/reverse the new algorithm, sorry.

I have a rooted unit running the latest firmware, I could try to extract something from the running image if that works. Do you know what you'll need from the running filesystem?

**Comment by bkerler** [comment]
I'd need the modem files (modem.mdt and modem.b*). How did you root the unit ?

**Comment by bkerler** [comment]
Actually, the more you can dump, the better. Maybe I can reverse the key for decrypting the firmware as well.

**Comment by bkerler** [comment]
For extracting the firmware, there might/should be a NetgearWebApp somewhere

**Comment by wojo** [comment]
@bkerler sent via email due to IMEI, etc

**Comment by bkerler** [comment]
Thanks. Do I assume correctly that the "new" codes started with 10.04.13.03 ?

**Comment by wojo** [comment]
@bkerler that's correct

**Comment by bkerler** [comment]
So, to let the others know, I do have a working solution for NTGX65_10.04.13.03 and upper. However due to abuse of the code by unlocker crews making money out of it and as netgear/sierra wireless is monitoring this repo I won't publish the solution, we don't need another cat vs. mouse problem. If you need a code to be generated, just contact me.

**Comment by infinitenewworld** [comment]
> So, to let the others know, I do have a working solution for NTGX65_10.04.13.03 and upper. However due to abuse of the code by unlocker crews making money out of it and as netgear/sierra wireless is monitoring this repo I won't publish the solution, we don't need another cat vs. mouse problem. If you need a code to be generated, just contact me.

Hi bkerler, do you know if it is possible to change the imei of the MR6550 yet? I'm currently on firmware 12.01.47. Thank you for any info you can provide.

**Comment by eddiebro7** [comment]
I can’t find your email to request challenge responses for 10.04.33.00 firmware on an Mr6500. I messaged on twitter but not sure if you check it; what’s a good email for you or whatever way to contact for this one modem?
