### ISSUE TITLE
Question: Can I dump from one phone and write on other phone?

### ISSUE THREAD

**Issue by keiem** [bkerler/edl#369]
Hello,

I have a pixel 3a that is locked in fastboot mode, and I have another pixel that runs fine.

I wonder, can I dump the emmc from the good phone and write this dump to the one with the locked fastboot with this edl tool?

**Comment by cuynu** [comment]
There is no firehose loader programmer file for Pixel phones. no hope

**Comment by bkerler** [comment]
No, this won't work for several reasons (root of trust, different hw keys, encryption, different hw)
