### ISSUE TITLE
Device is in unknown state

### ISSUE THREAD

**Issue by shiva2232** [bkerler/edl#37]
`# python3.8 edl.py --loader="../extracted/prog_firehose_ddr_ufs.elf" printgpt`
Qualcomm Sahara / Firehose Client (c) B.Kerler 2018-2020.
Library.utils - Using loader ../extracted/prog_firehose_ddr_ufs.elf ...
Library.utils - Waiting for the device
**.....Library.utils - Device detected :)
Library.utils - Mode detected: sahara
Device is in an unknown state**

**Comment by shiva2232** [comment]
Please help me to resolve this issue...

**Comment by bkerler** [comment]
what device did you try ? Looks like the programmer you are using doesn't match the pkhash or hardware.

**Comment by bkerler** [comment]
Please try commit 66f0e46 and report back if it works now.

**Comment by sytabaresa** [comment]
I have a similar issue when I try to execute any command:

```
$ ./edl.py reset # or other command
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x008110e102c80000 (MSM_ID:0x008110e1,OEM_ID:0x02c8,MODEL_ID:0x0000)
CPU detected:      "MSM8210"
PK_HASH:           0x2201bba0e6233f9bede802d8b87560cd0e9727d26e313f4b9abc2681c2a34a96
Serial:            0x038cf7b6

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (008110e102c80000_2201bba0e6233f9b_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}

```

It's a Motorola Moto E XT1021 in a Bricked state :'(

I don't know if it's an issue of the smartphone, but it's important to know how to fix it.

Thank you very much.

**Comment by SimonAstani** [comment]
Did anyone find the solution yet?

**Comment by bkerler** [comment]
The solution is to force reboot the device and use a correct loader for the device.

**Comment by GitHubQueenn** [comment]
> 

Any idea why the prog_emmc_firehose_8917_ddr.mbn that works for the MSM8937 UMX U693CL phone would not work for the newer U696CL model that uses the same 8937? Been at this for days, was able to unlock bootloader on the 696CL and fastboot is fully intact, but whether I use Linux EDL or Windows QFIL, I *always* get the saharsa [LIB] error that's above. For more info: https://forum.xda-developers.com/t/android-wont-show-up-as-usb-device-on-virtualbox-after-putting-phone-in-adb-edl-mode.4445079/post-86891179

**Comment by LiquidVenomX** [comment]
and how to do this??? ;-)
