### ISSUE TITLE
EDL Remove Xiaomi Account Redmi Note 8 (M1908C3JG)

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#370]
Hi guys, I've lost my Xiaomi Account Password... actually, I 've just wiped it and created another Xiaomi account and after that, I can’t recover the phone neither my account. I've flashed new ROM using this tool in EDL mode. Also erased persist, misc, frp (edl e persist, misc, frp). It seems to remove Xiaomi Account but after I initialize and configure internet connection, it’s back again. 
Is there a way to completely remove Xiaomi account while keeping a locked state bootloader? Or do you think that I should try to unlock bootloader and flash a new ROM so that I could work around this problem. 
I realize this has nothing to do with the actual EDL tool, but here is the place I trust most to have any information!
I understand if the team considers that the issue should be closed!
Just thank you guys, anyway.

**Comment by bkerler** [comment]
Sorry, out of scope of this project.
