### ISSUE TITLE
Issue with edl

### ISSUE THREAD

**Issue by umaryasin33** [bkerler/edl#372]
Hello! I am able to see the device id using UsbDkController -n.
Where do I enter the next commands like edl --serial. I tried in command prompt it shows not found. I am only looking to reset my device out of edl mode and need to use the edl --reset command though i dont know where to enter it. Any help would be appreciated. TIA

**Comment by THEBESTSZ** [comment]
> Hello! I am able to see the device id using UsbDkController -n. Where do I enter the next commands like edl --serial. I tried in command prompt it shows not found. I am only looking to reset my device out of edl mode and need to use the edl --reset command though i dont know where to enter it. Any help would be appreciated. TIA

did you manage to solve? I'm using windows too, only it doesn't enable "edl" commands when installing

**Comment by bkerler** [comment]
Due to issues with windows updates, usbdk currently fails to work.

**Comment by RealYukiSan** [comment]
@bkerler does that mean this tool no longer work in windows?
