### ISSUE TITLE
xiaoxin p11 pro 2021 does not scape edl after successful reset

### ISSUE THREAD

**Issue by ahenla** [bkerler/edl#374]
Hi

thank you for your hard work

i've been trying to scape my tablet Xiaoxin p11 pro 2021 form edl mode but even when the
resetting show success, the tablet is still in the same mode.

this is the log shown by the program.

[edl log.txt](https://github.com/bkerler/edl/files/10833616/edl.log.txt)

**Comment by bkerler** [comment]
For some devices, resetting won't work or will require usb cable to be removed.

**Comment by ahenla** [comment]
ohhh, ok, i understand, i'll try to find another way.
 Thank you for your reply.
