### ISSUE TITLE
Google Pixel 4a (5G) & AN0M Phone Help!

### ISSUE THREAD

**Issue by CE1CECL** [bkerler/edl#375]
Hello! I am trying to help a friend with the 2 bricked phones listed in the issue title, and found there were no loaders for those devices. So I got the boot loader image from google and uploaded the XBL file that was extracted in the image, and it says it uploaded successfully, but I run the command again, it still keeps saying it uploaded. I did the same for my dead screen SMT560-NU and it worked for me and put me in 9006 mode (keep in mind, no display, not enough power for MMC I believe, and there is one loader known for it) Here is the log for my device: 
```
root@HP-PAVILION-590:~/edl# lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 019: ID 1b1c:1b38 Corsair Corsair Gaming K70 RGB RAPIDFIRE Keyboard 
Bus 003 Device 020: ID 046d:c092 Logitech, Inc. G102/G203 LIGHTSYNC Gaming Mouse
Bus 003 Device 018: ID 1b1c:1b3b Corsair Corsair Gaming MM800 RGB POLARIS
Bus 003 Device 017: ID 1b1c:1b2c Corsair Gaming USB2.0 Smart Port
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 0bda:b00a Realtek Semiconductor Corp. Realtek Bluetooth 4.2 Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@HP-PAVILION-590:~/edl# lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 019: ID 1b1c:1b38 Corsair Corsair Gaming K70 RGB RAPIDFIRE Keyboard 
Bus 003 Device 020: ID 046d:c092 Logitech, Inc. G102/G203 LIGHTSYNC Gaming Mouse
Bus 003 Device 018: ID 1b1c:1b3b Corsair Corsair Gaming MM800 RGB POLARIS
Bus 003 Device 017: ID 1b1c:1b2c Corsair Gaming USB2.0 Smart Port
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 039: ID 05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)
Bus 001 Device 006: ID 0bda:b00a Realtek Semiconductor Corp. Realtek Bluetooth 4.2 Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@HP-PAVILION-590:~/edl# ./edl --loader=../BL_T560NUUEU1CRG1_CL14081424_QB19124359_REV00_user_low_ship_MULTI_CERT.tar/sbl1.mbn 
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader ../BL_T560NUUEU1CRG1_CL14081424_QB19124359_REV00_user_low_ship_MULTI_CERT.tar/sbl1.mbn ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x007060e100000000 (MSM_ID:0x007060e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "APQ8016"
PK_HASH:           0x98dc3fdde47b651f47f77620e7376d09905fc36d97cba5b560bcfef2f77df06a
Serial:            0x2655760a

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader ../BL_T560NUUEU1CRG1_CL14081424_QB19124359_REV00_user_low_ship_MULTI_CERT.tar/sbl1.mbn ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
root@HP-PAVILION-590:~/edl# ./edl --loader=../BL_T560NUUEU1CRG1_CL14081424_QB19124359_REV00_user_low_ship_MULTI_CERT.tar/sbl1.mbn 
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader ../BL_T560NUUEU1CRG1_CL14081424_QB19124359_REV00_user_low_ship_MULTI_CERT.tar/sbl1.mbn ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

^C.Traceback (most recent call last):
  File "/root/edl/./edl", line 391, in <module>
    base.run()
  File "/root/edl/./edl", line 299, in run
    conninfo = self.doconnect(loop)
  File "/root/edl/./edl", line 208, in doconnect
    time.sleep(1)
KeyboardInterrupt

root@HP-PAVILION-590:~/edl# lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 019: ID 1b1c:1b38 Corsair Corsair Gaming K70 RGB RAPIDFIRE Keyboard 
Bus 003 Device 020: ID 046d:c092 Logitech, Inc. G102/G203 LIGHTSYNC Gaming Mouse
Bus 003 Device 018: ID 1b1c:1b3b Corsair Corsair Gaming MM800 RGB POLARIS
Bus 003 Device 017: ID 1b1c:1b2c Corsair Gaming USB2.0 Smart Port
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 040: ID 05c6:9006 Qualcomm, Inc. QHSUSB__BULK
Bus 001 Device 006: ID 0bda:b00a Realtek Semiconductor Corp. Realtek Bluetooth 4.2 Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@HP-PAVILION-590:~/edl# lsusb
Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 019: ID 1b1c:1b38 Corsair Corsair Gaming K70 RGB RAPIDFIRE Keyboard 
Bus 003 Device 020: ID 046d:c092 Logitech, Inc. G102/G203 LIGHTSYNC Gaming Mouse
Bus 003 Device 018: ID 1b1c:1b3b Corsair Corsair Gaming MM800 RGB POLARIS
Bus 003 Device 017: ID 1b1c:1b2c Corsair Gaming USB2.0 Smart Port
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 0bda:b00a Realtek Semiconductor Corp. Realtek Bluetooth 4.2 Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@HP-PAVILION-590:~/edl# 
````
Any help is appreciated! Thanks!

**Comment by CE1CECL** [comment]
@infr-automation This is one of the devices (the samsung in the log) but its the same for the ticwatch pro (except the id and its APQ8009w rather than APQ8016), wearable btw. I have since found out that the pixel 5 & 5a are composable with the XBL to the 4a and 4a 5g and both ways. On the 4a 5g, it reboots when i upload its 4a 5g file but ill try to upload the 5 or 5a file and see what happens different.

**Comment by CE1CECL** [comment]
> For the T560NU this is a full dump image without the userdata system and cache [Dump T50NU (without userdata)_2_2.zip.zip](https://github.com/bkerler/edl/files/11128624/Dump.T50NU.without.userdata._2_2.zip.zip) [Dump T50NU (without userdata)_2.zip.zip](https://github.com/bkerler/edl/files/11128626/Dump.T50NU.without.userdata._2.zip.zip)

How did you make this in your case? Did you enter my 9006 method or use firehose?

**Comment by CE1CECL** [comment]
> I am even more confused, I need to get the reference reading material for 9006 and Streaming.
> 
> I think Qualcomm 9006 emmc Download mode is not Samsung Odin Download mode
> 
> The logs are only from T560NU ? What are the logs from the two phones?

It isnt a samsung mode but it mounts as a MMC disk in linux directly, which you can use like a usb flash stick. The google pixel did upload its image as said above fine, it just reboots back into 9008 and it says success rather than 9006. Still need help entering 9008 mode on the ArcaneOS phone though as the cable isnt working for them

**Comment by CE1CECL** [comment]
> The full dump was made by an unknown repair hero, probably by methods of jtag and emmc chip-off most probably with easyjtag. The log in the archive is probably from such a tool.

Its worth mentioning the MSM8909w AMSS leak i found online works as well with my watch, but the loader id is the same so yeah. I saw you found the samsung leak on sizeof.cat but that seems to have been a incomplete leak in terms of it building. The MSM8909, MSM8909w, & MSM8916 all have at least 5 things missing from it needed to build (or more).

**Comment by CE1CECL** [comment]
> I suspected those missing sources are in the devkits when you register in the communities or purchase dev board.

True but I cannot find it anywhere and the leaks were from 2016 at most (for the older phones anyways)

**Comment by CE1CECL** [comment]
[3ef72a02fb931be15408bb63603588faeafeb09f07d567c04a3fdc7e9fdd7e2faab10f954c89a682afe1cd46f8482c6c.zip](https://github.com/bkerler/edl/files/11130453/3ef72a02fb931be15408bb63603588faeafeb09f07d567c04a3fdc7e9fdd7e2faab10f954c89a682afe1cd46f8482c6c.zip)

**Comment by CE1CECL** [comment]
@infr-automation do you still have the SM-T560NU? if so, you mind flashing twrp onto it? booting into twrp and on pc run ```adb shell```
then type on the prompt ```reboot edl``` if it doesnt work try ```adb reboot edl``` and upload the sbl1.img and see if it works with ```edl --loader=sbl1.img``` and run ```lsusb``` and show me that. 
[samsung-gtelwifiue.zip](https://github.com/bkerler/edl/files/11130473/samsung-gtelwifiue.zip)
you can also boot twrp and on the twrp terminal builtin run ```reboot edl``` if you want but you need the pc anyways to upload sbl1.img and the lsusb output

**Comment by CE1CECL** [comment]
> Do you have at least fastboot on the pixel4a 5g ? And the an0m is the same hardware 4a 5g ? It would be nice of them since their ops is over, to release the sources and stuff so we can recycle the hardware. As well as to be compliant with software law.
> 
> Unless they can guarantee the precious metals forever, they better do their job what we pay them taxes for in the first place. 😁😁😁

We actually bricked the 5g phone using fastboot and now we aren't able to access it. For the an0m phone, the friend has more than one device and can access fastboot but I am currently unable to enter edl mode on the an0m's. I did something like adb OEM edl and it said it wasn't allowed.

**Comment by CE1CECL** [comment]
> Well so it could be that the PID is incorrect the important thing is which protocol the device is speaking right now.
> 
> It's very interesting how you uploaded sbl1.mbn TWICE in your example to get to 9006 mode ?
> 
> This is also something I need to doublecheck with my N976V
> 
> I suspect there are other bugs as well creating differences from documentation, sources, expectations, and hardware behavior.
> 
> Can we put Wireshark on the USB port and watch some USB packets? I forgot how I did that in the past maybe some other software.

I actually did lsusb to show before and after but uploaded it once and it changed the mode right away (trying to upload 2 times would freeze the thing b/c its not in a communicable mode but you only do it 1 time.).

**Comment by bkerler** [comment]
I don't expect any edl loaders to leak for the google pixel devices in any near future. So I recommend to close this issue.

**Comment by CE1CECL** [comment]
Okay
