### ISSUE TITLE
very important

### ISSUE THREAD

**Issue by KING-ENGMOATH** [bkerler/edl#377]
I need this file to use for a private work who is willing to pay whatever amount is reasonable

CpuID     : 0x000460E1
HW_ID     : 0x460E100040000
CpuHASH   : 0x7087BE6BE412881DFE6E7EAFBF45A75059C5D35E2434CF7558B444E93BD10AE4

MSM_HW_ID: 0x000460E1
OEM_PK_HASH: 0x7087BE6BE412881DFE6E7EAFBF45A75059C5D35E2434CF7558B444E93BD10AE4
SBL SW Version: 0x00000003

send me  moad20022020@gmail.com

**Comment by bkerler** [comment]
Sorry, you should ask that in the loaders repository, not here.
