### ISSUE TITLE
Spec file for pyinstaller

### ISSUE THREAD

**Issue by biden2020prez** [bkerler/edl#378]
Hi. @bkerler. Thanks for this amazing tool. Would you be interested in creating a spec file so we can make a pyinstaller executable? Or if you give me some details about what needs to be included I can try to make one myself

**Comment by bkerler** [comment]
Hi, sure. I will soon update the repo and the. i'll try to add the pyinstaller spec as well.

Am 8. März 2023 19:58:12 MEZ schrieb Biden2020prez ***@***.***>:
