### ISSUE TITLE
Question about loaders for LG-made Google Pixels

### ISSUE THREAD

**Issue by kjh96** [bkerler/edl#383]
Hi bkerler, thank you for your work. 
In this comment: https://github.com/bkerler/edl/issues/204#issuecomment-997414363 
you said that there haven't been any loaders leaked or released for Google Pixels, **except** LG-based ones.

I've searched for a while, and couldn't find anything about **any** Pixel loaders being available at all.
I'm curious, do you recall which loaders or which LG Pixel models you were referring to? Also, I thought the only one made by LG is the Pixel 2 XL.

**Comment by bkerler** [comment]
Actually I was referring to the nexus 5x. There were other htc google leaked loaders as well afair. The pixel 4 and 4a loaders that have leaked recently are a scam and in fact xiaomi auth loaders.
