### ISSUE TITLE
add option for this 

### ISSUE THREAD

**Issue by satyamisme** [bkerler/edl#384]
## Device Details

- Model: MDM9x5x
- Configuration:
  - id=10 
  - addr=079b0000 
  - udflag=1 
  - ctrl=0 
  - msmid=0950 
  - msmid=0951 
  - sahara=1 
  - nprg=NPRG9x55-ac98p.mbn 
  - enprg=ENPRG9x55.mbn 
  - device=nand

## Issue Details

- The device works only in download mode with SB3.0
- Attempting to dump firmware fails as the Sahara protocol is failing.
- Seeking guidance on using the qdload patch with EDL tool or if it's automatic.

**Comment by bkerler** [comment]
you need to put the device into 9008 mode, not streaming mode, then the enprg loader does work after it's patched. You need to patch it yourself. Download mode isn't supported as only edl is supported.
