### ISSUE TITLE
Library.sahara - bytearray index out of range

### ISSUE THREAD

**Issue by 44yu5h** [bkerler/edl#387]
I'm trying to run the EDL tool on windows. With python 3.11 
On running any EDL command this is the error I'm getting:

> PS C:\Users\Ayy\Downloads\Exit EDL mode in Windows\edl-3.1\edl-3.1> python ./edl.py reset
> Qualcomm Sahara / Firehose Client V3.1 (c) B.Kerler 2018-2021.
> Library.utils - Trying with no loader given ...
> Library.utils - Waiting for the device
> Library.utils - Device detected :)
> Library.sahara - bytearray index out of range
> Library.sahara - bytearray index out of range
> Library.utils - Unknown mode. Aborting.

Is this a bug or something to do with my system?

**Comment by 44yu5h** [comment]
The Latest version just doesn't reply: 
```
PS C:\Users\Ayy\Documents\edl> python ./edl reset
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
PS C:\Users\Ayy\Documents\edl>
```
And 3.1 version:
```
PS C:\Users\Ayy\Downloads\edl-3.1> python ./edl.py printgpt
Qualcomm Sahara / Firehose Client V3.1 (c) B.Kerler 2018-2021.
Library.utils - Trying with no loader given ...
Library.utils - Waiting for the device
Library.utils - Device detected :)
Library.sahara - bytearray index out of range
Library.sahara - bytearray index out of range
Library.utils - Unknown mode. Aborting.
PS C:\Users\Ayy\Downloads\edl-3.1> python ./edl.py reset
Qualcomm Sahara / Firehose Client V3.1 (c) B.Kerler 2018-2021.
Library.utils - Trying with no loader given ...
Library.utils - Waiting for the device
Library.utils - Device detected :)
Device is in Sahara error state, please reboot the device.
Library.utils - Mode detected: sahara
Sahara in error state, resetting ...
```

**Comment by 44yu5h** [comment]
> 

So the only fix is to use Linux?

**Comment by archislove-archislife** [comment]
Hi, sorry to revive this issue, but im using arch linux, a nokia 6300 4G and having the same issue, i've installed python 3.7 and the 3.9 version too and none of them work, even tried using `python` instead of `python3` as is recommended in the [documentation im following](https://ivan-hc.github.io/bananahackers/Nokia%208000%204G%20%20Nokia%206300%204G%202020.html) and still the problem persists. I'm using the `python3 edl.py w recovery imgmbn/recovery-8110.img --loader=imgmbn/8k.mbn` command as the guide says

**Comment by 44yu5h** [comment]
Hi @archislove-archislife, I think your device is in "Qualcomm HS-USB Diagnostics **900E**" mode you have to bring it to **9008** (EDL mode) before running commands. There are several videos out there demonstrating the same 

You can check the device mode by `lsusb` command in terminal.

P.S.  I did it by shorting the test points. But in my case I can only run a command once and then despite showing 9008 mode it doesnt work for the second command I enter. So I have to disconnect, reconnect and then again put it into 9008 mode and then run the command. Just saying in case the same happens to you.

**Comment by archislove-archislife** [comment]
> 

thx for replying <33, so my output of `lsusb` is `Bus 002 Device 006: ID 05c6:9039 Qualcomm, Inc. Nokia 6300 4G`, i think its on 9039 mode (which i don't really know what it means), anyway i use `adb reboot edl` and my device now appears in `lsusb` as `Bus 002 Device 007: ID 05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)` which i think is what you mean, then i try running the command, even from version 3.1 and it outputs `Library.sahara - [Errno 2] No such file or directory: '~/nokia63004g/edl-3.52.1/Loaders'`. From version 3.52.1: `sahara - [LIB]: [Errno 2] No such file or directory: '~/nokia63004g/edl-3.52.1/Loaders'`, even if i try specifying the file too, it outputs `sahara - [LIB]: [Errno 2] No such file or directory: '~/nokia63004g/edl-3.52.1/Loaders/8k.mbn'` i don't know if the file im using is the wrong one or what is happening, but i really need to root this phone

**Comment by 44yu5h** [comment]
I think the edl you are using lacks some files. Fresh setup edl as explained in the Readme of the repo. It should work

Here:
```
sudo pacman -S android-tools python python-pip git xz
sudo pacman -R modemmanager

sudo systemctl stop ModemManager
sudo systemctl disable ModemManager
sudo apt purge ModemManager


git clone https://github.com/bkerler/edl.git
cd edl
git submodule update --init --recursive
sudo cp Drivers/51-edl.rules /etc/udev/rules.d
sudo cp Drivers/50-android.rules /etc/udev/rules.d
python3 setup.py build
sudo python3 setup.py install
```

**Comment by archislove-archislife** [comment]
ok, im gonna try that again and let u know how it goes

**Comment by archislove-archislife** [comment]
Hi, sorry for the late reply but tried doing exactly what the git guide said and installed everything again and now the output is this, im gonna try and fix this, but if you have any solutions let me know. 
` python edl.py w recovery ~/nokia63004g/imgmbn/recovery-8110.img --loader= ~/nokia63004g/imgmbn/8k.mbn
Traceback (most recent call last):
  File "/home/user/nokia63004g/edl-3.52.1/edl.py", line 122, in <module>
    from edl.Config.usb_ids import default_ids
  File "/home/user/nokia63004g/edl-3.52.1/edl.py", line 122, in <module>
    from edl.Config.usb_ids import default_ids
ModuleNotFoundError: No module named 'edl.Config'; 'edl' is not a package`

**Comment by archislove-archislife** [comment]
still same output: 
` python3 edl w recovery ~/nokia63004g/imgmbn/recovery-8110.img --loader=~/nokia63004g/imgmbn/8k.mbn
No module named 'Cryptodome'
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Using loader ~/nokia63004g/imgmbn/8k.mbn ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x009600e100420029 (MSM_ID:0x009600e1,OEM_ID:0x0042,MODEL_ID:0x0029)
CPU detected:      "MSM8909"
PK_HASH:           0x338d702c38aab61291adcf854dd02bff4d9ae987f4221cd8b019001db8d4017b
Serial:            0x22de5391

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader ~/nokia63004g/imgmbn/8k.mbn ...
sahara
sahara - [LIB]: [Errno 2] No such file or directory: '~/nokia63004g/imgmbn/8k.mbn'`
re installed it a bunch of times and i have no clue if im using the right syntax to specify the loader or not ;-;

**Comment by archislove-archislife** [comment]
ok so now im stuck with this: 
```
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader Loaders/qualcomm/factory/8k.mbn ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
```
i dont know what to do or if im using wrong files for this, help :(

**Comment by 44yu5h** [comment]
Hi @archislove-archislife, I don't understand the loader that you are using. Are you following [this guide](https://sites.google.com/view/bananahackers/devices/nokia-8000-4g-nokia-6300-4g-2020)?

Also there is another similar issue #88 you might want to look at this. I don't know what 3.0 tag means but [this](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcenterhost.doc/GUID-05323758-1EBF-406F-99B6-B1A33E893453.html) might help.

**Comment by archislove-archislife** [comment]
Yes i was following that guide but it didn't work for me :(

I appreciate a bunch, i will follow what that person did and let you know how it goes <3

about "tag", I think it may refer to the release #3.0 of edl, either way if that doesn't work im gonna try the link [that](https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.vcenterhost.doc/GUID-05323758-1EBF-406F-99B6-B1A33E893453.html) link you sent me and see what it says :))
