### ISSUE TITLE
xml parse error

### ISSUE THREAD

**Issue by gompa** [bkerler/edl#39]
when trying to load an xml file it errors out, shouldnt this just be data instead of bytes data ? 
https://github.com/bkerler/edl/blob/524b2639fe7cc7a2203ca50326d7253824d9fb66/Library/firehose.py#L99

**Comment by bkerler** [comment]
No, that's how it should be. Can you upload a full log.txy of what you are trying using --debugmode option ?

**Comment by bkerler** [comment]
Can you please try commit 2908728 and report if it works ?
