### ISSUE TITLE
Python has stopped working

### ISSUE THREAD

**Issue by ansh-thecrazy** [bkerler/edl#394]
Started getting below error after installed lib_win32 driver -

![image](https://user-images.githubusercontent.com/122473790/234366657-9e1f0083-5343-49f7-9fbf-add09c845bf9.png)

I was earlier using Python 3.11, thought it is a python issue. Installed Python 3.9 but still getting the same error.

Also, getting below error(s) while running --debugmode - 

![image](https://user-images.githubusercontent.com/122473790/234367625-037c2252-7600-4604-bbf9-568238952b26.png)

Can someone please help in resolving this error. Thanks in advance.

**Comment by 44yu5h** [comment]
Is this you? 
https://stackoverflow.com/questions/47828821/python-has-stopped-working

See what Windows event viewer says

**Comment by ansh-thecrazy** [comment]
Couldn't find anything in the event viewer. Re-ran the command and found below issue. Yes I am using windows.

_Faulting application name: python.exe, version: 3.9.9150.1013, time stamp: 0x6192a38c
Faulting module name: libusb-1.0.dll, version: 1.0.24.11584, time stamp: 0x5fd32f16
Exception code: 0xc0000005
Fault offset: 0x0000000000007726
Faulting process id: 0x3580
Faulting application start time: 0x01d978395ab0f552
Faulting application path: C:\Users\******\AppData\Local\Programs\Python\Python39\python.exe
Faulting module path: C:\Users\******\edl\edlclient\Windows\libusb-1.0.dll
Report Id: 182ce76b-5fd3-4c09-908a-6583f632a2f9
Faulting package full name: 
Faulting package-relative application ID:_

**Comment by 44yu5h** [comment]
> 0xc0000005 means 'memory access violation' error. The related info seems to indicate this happens when python is processing arrays.

You can try to troubleshoot by searching for python Exception code: 0xc0000005
There are many solutions. See what works for you

**Comment by ansh-thecrazy** [comment]
@44yu5h  Thanks. I downloaded the libusb-1.0.dll from https://[libusb](https://libusb.info/).info/ and pasted it in 

_~edl\edlclient\Windows_ location

Now it is running fine so it was the driver but it's fixed and gave me the below output. :) Thanks for pointing me out to the event viewer.


![image](https://user-images.githubusercontent.com/122473790/234575017-0d4c6bf7-8843-4537-b00c-6fec68c63424.png)

**Comment by 44yu5h** [comment]
@ansh-thecrazy Very Welcome. You may close the issue ;)

**Comment by ansh-thecrazy** [comment]
I was running the command - 

python edl printgpt 

It wasn't showing any activity on the system. My system restarted due to low battery and I have started getting a different error for mode now - 

![image](https://user-images.githubusercontent.com/122473790/234592600-6e52b013-8d67-42fd-8cb6-93f032269a06.png)

Any idea how to fix this?

**Comment by ansh-thecrazy** [comment]
Thanks! Aayush once again. 

So I was able to sort it out right after I posted the issue. Reinstalling the driver didn't fix the issue.

The issue was with the mode device was in. I pressed "Vol Up + Power Key" for about 30 seconds and re-plugged the device. 

**The error was gone.**

Now I am facing a different issue :) I am trying to extract the data from userdata partition. I am able to start by passing the loader file and it starts extracting the data but somehow it keeps getting stuck.

The first time I ran, it got stuck at 0.4%
Second time at 16.4%
Currently, it's stuck at 1.4%

Not sure if this is normal.. If I should leave the laptop as is and it will complete? Or should I just kill and restart the process again?

I wish there were some YT videos around the usage of this tool :) I can create one for my use case once I get success. 👍

**Comment by ansh-thecrazy** [comment]
I've managed to run past the recovery command and was able to recover the userdata folder.

However, I am trying to open the media folder in it and it's showing gibberish characters. I am unable to extract these files. Could this be a charset issue? Any leads on how to resolve or extract the data. Below is how the data looks, I am trying to open it in powerISO tool -

![image](https://user-images.githubusercontent.com/122473790/234764141-f0dd16d0-a76b-468e-84fb-5f524559d8e8.png)

**Comment by 44yu5h** [comment]
Hi, Sorry for a late reply.

> The first time I ran, it got stuck at 0.4%
Second time at 16.4%
Currently, it's stuck at 1.4%
>Not sure if this is normal.. If I should leave the laptop as is and it will complete? Or should I just kill and restart the process again?

This isn't normal. However, I don't know for sure what the issue could be

>However, I am trying to open the media folder in it and it's showing gibberish characters. I am unable to extract these files.

Did you have a screen lock? They seem to be encrypted. It is recommmended to remove the screen lock before tweaking.
Do you have TWRP or adb? Can you access these?

**Comment by 44yu5h** [comment]
>The phone had stopped working suddenly.

Are you trying to recover the data?

What stage are you at exacty? 
Can you boot to recovery or fastboot? (assuming no)
You can go to EDL mode so did you try flashing stock rom? What is your phone's model?

> I've been patient with the phone for past six months to find a solution. laughing

Lol I TOTALLY feel you. I'd been carrying my Redmi Note 4 for 3 and a half years. Still couldn't fix it. It is stuck in edl mode. I'm trying to listen to UART but I dont have a 3.3v to 1.8v converter yet :')

**Comment by ansh-thecrazy** [comment]
> Are you trying to recover the data?

Yes



> What stage are you at exacty?
Was just able to create userdata.bin yesterday.

> Can you boot to recovery or fastboot? (assuming no)

No

> You can go to EDL mode so did you try flashing stock rom? What is your phone's model?

Wouldn't flashing stock format the device and I'll lose the data?

I'm just trying different things from different forums at this moment. Just need to figure out a way to recover the data. I'm not too worried about the phone working 😅

**Comment by 44yu5h** [comment]
Hmm.. With condition like that it may be a tough thing to recover the data. You do have access to /media/0/ so you should ask on XDA forum since I don't know much about decrypting the data. It should be possible since you know the password but I'm afraid I won't be able to help any further :/

**Comment by 44yu5h** [comment]
You can if you go deep enough to know exactly what you want to know if you want to. Pull logs or listen to UART (displays boot logs while starting) on interrupting boot via UART you can get into shell
dig xda it has everything

**Comment by ansh-thecrazy** [comment]
I'm very new to this and don't know how to pull logs or listen to UART. Can we connect somewhere else? I'm on insta with the username - pro.punjabi
Don't wanna keep spamming this space up. ;)

**Comment by 44yu5h** [comment]
Honestly, if Android/tech is not your field then it will not be worth wasting so much time before it. You can instead pay to get the data back.
or you can send it to a youtuber, @PhoneRepairGuru there's one more trustable but i can't remember the name. they do it at cheap because they earn from yt too

**Comment by bkerler** [comment]
Closing this issue now.

**Comment by ansh-thecrazy** [comment]
How do I decrypt the file?
