### ISSUE TITLE
Question about capstone and keystone engine

### ISSUE THREAD

**Issue by realivanjx** [bkerler/edl#4]
Hi,

First of all thanks for this tool it helps me to flash my phones. The next thing i want to do is to implement this in C# so i can understand this, python and c# better. My question is what is the purpose of capstone and keystone engine for this program?

Thanks

**Comment by bkerler** [comment]
Actually it's being used for other modules that are non-public. You may comment them out :)

**Comment by realivanjx** [comment]
Ok thanks for letting me know.
