### ISSUE TITLE
Trying to use 'oemunlock'  on TMO OP8T

### ISSUE THREAD

**Issue by kylestanevich** [bkerler/edl#40]
I am trying to use the 'oemunlock' command on a t-mobile oneplus 8t (+ 5g). I get the same error with all 3 firehose.elf files from the .ops file (from msmdownloadtool). Also tried to use the fhloaderparse.py but get the same error. See the output below.

> edl.py modules oemunlock enable --loader=prog_firehose_lite.elf

Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3 (c) B.Kerler 2018-2020.
Library.utils - Using loader prog_firehose_lite.elf ...
Library.utils - Waiting for the device
.....Library.utils - Device detected :)
Library.utils - Mode detected: sahara
Device is in EDL mode .. continuing.
Library.sahara -
------------------------
HWID:              0x000c30e100514d6d (MSM_ID:0x000c30e1,OEM_ID:0x0051,MODEL_ID:0x4d6d)
PK_HASH:           0x????????
Serial:            0x????????
SBL Version:       0x00000000

Library.sahara - Using loader prog_firehose_lite.elf ...
Library.sahara - Unexpected error on uploading, maybe signature of loader wasn't accepted ?
unpack requires a buffer of 4 bytes
Traceback (most recent call last):
  File "C:\Users\????\Downloads\phonestuff\edl-master\edl.py", line 363, in <module>
    main()
  File "C:\Users\????\Downloads\phonestuff\edl-master\edl.py", line 319, in main
    if streaming.connect(1):
  File "C:\Users\????\Downloads\phonestuff\edl-master\Library\streaming.py", line 624, in connect
    if resp[1] != 2:
IndexError: bytearray index out of range

**Comment by bkerler** [comment]
As it says, error on uploading, your loader doesn't seem to fit. Furthermore, the factory loader of OP8T only allows reading but not writing of partitions. That's the same for all newer oneplus, oppo and xiaomi devices.

**Comment by bkerler** [comment]
Also, you forgot to set memory to ufs. The correct usage would be for reading :
./edl.py r boot boot.img --memory=ufs

**Comment by kylestanevich** [comment]
Sorry about that. I didn't know that it was read only.

**Comment by bkerler** [comment]
Maybe patch command still works. Please try the latest commit.
