### ISSUE TITLE
Questions about qfil and sparse images

### ISSUE THREAD

**Issue by randalthor17** [bkerler/edl#403]
Sorry if I'm being dumb, but i have two questions:
1. Is there a way to dump partitions as sparse files?
2. When I flash roms made using msmdownload tool through the 'edl qfil' mode, the sparse userdata partition takes almost 7 hours to flash. Is there a way to speed it up?
Thanks in advance.

**Comment by bkerler** [comment]
Hi,
1. no
2. not sure, but I doubt it can be made any faster. 7 hours however does sound like a lot of time, which is pretty unusual.

**Comment by Weissnix4711** [comment]
5 minutes sounds quite reasonable. I think this may have something to do with #347.

Is it possible that were padding the image out and writing nulls to the entire rest of the partition, instead of just writing as much data as necessary? I don't have the time to figure out how this project is actually working, just guessing.

**Comment by RenateUSB** [comment]
7 hours is ludicrous.
If you are ever having an issue with a sparse file, just expand it on the desktop using (one of those) simg2img utilities.
Then you can see if there is a problem there and you can flash it as a flat file.

**Comment by randalthor17** [comment]
Probably this is related to the issue that Weissnix mentioned, as the speed drops to .5 Mbps-ish for me too.

**Comment by randalthor17** [comment]
upon further inspection, the stock image flasher (msm8x39download) actually reboots the phone to bulk storage mode (9006 mode) and then flashes the images. i think this is why the flasher is faster than qfil.

**Comment by randalthor17** [comment]
ig im going to close this.
