### ISSUE TITLE
Everything is fine! But stuck in EDL mode 🙂

### ISSUE THREAD

**Issue by 44yu5h** [bkerler/edl#405]
I can flash successfully through both the Redmi Flash tool and this awesome edl tool several times with several versions of the stock ROM. But I'm kind of stuck in EDL mode. It says `firehose - Reset succeeded.` But all it does is goes from 9008 mode to 900E (crash mode). Long pressing the power key has no effect. Does this mean I might have screwed my hardware? 

I tried erasing all the partitions and flashing again (`edl qfil`), didn't help.

I'm using this loader but that shouldn't be an issue.. https://github.com/bkerler/edl/issues/281

Any insight on this will be very appreciated.

**Comment by RenateUSB** [comment]
900e says that it is unhappy when booting.
It's not so much stuck in EDL as just failing to run.
A full raw backup might have been useful.

**Comment by 44yu5h** [comment]
@RenateUSB Hi, Thanks for replying. 
Could you point out something I should be looking for if possible or doing? Because I'm practically totally stuck with this. 
Is it the hardware or something obvious to you? 

Thanks!
(are you the same Renate from XDA? :)

**Comment by bkerler** [comment]
900e means that the sbl/lk is broken/damaged. The only option to get the device back to 9008 mode is to short dat0 or clk of emmc to ground. Make sure to disconnect the battery first so that it is powerless. Once you see 9008 port, remove the short immediately.

**Comment by 44yu5h** [comment]
@bkerler Hi, thanks for replying. 
I can get into 9008 and flash successfully (I think you missed, I mentioned it above)

But everytime I try to boot it. It doesn't boot up. If this issue in any way familiar to you.. your help would be great
