### ISSUE TITLE
Supported device list

### ISSUE THREAD

**Issue by EIREXE** [bkerler/edl#407]
Hello, I make this issue to ask if there's any list of supported devices, I succesfully used this project to unlock the bootloader of my Aquaris X5 succesfully, which was nice, thank you for the hard work.

I have obtained a xiaomi poco x3 nfc that I want to unlock the bootloader of, since I have to open it anyways to replace a bulging battery I was wondering if the chip (Snapdragon 732G) is supported by this project for this purpose, otherwise I will just wait the two weeks xiaomi wants.

I saw that the README talks about the secure loader on SDM660 devices, does this affect the SM7150-AC on the x3 nfc too?

Cheers.

**Comment by bkerler** [comment]
It affects all newer devices with either VIP programming or custom implementations as Xiaomi EDL Auth. A supported device list doesn't make a lot of sense as all qualcomm devices are supported as long as a working firehose loader does exist.

**Comment by EIREXE** [comment]
> It affects all newer devices with either VIP programming or custom implementations as Xiaomi EDL Auth. A supported device list doesn't make a lot of sense as all qualcomm devices are supported as long as a working firehose loader does exist.

I see, thanks for the info

**Comment by AgentSteel** [comment]
@EIREXE Hello, may I ask how you successfully unlocked your Aquaris X5? (Which command did you use?) 
Thank you very much!
