### ISSUE TITLE
"wheel" is missing from requirements.txt

### ISSUE THREAD

**Issue by rptb1** [bkerler/edl#41]
Fresh Debian 10 minimal.  Installed sudo, gcc, python3, python3-venv, adb, fastboot, liblzma-dev, python3-dev.  But then `pip install -r requirements.txt` failed making bdist_wheel.  https://stackoverflow.com/a/44862371 revealed why, and `pip install wheel` fixed things.

So I suggest you add wheel to requirements.txt.

And possibly python3-dev to your apt package list in the readme.

Thanks!

**Comment by rptb1** [comment]
For what it's worth I was able to get edl.py talking to my phone from macOS 10.14.  Of course I ignored the `apt` commands, and the only extra step was `brew install libusb`.

**Comment by bkerler** [comment]
Thanks ! I will update the requirements

**Comment by bkerler** [comment]
Please verify if commit bea898d is fine for you :)
