### ISSUE TITLE
telnetlib is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by jedis00** [bkerler/edl#410]
> E:\edl\edlclient\Tools\sierrakeygen.py:11: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13
  from telnetlib import Telnet

telnetlib to be replaced by telnetlib3, Exscript

**Comment by bkerler** [comment]
Solved with commit [ec27ffb](https://github.com/bkerler/edl/commit/ec27ffb4aa50d962944a75084c454dbc2b4435ea)
