### ISSUE TITLE
Support for MBN programmer

### ISSUE THREAD

**Issue by evilpan** [bkerler/edl#42]
It seems that fhloaderparse.py now only recognize ELF programmers, however some of the devices (Nexus 5/6p, OnePlusX, etc.) use the old MBN loader, should we add it for backward compability?

**Comment by bkerler** [comment]
Sure, feel free to add a commit ;)

**Comment by bkerler** [comment]
Support added with commit e1d0000 :)
OnePlusX is unfused, thus it will only work for fused loaders like Nexus5/6p.
