### ISSUE TITLE
Please add support New device Realme - GT 2 (Porsche)

### ISSUE THREAD

**Issue by Saikatsaha1996** [bkerler/edl#422]
Device Realme RMX3312 (Realme GT2]

I am trying to take backup.. my device not bricked.. but want to take backup partitions..
But unable to take..
Help wanted..

**Comment by Saikatsaha1996** [comment]
Hello I want one help.. can you help?

My device is okay.. not bricked.. but I want to take backup for feature.. is it okay?


`edl gpt . --genxml --memory=ufs` ?

And if my device is bricked then can I unbrick with this backup via edl ?

**Comment by Saikatsaha1996** [comment]
Is it possible for help? Trying to backup my device..
![IMG_20231009_132226](https://github.com/bkerler/edl/assets/72664192/2a3097e3-1850-432f-9286-230f92709d82)

**Comment by Saikatsaha1996** [comment]
```
------------------------

HWID:              0x001350e100510000 (MSM_ID:0x001350e1,OEM_ID:0x0051,MODEL_ID:0x0000)

CPU detected:      "lahaina"

PK_HASH:           0xd8e3b5a8dada006de3600d3489af632f62511e17bc2f0834ccd8855294b3eaea5806184aac7bf6fd5def121311a5ff49000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Serial:            0xde952c21
```

Realme GT 2 (Porsche)

**Comment by Saikatsaha1996** [comment]
Any solution available?

**Comment by Saikatsaha1996** [comment]
Some how I found no auth firehs file .. but I am getting error
`DeviceClass - [LIB]: Time out`

![IMG_20231013_213235](https://github.com/bkerler/edl/assets/72664192/62dbff8b-4dff-49a7-b2ff-c467003b758f)

**Comment by bkerler** [comment]
I don't see any real error .. What happens when it tries to read the first storage sector ? Maybe --memorytype=emmc is needed

**Comment by Saikatsaha1996** [comment]
> I don't see any real error .. What happens when it tries to read the first storage sector ? Maybe --memorytype=emmc is needed

My device actually ufs device..

This is log
[log_20231014161337.txt](https://github.com/bkerler/edl/files/12904590/log_20231014161337.txt)

**Comment by Saikatsaha1996** [comment]
> I don't see any real error .. What happens when it tries to read the first storage sector ? Maybe --memorytype=emmc is needed

Any help possible please? Even unable to backup with qfil
[port_trace.txt](https://github.com/bkerler/edl/files/12912234/port_trace.txt)
