### ISSUE TITLE
I have unknown chiness phone that stuck in edl mode

### ISSUE THREAD

**Issue by tineprogramming** [bkerler/edl#43]
Is ir possible this program can find the right programmer for my cpu ? I have qualcomm sdm636 but I tried all the programmer and it doesn't work

**Comment by bkerler** [comment]
Can you share your msmid and pkhash ?

**Comment by tineprogramming** [comment]
![image](https://user-images.githubusercontent.com/18547587/104581888-c75dec00-5691-11eb-91a7-a97bf8cc7352.png)
Here it is
HWID:              0x000cc0e101300002 (MSM_ID:0x000cc0e1,OEM_ID:0x0130,MODEL_ID:0x0002)
PK_HASH:           0xd1977a4e726afda9dc0e0ceab26c2bd0758a330e5d2acfee6803390642492e6c
Serial:            0x32a5b2c5

Thank you.

If you really can help will be much appreciated.

**Comment by bkerler** [comment]
Thx. the oem_id is unknown to me. The device is an SDM636. Do you have any labels on the phone ? Can you upload a picture ?
Unfortunately you will need the specific loader as the device is fused.

**Comment by tineprogramming** [comment]
I have amazon link. 
https://www.amazon.com/dp/B07YDVNHH7/ref=cm_sw_r_cp_apa_i_X6eaGb6CTTTJ9

I confused the cpu model as on the recovery mode said it sdm660. So I should try to find sdm636 ?

**Comment by bkerler** [comment]
You need a specific signed loader for this device. Others won't work.
https://shop.hikaritv.net/shopping/commodity/plala/5410200277/

**Comment by tineprogramming** [comment]
It's needed to be leak from the factory then. Not just any loader from the same cpu right. Why it has to be signed loader though.

**Comment by bkerler** [comment]
Don't think anyone has this loader, so I'm closing this issue for now. If I find a loader for this device, I will let you know.
