### ISSUE TITLE
Unexpected error on uploading, maybe signature of loader wasn't accepted ?

### ISSUE THREAD

**Issue by cibimo** [bkerler/edl#44]
> zyl@MBP edl % ./edl.py --loader="/Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn" printgpt
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader /Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
'int' object is not subscriptable
No suitable loader found :(
<Library.usblib.usb_class object at 0x10b21f110>
zyl@MBP edl % ./edl.py --loader="/Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn" printgpt
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader /Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Sahara in error state, resetting ...
Traceback (most recent call last):
  File "./edl.py", line 398, in <module>
    base.run()
  File "./edl.py", line 308, in run
    saharahdl.cmd_reset()
  File "/Users/zyl/Downloads/edl/Library/sahara.py", line 558, in cmd_reset
    if cmd["cmd"] == self.cmd.SAHARA_RESET_RSP:
TypeError: 'int' object is not subscriptable

**Comment by cibimo** [comment]
With debugmode:

> zyl@MBP edl % ./edl.py --loader="/Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn" printgpt --debugmode
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader /Volumes/SN750/padsj/image/prog_emmc_firehose_8917_ddr.mbn ...
main - Waiting for the device
usb_class
usb_class - [LIB]:   CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x20 (32 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0x80 Bus Powered
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Vendor Specific ===========================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x2
     bInterfaceClass    :   0xff Vendor Specific
     bInterfaceSubClass :   0xff
     bInterfaceProtocol :   0xff
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x1: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x1 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
main - Device detected :)
usb_class
usb_class - [LIB]: connect:0x80
usb_class
usb_class - [LIB]: RX:010000003000000002000000010000000004000000000000000000000000000000000000000000000000000000000000
main - Mode detected: sahara
Device is in EDL mode .. continuing.
usb_class
usb_class - [LIB]: TX:020000003000000002000000010000000000000003000000000000000000000000000000000000000000000000000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:0b00000008000000
usb_class
usb_class - [LIB]: TX:0d0000000c00000001000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:0e000000100000000100000004000000
usb_class
usb_class - [LIB]: TX:0f0000000c00000001000000
usb_class
usb_class - [LIB]: cmd_exec:0x4
usb_class
usb_class - [LIB]: RX:6896404e
usb_class
usb_class - [LIB]: TX:0d0000000c00000002000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:0e000000100000000200000018000000
usb_class
usb_class - [LIB]: TX:0f0000000c00000002000000
usb_class
usb_class - [LIB]: cmd_exec:0x18
usb_class
usb_class - [LIB]: RX:00000000e150050000000000e150050000000000e1500500
usb_class
usb_class - [LIB]: TX:0d0000000c00000003000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:0e000000100000000300000060000000
usb_class
usb_class - [LIB]: TX:0f0000000c00000003000000
usb_class
usb_class - [LIB]: cmd_exec:0x60
usb_class
usb_class - [LIB]: RX:ddb33f2a320b3536ffa2026554dab19cf903d207bfb0ae9ee1d39847828740c1ddb33f2a320b3536ffa2026554dab19cf903d207bfb0ae9ee1d39847828740c1ddb33f2a320b3536ffa2026554dab19cf903d207bfb0ae9ee1d39847828740c1
usb_class
usb_class - [LIB]: TX:0c0000000c00000003000000
usb_class
usb_class - [LIB]: connect:0x80
usb_class
usb_class - [LIB]: RX:010000003000000002000000010000000004000003000000000000000000000000000000000000000000000000000000
usb_class
usb_class - [LIB]: TX:020000003000000002000000010000000000000000000000000000000000000000000000000000000000000000000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:03000000140000000d0000000000000034000000
usb_class
usb_class - [LIB]: TX:7f454c460101010000000000000000000200280001000000308b0008340000000000000002000005340020000900280000000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:03000000140000000d0000003400000020010000
usb_class
usb_class - [LIB]: TX:0000000000000000000000000000000054010000000000000000000700000000000000000010000000b0768600b07686481a000000200000000020020010000001000000c08905000000220000002200802c0000802c000005000000100000000100000040b605000030220000302200280b0000480b000006000000080000000100000000300000006000080060000838bc040038bc040005000080100000000100000038ec04000060050800600508000000000060000006000000040000000100000038ec040000c0050800c00508889d00006c5a0100060000000010000001000000c089050000000080000000800000000000242000060000000010000001000000c0890500000070860000708600000000f0a606000600000000400000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:03000000140000000d0000000010000000100000
usb_class
usb_class - [LIB]: TX:15000000030000000000000028b07686201a00002001000048b176860001000048b27686001800009fceace13036c945bfe0df4680b50af406b4a869b745d14c955b5c859f7e80b700000000000000000000000000000000000000000000000000000000000000008084d6e0c5fbc855b0e2cc60fd3743ece8f9875cbda13fe4f83e6d6de961fe0200c79640569f93081e0e539c600927d962a012f40dc67c9772c1a77f975ba739524e34d0e578254a5dcfd1605a0ab746ae16c46b58774ab65c9fa0eed1a6b8470000000000000000000000000000000000000000000000000000000000000000b45624aa8d4ced2ff9c02b50834b556caba68c68b60dd328a88acf47c16ca755000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005479168f31784ef5c8094e5aa937e69e431cc4e60c608b2501304fdbe4b252d9705751f1212b6f62ae1da58e786c7972099867a6ad574ae5b121f6b4bf534fb0b925b6588fb6003e2e6760dd94ade1d9bab79e2fee0003ae02962ae5740b155775cc8b79bf8aa680a527c0ae5d0d1c54bfd6f0a9f9576efd7f5abbbd203f1d8c64c5d8f03e99701911e094df2b38aed56041e45899cd471bcf867577db885cb23c2fe42ef48fb2f650a3b84d23df5f7e68d6cd646d6d93614994f0d36bd6e557773d605ff34a1c1b25468746690e8f493552ce2d7ca7a42ab65428f8fe1ed3aaafa63238267f5bc50e58e35c8455bb66ea133685fa861550f51a12c410940df9308204ac30820394a003020102020101300d06092a864886f70d01010b05003081b1310b300906035504061302434e3110300e060355040813074875695a686f753111300f060355040713085a686f6e674b616931123010060355040a13094c4f4e47434845455231243022060355040b131b4c6f6e6743686565722050726f64756374696f6e2041747465732e31263024060355040b131d4c6f6e67436865657220546563686e6f6c6f677920436f2e2c204c7464311b3019060355040313124c4354206174746573746174696f6e204341301e170d3139313230333137313731365a170d3339313132383137313731365a3082013f310b300906035504061302434e3120301e060355040313174c6f6e67436865657220536563546f6f6c7320557365723111300f060355040713085a686f6e674b616931123010060355040a13094c6f6e6743686565723110300e060355040813074875695a686f7531223020060355040b1419303120303030303030303030303030303030332053575f494431223020060355040b1419303220303030353630453130303030303030302048575f494431173015060355040b140e30342030303030204f454d5f4944311c301a060355040b141330352030303030303134382053575f53495a4531193017060355040b141030362030303030204d4f44454c5f494431173015060355040b130e303720303030312053484132353631223020060355040b13193033203030303030303030303030303030303220444542554730820122300d06092a864886f70d01010105000382010f003082010a0282010100b2d02b6c4b0c03ca49b0752ee0197ca140d37413e347cda3fec21143ebe99e9d803c356586386c711c36fd72eeb7ddc32f1c23a2a5e318684aae1a2df76099c20a51bacda34793624a8301adae7708c838e66155b88d5dfdce769cfa78d82acfb7b17bda4aa2f0d553fab1f7ae4b27f143addd2b3c8d793c039caa24b240beb8c400e1ffdd0bf7c948e86ae8c7e6ff88f3536038326d2b544cb089db177406aa64dcd636edeaa174da6333d98a19e3dee65570694a309660e6f342625fcebfca5474cac57a6e99b29da937d0d466bfa78d206c8dc38b98b2536dbf29e3b4f30f09c49a2be34cea4ae51b5f6ba44201f2a72248e71ace5fdf9311f70a13d296f70203010001a33e303c301f0603551d230418301680142652871ebf428f08ea6080f061fa4f32089b246d300c0603551d1304053003020100300b0603551d0f040403020780300d06092a864886f70d01010b0500038201010071fa95bf57bb1554fbdbdce11ea71e849e7c5aba7ccac95d10a9b65d6ccbd2ff6748948104cd0a93560ee48d3077b387d4391ab0e3a144bedc27329b3690c21c378c479fce89a6ac72f321c3e919077028ac2e99c3d222f24a0d57bc2872d89438612d70316d0740cf1785e14279478c179462c160656f9ebac5bcd921cfc6c938176a84f8ff89c68098e3726561f113f635a706759b4ffcd28607538e2f18a07b0a637eb60391be3f36460c4b8a95fc0d6c1173b4eac35112ff5f65628a35e1404e53eee7314c28beba7c5a019a5a81e165ede5193201a54fa4a868d76a03750f7801934e305dcb58cd0b2190f5d1c6a1a11faeb102c6f916e0694a0d558f06308204363082031ea003020102020105300d06092a864886f70d01010b05003081aa310b300906035504061302434e3110300e060355040813074875695a686f753111300f060355040713085a686f6e674b616931123010060355040a13094c4f4e47434845455231243022060355040b131b4c6f6e6743686565722050726f64756374696f6e2041747465732e31263024060355040b131d4c6f6e67436865657220546563686e6f6c6f677920436f2e2c204c7464311430120603550403130b4c435420524f4f54204341301e170d3136313230333039333433325a170d3336313132383039333433325a3081b1310b300906035504061302434e3110300e060355040813074875695a686f753111300f060355040713085a686f6e674b616931123010060355040a13094c4f4e47434845455231243022060355040b131b4c6f6e6743686565722050726f64756374696f6e2041747465732e31263024060355040b131d4c6f6e67436865657220546563686e6f6c6f677920436f2e2c204c7464311b3019060355040313124c4354206174746573746174696f6e20434130820120300d06092a864886f70d01010105000382010d00308201080282010100d1fd006841181d07d793221a83c82c62eda4696eb56dd13c8509b9e90310aee801ae722c4dfbdfbb4323907c7f576c2f9b5db05b049dfccc3d141b645fa24d6e77ed04cc5097142bb450a036479cb2d8da1a5956905edf1082370624383715bda2aa72151475fb8cd7461f5cac08c170de242809c3fe9b009b21f919ee254584b3d8662a3a42767f245b377b4f52308f67ee95f6873d21110cb8932a371b85ddbd6a4ad68f828b21503ad115906d3241a30b0ca52d554ac82c22911eb532d6a553bcbee0afb8ae1559670a560672f2a0c61f8990efbd8d0e9c13a95a45629964e02ba2795bc0e4e65da20be48d1feb3abc221ae201461cef67f9eaf146a59f33020103a360305e301f0603551d23041830168014bb465c01f36bd8e990fc2b516bdc39cec46424d7301d0603551d0e041604142652871ebf428f08ea6080f061fa4f32089b246d300f0603551d13040830060101ff020100300b0603551d0f040403020204300d06092a864886f70d01010b05000382010100533b68bbf272bb523f0b2429c54f5cc685884560c8e9a775d0cd073f1b9dec68463c14fa73b92c10bcbec3db8b06202d997800b4b9c02e5d74b5b95e31f57980241198ab656a2a9cc5eb0d1be3c899d035e9e4c2e439560ac85ff8c1175674e201e867192f28902df4ab3301d4c2f722a1700b082d5ae994c2237fb9b9f1bad005a75153dcce5cd6cf47331ec5b0aea6c488c39be846f620abc6f9898b567ea8b5aec7338666295dff7eb92b6cad9c6fed176a59cb6c389c824832acc1f98e7b0103a891a94c846b7dd7383fc1c8780e37ce4c8e02ed99e17719ea0ca74827a6c9c2372a790fcfcc86d8dca9c4c0ef8a3aa17ac4a0d71d87576578d1c72311a93082040b308202f3a003020102020101300d06092a864886f70d01010b05003081aa310b300906035504061302434e3110300e060355040813074875695a686f753111300f060355040713085a686f6e674b616931123010060355040a13094c4f4e47434845455231243022060355040b131b4c6f6e6743686565722050726f64756374696f6e2041747465732e31263024060355040b131d4c6f6e67436865657220546563686e6f6c6f677920436f2e2c204c7464311430120603550403130b4c435420524f4f54204341301e170d3136313230333039333433315a170d3336313132383039333433315a3081aa310b300906035504061302434e3110300e060355040813074875695a686f753111300f060355040713085a686f6e674b616931123010060355040a13094c4f4e47434845455231243022060355040b131b4c6f6e6743686565722050726f64756374696f6e2041747465732e31263024060355040b131d4c6f6e67436865657220546563686e6f6c6f677920436f2e2c204c7464311430120603550403130b4c435420524f4f5420434130820120300d06092a864886f70d01010105000382010d00308201080282010100b489b9b887ba23c1325d7b631b8ca3bf991afd3196343531aa388e63e0f925e7b22f5f02b694cafc9008b1254cb5266d0f2c9758da399af05c638a102027f8ec29fb0f576d53948372b758ae67b1a4cbe7fa9a8b213fd444c8a354fb0c2bce84efa6659fab4d1700547f1a8d8caa97accebc871c45f513a27bd668cc57685def949ca6b79e01596f5a14a478f7c6baad34570db26572eb315eca92d92a6367702079611811f1a122fb26f673860cb110f222242ddb743efcb39c78e11db3d4f542322364501e21669e6c80ac19a70ddf9b3b6d915ef1c7ab47b01a07883c71a1a1e35cf8881d7c584b5a37f6a6538d7fe6527ef4796ad2ea8410696c01d3e1a9020103a33c303a301d0603551d0e04160414bb465c01f36bd8e990fc2b516bdc39cec46424d7300c0603551d13040530030101ff300b0603551d0f040403020106300d06092a864886f70d01010b05000382010100274906f4f92fc91a3565db89648c81e75b88aaba0cfd4ce52689e164232ebe4d74fc708b78e4571b3086c775f58feb7443dbdb166c91e8d7717b8bfc9a1238325cb65efecb3aaaeb4d768ad6b2d72b62e9132f893c7361125253245d69977d25d7b7a56080ea11500a64e04ec3433344416bc99ef7028b93983091816702c18aae51ab0f6f398d78a467825074ac17b8aef673971825a0f9dc569bb3330ef82f5492b76860d1b1e8bcf5aadc5b7e5a47634a118b61c35ece6808b1b87ba0dee8fec3ccd1e8e968eee1e064e22d02d03685a521c9da90d7bf3c936756de63ac0003df6c532a50083edb9d976ba77ea4b46de9e6c564dae2f2863b1b5c0c4477b6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: RX:03000000140000000d00000000200000480a0000
usb_class
usb_class - [LIB]: TX:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: Timed out
usb_class
usb_class - [LIB]: b''
usb_class
usb_class - [LIB]: TX:0500000008000000
usb_class
usb_class - [LIB]: get_rsp:0x80
usb_class
usb_class - [LIB]: Timed out
usb_class
usb_class - [LIB]: b''
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
'int' object is not subscriptable
No suitable loader found :(
<Library.usblib.usb_class object at 0x10b4c4310>

**Comment by bkerler** [comment]
That means that the loader doesn't respond, maybe because the pkhash doesn't match the device pkhash, or because the hardware doesn't match the loader.
