### ISSUE TITLE
Read failed at sector 0, Invalid or unknown GPT magic.

### ISSUE THREAD

**Issue by kercre123** [bkerler/edl#48]
I used this tool with my Windows machine, and it worked very well. I have a little APQ8009 robot which I unbricked with it.

However, when I tried to use it on my Linux (Ubuntu 20.04) machine, this is the output I get.

wire@wirebook:~/Desktop/edl$ sudo python3 edl.py rf starbutt.bin --loader=8909.mbn
Capstone and Keystone libraries missing.
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Using loader 8909.mbn ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
firehose - Nop succeeded.
firehose - No supported functions detected, configuring qc generic commands
firehose - 
firehose
firehose - [LIB]: GetStorageInfo command isn't supported.
firehose_client - No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - TargetName=MSM8909
firehose - MemoryName=eMMC
firehose - Version=1
firehose_client - Supported functions:
-----------------
configure,program,firmwarewrite,patch,setbootablestoragedrive,ufs,emmc,power,benchmark,read,getstorageinfo,getcrc16digest,getsha256digest,erase,peek,poke,nop,xml
firehose
firehose - [LIB]: Error:
firehose
firehose - [LIB]: Read failed at sector 0
firehose
firehose - [LIB]: Finished sector address 0
firehose
firehose - [LIB]: Error:
firehose
firehose - [LIB]: Read failed at sector 0
firehose
firehose - [LIB]: Finished sector address 0
gpt
gpt - [LIB]: Invalid or unknown GPT magic.
Traceback (most recent call last):
  File "edl.py", line 422, in <module>
    base.run()
  File "edl.py", line 404, in run
    fh.handle_firehose(cmd,options)
  File "/home/wire/Desktop/edl/Library/firehose_client.py", line 280, in handle_firehose
    self.printer(f"Dumping sector 0 with sector count {str(guid_gpt.totalsectors)} as {filename}.")
AttributeError: 'gpt' object has no attribute 'totalsectors'

**Comment by bkerler** [comment]
Hi, can you run with option --debugmode and send me the log.txt ? Thanks

**Comment by kercre123** [comment]
> Hi, can you run with option --debugmode and send me the log.txt ? Thanks

I just restarted and now it seems to be working fine. Maybe I just needed to restart for the .rules to take effect.
