### ISSUE TITLE
Unknown CPU; send log...

### ISSUE THREAD

**Issue by Bob21lla** [bkerler/edl#498]
Hey,

So when attempting to run this program with my phone I was given an error message that reads as follows:

**user@livedvd:/opt/edl$** ./edl
Qualcomm Sahara / Firehose Client V3.60 (c) B.Kerler 2018-2022.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2.1
main - Mode detected: sahara
sahara - 
------------------------
HWID:              0x001a90e100510000 (MSM_ID:0x001a90e1,OEM_ID:0x0051,MODEL_ID:0x0000)
Unknown CPU, please send log as issue to https://github.com/bkerler/edl
PK_HASH:           0x22f415bec935e3cbe982eeb854dd5f3d150d46a5c41060bbfe4600eaf94b981d
Serial:            0x5e54528b

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (001a90e100510000_22f415bec935e3cb_[FHPRG/ENPRG].bin) :(

My phone is an OnePlus Nord N30 5G (CPH2515) if that helps.  If you need any additional information just let me know.

Thanks!
![Screenshot_2024-01-29_20-15-28](https://github.com/bkerler/edl/assets/47058260/9892f09c-9a0b-4d7a-8ca4-ba37c0e6fbd4)

**Comment by RenateUSB** [comment]
I don't know but this file has the right hash, the right OEM and it handles SM_STRAIT.
https://github.com/bkerler/Loaders/blob/main/oppo/0000000000510000_22f415bec935e3cb_fhprg_rmx3471_695_SM6375.bin

**Comment by Bob21lla** [comment]
Thank you for the help!
