### ISSUE TITLE
does this tool run smoothly on linux?

### ISSUE THREAD

**Issue by RealYukiSan** [bkerler/edl#502]
how this tool work without [qualcomm driver](https://gsmusbdrivers.com/download/qualcomm-hs-usb-qdloader-9008-driver-64-bit-windows/)?

**Comment by RenateUSB** [comment]
EDL/Sahara/Firehose is just a USB bulk out endpoint and a USB bulk in endpoint.
It's simple to just use them directly.
Only wackoes use bogus Qualcomm virtual com ports or their WIndows drivers.
Still, in Windows you need a generic WinUsb driver. Zadig can install it.

**Comment by RealYukiSan** [comment]
> Still, in Windows you need a generic WinUsb driver. Zadig can install it.

how about linux?

**Comment by RenateUSB** [comment]
Linux does not need a driver for this.

**Comment by RealYukiSan** [comment]
hmmmmmm wondering why most flashing tools developed in windows environment instead of linux

**Comment by cuynu** [comment]
> hmmmmmm wondering why most flashing tools developed in windows environment instead of linux

cuz of its popularity
