### ISSUE TITLE
restore specific partition

### ISSUE THREAD

**Issue by RealYukiSan** [bkerler/edl#503]
does this tool capable to restrore/recover the backup of efs partition? I've followed [this tutorial](https://www.getdroidtips.com/backup-and-restore-efs-partition/#Method-2) but my device not support fastboot, so I looking for alternative command of: `fastboot flash modemst1 modemst1.bin`

modemst1.bin generated by command: `dd if=/dev/block/mmcblk0p10 of=/sdcard/modemst1.bin bs=512`

- related [links](https://t.me/oppoa37community/125660)

**Comment by RenateUSB** [comment]
Partitions are partitions. If it can do one, it can do any.
(With the exception of Motorola whose EDL loaders include specific block restrictions.)
