### ISSUE TITLE
Loader for sm8350

### ISSUE THREAD

**Issue by pckotzer** [bkerler/edl#518]
Is there anything for

HWID:              0x001350e100290875 (MSM_ID:0x001350e1,OEM_ID:0x0029,MODEL_ID:0x0875)
CPU detected:      "lahaina"
PK_HASH:           0x0e172e7799ab2674eacaee35e098e8b505ae768f7a2418ca653abecbe02198c3

**Comment by wolverine998** [comment]
Firstly, which phone are you using. You must try to use loader that is supplied by them, if it exists. Also, that is the Snapdragon 8 Gen 2 i think, you could try looking on Google and testing available loaders. Good luck!

**Comment by wolverine998** [comment]
Hmm, lahaina is 888. Is there a loader in manufacturer stock ROM zip? It should be provided in the fastboot ROM.

**Comment by pckotzer** [comment]
There is only a payload.bin or something. What extension did have the loader? Iam sure there is none in the rom zip

**Comment by pckotzer** [comment]
I have a downgrade rom zip containing this stuff
![IMG_20240501_222342_503](https://github.com/bkerler/edl/assets/67205129/98c439fb-1fef-4acf-87d7-0836cbd0a03a)
![IMG_20240501_222342_337](https://github.com/bkerler/edl/assets/67205129/d7ea5b08-a954-4780-8172-72dd4903db1a)
![IMG_20240501_222342_647](https://github.com/bkerler/edl/assets/67205129/4c3e50a2-98ef-4743-82f7-7248711b720a)

**Comment by wolverine998** [comment]
In the firmware folder, the **prog_firehose_ddr.elf**.
If it rejects the loader, try the **lite** version. Hope it Works.

**Comment by pckotzer** [comment]
539f1ef0f4cea98513632568316b77a6  Loaders/asus/prog_firehose_ddr.elf
138f36e226de1a959ff7479f6b2ad8e3  Loaders/asus/prog_firehose_lite.elf

However i used ddr.elf and used the edl unlock command it started to do something with saying Full Ramdump, the edl tool sayd the device disconnected and in the mode on phone nothing happend so i restarted the device and now iam unabel to get in edl again by using adb reboot edl

**Comment by wolverine998** [comment]
Please take care, if your device isnt bricked, make sure you do the commands right. Especially **write** command. Reboot into fastboot, the to

**Comment by pckotzer** [comment]
This is what is did after that, and it just dont go in edl with adb command. Device works fine

**Comment by pckotzer** [comment]
I think the loader i used is just for Full Ramdump stuff, and the lite loader i cant test now xD

**Comment by pckotzer** [comment]
I want to unlock the bootloader cause asus just destroyed the ability for that with their false promises

**Comment by pckotzer** [comment]
This loader works with the functions mentioned above by edl, the ddr one, i can write and read successfully.
https://www.mediafire.com/file/okhp5aebkbwfdwr/prog_firehose_ddr.elf/file

**Comment by RenateUSB** [comment]
@pckotzer @bkerler 

Please add this to the collection, it is completely Qualcomm with no OEM or HWID.
It should work on some newer models like:

```
SC_KODIAK_CHROME
SC_KODIAK_WINDOWS
SCP_MAKENA
SDX_OLYMPIC
SM_CEDROS
SM_KODIAK
SM_LAHAINA
SM_WAIPIO
SMP_LAHAINA
```

**Comment by crashniels** [comment]
> I want to unlock the bootloader cause asus just destroyed the ability for that with their false promises

Did you manage to unlock the bootloader ?

**Comment by pckotzer** [comment]
Nope, and my zenfone 8 died also haha

**Comment by crashniels** [comment]
> I have a downgrade rom zip containing this stuff 

do you still have the romdump zip? Would you mind sharing it ?

**Comment by pckotzer** [comment]
> > I have a downgrade rom zip containing this stuff
> 
> do you still have the romdump zip? Would you mind sharing it ?

No, i dont have it anymore, but you can find it in xda zenfone 8 firmware collection
