### ISSUE TITLE
Samsung s9 G960U flash

### ISSUE THREAD

**Issue by francdubai** [bkerler/edl#54]
I whant to know if there is any solution for flash G960U via edl because I keep stuck when need to send system.img 
![26B83986-F7D8-4CDB-96CE-B316CF049F50](https://user-images.githubusercontent.com/48048494/108467449-82773780-7285-11eb-933a-509b330273a2.jpeg)

**Comment by bkerler** [comment]
can you rerun using --debugmode and upload the log.txt ?

**Comment by francdubai** [comment]
I’m using bat for run and I can’t get log I don’t know about debug mode.

**Comment by francdubai** [comment]
I’m my folder I have emmcdl raw programm.xml and run bat for run I must put
the phone in edl 9008 mode and run the bat after run the bat BL file flash
well but when start to flash system stuck at sector remaining 12.....

**Comment by francdubai** [comment]
<data>
<response value="ACK" rawmode="true" /></data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="ACK" rawmode="false" /></data>
start_sector: 838 physical_partition_number: 2 num_partition_sectors: 64
filename: xbl_config.elf file_sector_offset: 0
Sparse image not detected -- loading binary
In offset: 0 out offset: 838 sectors: 25
<?xml version="1.0" ?><data>
<program SECTOR_SIZE_IN_BYTES="4096" num_partition_sectors="25"
physical_partition_number="2" start_sector="838"/>
</data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="INFO: Calling handler for program" /></data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="ACK" rawmode="true" /></data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="ACK" rawmode="false" /></data>
start_sector: 76553 physical_partition_number: 0 num_partition_sectors: 128
start_sector: 1586696 physical_partition_number: 0 num_partition_sectors:
128000 start_sector: 142217 physical_partition_number: 0
num_partition_sectors: 256 start_sector: 142473 physical_partition_number:
0 num_partition_sectors: 128 start_sector: 142601
physical_partition_number: 0 num_partition_sectors: 128 start_sector:
127752 physical_partition_number: 0 num_partition_sectors: 1217536
filename: system.img file_sector_offset: 0
Sparse image not detected -- loading binary
In offset: 0 out offset: 127752 sectors: 1217536
<?xml version="1.0" ?><data>
<program SECTOR_SIZE_IN_BYTES="4096" num_partition_sectors="1217536"
physical_partition_number="0" start_sector="127752"/>
</data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="INFO: Calling handler for program" /></data>
<?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="ACK" rawmode="true" /></data>
Sectors remaining 1217536

**Comment by bkerler** [comment]
samsung firehose loaders have a protection for some sectors :)

**Comment by francdubai** [comment]
so how to flash s9 via edl? Because I saw many phone with custom rom and
system status official and void0x0 then only edl can’t do that

**Comment by bkerler** [comment]
for some devices, there are engineering aboot / boot that allow that (called combination rom).
