### ISSUE TITLE
Is there a way to disable secureboot?

### ISSUE THREAD

**Issue by Koladweep** [bkerler/edl#567]
D:\edl>python edl peek 0x000000 0x500000000 mem.bin
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara -
Version 0x2
------------------------
HWID:              0x000940e100900000 (MSM_ID:0x000940e1,OEM_ID:0x0090,MODEL_ID:0x0000)
CPU detected:      "MSM8905"
PK_HASH:           0xac642ebfa99abb54011debd5d0b00d0bab817c8e92ab2cdc55bb27ae4ed0adf5
Serial:            0x13bafdfe

sahara - Detected loader: D:\edl\edlclient\..\Loaders\f10q\000940e100900000_ac642ebfa99abb54_fhprg_peek.bin
sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader D:\edl\edlclient\..\Loaders\f10q\000940e100900000_ac642ebfa99abb54_fhprg_peek.bin ...
sahara - 32-Bit mode detected.
sahara - Firehose mode detected, uploading...
sahara - Loader successfully uploaded.
main - Trying to connect to firehose loader ...
firehose_client
firehose_client - [LIB]: No --memory option set, we assume "eMMC" as default ..., if it fails, try using "--memory" with "UFS","NAND" or "spinor" instead !
firehose - TargetName=MSM8909
firehose - MemoryName=eMMC
firehose - Version=1
firehose - Trying to read first storage sector...
firehose - Running configure...
firehose_client - Supported functions:
-----------------
firehose - Peek: Address(0x0),Size(0x500000000)
Progress: |--------------------------------------------------|   0.0% Complete                                                                    firehose
firehose - [LIB]: Error:bytearray(b'<?xml version="1.0" encoding="UTF-8" ?><data><log value="Peek not allowed when secure boot is enabled." /></data>')
firehose_client - Peek data from offset 0x0 and length 0x500000000 was written to mem.bin

**Comment by RenateUSB** [comment]
Only one way: Buy an unprogrammed SoC and have someone replace the one on your device.
https://www.censtry.com/product/qualcomm/msm8905.html

**Comment by Koladweep** [comment]
Thanks for the response.
You mean the SOC should not have a PBL?

**Comment by Koladweep** [comment]
Good idea. 
2 options:
1. Look for a way to block the OTA updates that will lead to this situation again.
2, get a raspberry pi instead which would cost the same. https://robu.in/product/raspberry-pi-3-model-a/

**Comment by Koladweep** [comment]
Wow!
I'll consider that.
However, unless I have a good reason to do that, 
I could consider a Raspberry Pi for all the tinkering, since it would cost the same amount (but without any of the cool stuff that a phone has i.e. NFC, Wi-Fi, etc.)
https://robu.in/product/raspberry-pi-3-model-a/
