### ISSUE TITLE
Stuck on "Firehose mode detected, uploading..."

### ISSUE THREAD

**Issue by ProfessorLongBeard** [bkerler/edl#587]
I've got a Moto G Power 2021 on Android 11 I was testing this tool on. I was able to get the phones stock ROM (It's for the Verizon variant) and found the programmer that came with it. The firmware package though is for Android 10 so I'm not sure if this is why I'm getting stuck here. I'm not sure it's supposed to sit that long?

**Comment by ProfessorLongBeard** [comment]
This is about as far as it gets:

```
(edl) austin@ryzen-beast:/media/austin/Scratch/moto/edl$ python3 edl printgpt --loader=prog_firehose_lite.elf
Qualcomm Sahara / Firehose Client V3.62 (c) B.Kerler 2018-2024.
main - Using loader prog_firehose_lite.elf ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold vol dwn + pwr, in fastboot mode connect usb.
        Run "./fastpwn oem edl".
main - Other:  Run "adb reboot edl".

...............
.main - Device detected :)
sahara - Protocol version: 2, Version supported: 1
main - Mode detected: sahara
sahara - 
Version 0x2
------------------------
HWID:              0x0014d0e102e80000 (MSM_ID:0x0014d0e1,OEM_ID:0x02e8,MODEL_ID:0x0000)
CPU detected:      "SDM662"
PK_HASH:           0xabbcc86fe393b13d59e2a2ec944af26da3fa3d4b2a1ccd2fb383c73e0fffc30dc1736dcb2752e955a61421c349974f90
Serial:            0xa120fadb

sahara - Protocol version: 2, Version supported: 1
sahara - Uploading loader prog_firehose_lite.elf ...
sahara - 64-Bit mode detected.
sahara - Firehose mode detected, uploading...
```

**Comment by RenateUSB** [comment]
I have that same model. I use https://github.com/bkerler/Loaders/blob/main/lenovo_motorola/0000000002e80000_abbcc86fe393b13d_fhprg.bin for a loader.

Note that this is Motorola and therefore is a **restricted** loader that can not access all parts of flash.

**Comment by ProfessorLongBeard** [comment]
> I have that same model. I use https://github.com/bkerler/Loaders/blob/main/lenovo_motorola/0000000002e80000_abbcc86fe393b13d_fhprg.bin for a loader.
> 
> Note that this is Motorola and therefore is a **restricted** loader that can not access all parts of flash.

This is good to know.... It would be nice just to be able to send the loader haha

**Comment by ProfessorLongBeard** [comment]
I did notice I'm able to so simple tasks like reading the GPT, but it doesn't appear to actually save on my local host machine. None the less I'm happy this tool at least works on my moto haha; Thank you guys for this wonderful tool!
