### ISSUE TITLE
UFS Flash to boot_a long time, is this normal?

### ISSUE THREAD

**Issue by kittizz** [bkerler/edl#63]
i Flash boot_a in oneplus n10 is slow

C:\Users\kitti\Desktop\edl-master>py edl.py w boot_a boot.img --memory=ufs --lun=4
Qualcomm Sahara / Firehose Client V3.2 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: firehose
firehose - Nop succeeded.
firehose - Chip serial num: 575202359 (0x2248e437)
firehose - Supported Functions: program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,eraseuserdata,setprocstart,setswprojmodel
firehose -
firehose - TargetName=
firehose - MemoryName=UFS
firehose - Version=
firehose_client - Supported functions:
-----------------
program,read,nop,patch,configure,setbootablestoragedrive,erase,power,firmwarewrite,getstorageinfo,benchmark,emmc,ufs,fixgpt,getsha256digest,eraseuserdata,setprocstart,setswprojmodel
firehose -
Writing to physical partition 4, sector 160390, sectors 24576
Progress: |████----------------------------------------------| 8.1% Complete (Sector 1980)0)

**Comment by kittizz** [comment]
[True, {'value': 'ACK', 'rawmode': 'false'}, bytearray(b'<?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="ERROR: fm=0, ato=0" /></data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<log value="ERROR: Device verified failed." /></data><?xml version="1.0" encoding="UTF-8" ?>\n<data>\n<response value="ACK" rawmode="false" />\n</data>')]

**Comment by kittizz** [comment]
@bkerler Which models oneplus can be write with EDL?

Thank you 👏￼

**Comment by bkerler** [comment]
Oneplus up to 6. 7,8,Nord has write auth. And N10-N100 they increased security even more
