### ISSUE TITLE
How to swipe this file in

### ISSUE THREAD

**Issue by Soar1989** [bkerler/edl#64]
<data><sig TargetName="sig" verbose="1" size_in_bytes="256"/></data>

[edl.zip](https://github.com/bkerler/edl/files/6148117/edl.zip)

**Comment by Soar1989** [comment]
<data><sig TargetName="sig" verbose="1" size_in_bytes="256"/></data>

**Comment by Soar1989** [comment]
How to swipe this file in
<data><sig TargetName="sig" verbose="1" size_in_bytes="256"/></data>

**Comment by bkerler** [comment]
That's an answer for xiaomi edl auth, not a request, so this won't work. But normally you can send xml files using "xml" command.

**Comment by Soar1989** [comment]
> 这是对xiaomi edl auth的答复，而不是请求，因此这行不通。但是通常您可以使用“ xml”命令发送xml文件。

How to send xml file to use
