### ISSUE TITLE
Vodafone Smart Ultra 6 please add it to supported devices or how it will?

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#69]
Hello Good Friends!
if I give a sensitive info that  without knowing, and this is no important!

![image](https://user-images.githubusercontent.com/30759335/113943994-50994080-97f3-11eb-8df0-3c974b5d4c91.png)

I have falsely delete all emmc partitions. for VSU6, original brand is zte.
FTM mode has not actived but edm or edl has been active!

the phone the phone has been flashed with unauthorized software and is locked has been flashed with unauthorized software and is locked 
this warning  was given the phone  during power on 

![image](https://user-images.githubusercontent.com/30759335/113945552-12e9e700-97f6-11eb-9aa1-8008dd8dbc56.png)

I have mbn files, how can  I also  use  the files as loader? How to converted  mbn files to bin loader file

Thanks to reading Thanks to your helping

**Comment by danielkutik** [comment]
the files starting with prog_emmc_firehose_*.mbn look relevant here. copy them into a folder and then follow these instructions:
https://github.com/bkerler/edl#install-edl-loaders

**Comment by CyberMan571** [comment]
![Screenshot_2021-04-09_15-05-23](https://user-images.githubusercontent.com/30759335/114201882-33c15200-9946-11eb-9413-89d00c30e291.png)

![image](https://user-images.githubusercontent.com/30759335/114202421-b0543080-9946-11eb-9a45-f3f912deacf0.png)

![image](https://user-images.githubusercontent.com/30759335/114202606-ded20b80-9946-11eb-88ff-70c9e80ef85b.png)

Thanks to reply 
I did what is called, but I have encountered such errors. 
python3 -m pip install -r requirements.txt 
 I did install  which are the requirement 
 
> 
> Capstone library is missing.
> Keystone library is missing.
> 
these errors still was going however it has gone  them when  I installed  the following

>  sudo apt install python3-keystone -y
> sudo apt install python3-capstone -y
> sudo apt install python-wheel-common -y
> sudo apt install python3-usb1 -y
> sudo apt install python3-docopt -y
> sudo dpkg -i /media/kali/Seagete_Expansion_Drive/ali/telefon-flash/edl/first-install/python-lzma_0.5.3-4_amd64.deb
> sudo apt install python3-lxml -y
> sudo apt install python3-colorama -y

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/114218117-89065f00-9958-11eb-9567-5121c32d1c78.png)
What error could cause this? so I uploaded all the requested ones. But I keep getting this error!  
Library Appears Not Installed.

**Comment by bkerler** [comment]
It looks like you reconnected 9008 port. A reconnect won't work if sahara failed. Start the edl.py client and then reboot the device into 9008 (disconnect battery if possible or use hardreset via button)

**Comment by CyberMan571** [comment]
I  have waiting as 15-20 minutes, it has being able to reconnect .

firehose - [LIB]: Error:{}
> firehose_client - [qfil] programming
> /media/kali/Seagete_Expansion_Drive/ali/Vodafone_Smart_Ultra_6_Stock_Rom-5.1/Firmware1/tz.mbn
> to ***@***.***(114688)...
> firehose -
>
>
tz.mbn
TZ.MBN is continually reinstalling. I have encounter an error here.

for PYUSB,  was said page it that is had been incompatible with Python3.9.
I have  install python3-usb/kali-rolling,now 1.0.2-2

I will let you know from improvements, I would like to be turned off when a
successful flashing is. folks-humans can learn something.
Bjoern Kerler ***@***.***>, 9 Nis 2021 Cum, 19:52 tarihinde
şunu yazdı:

**Comment by CyberMan571** [comment]
python3 edl.py w boot_a  ./Firmware1/boot.img --loader=./Loaders/loaders/0090b0e100040000_9764995d53559360_fhprg_peek.bin --memory=eMMC ( --skipresponse(the caused))
This Example of code has giving this error code is USBError(75, 'Overflow') <class 'usb.core.USBError'> 75.

**Comment by CyberMan571** [comment]
Hey Dear Friends;
I have meeting edl authorization problem with VSU 6 (original brand of ZTE blade s6 plus) 
 I have  receiving(confront) it similar which are "Read back verify failed at sector 1876912573,num sectors 131072"
 How to I have able to over bypass Qualcomm edl authorization

**Comment by CyberMan571** [comment]
second problem 
![image](https://user-images.githubusercontent.com/30759335/114805950-70041080-9d93-11eb-86e6-ca849d614262.png)

**Comment by bkerler** [comment]
Sorry, but vip and edl auth for ZTE aren't planned for now

**Comment by CyberMan571** [comment]
that was not good at all! How can I get the necessary information. collecting information from the phone for example auth. 
It may even be private.
In this way, both the project is developed. and people like to work more.

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116486918-40b6ce80-a87e-11eb-92f0-098884eb3a7e.png)
[(qfil)log.txt](https://github.com/bkerler/edl/files/6395549/qfil.log.txt)
[Errno 110] Operation timed out
how to solve timed out and gpt table fixing

**Comment by CyberMan571** [comment]
Thanks, I tested on ubuntu, and same problem. I have understood needing  a
problemless os and must learning reverse engineer to solving the problem.


Bjoern Kerler ***@***.***>, 5 Ağu 2021 Per, 10:15 tarihinde
şunu yazdı:

**Comment by CyberMan571** [comment]
@bkerler/edl
***@***.***>
I tested on a live ubuntu os

Ali ***@***.***>, 7 Ağu 2021 Cmt, 04:36 tarihinde şunu yazdı:
