### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by tuananhsai** [bkerler/edl#72]
haanh@DESKTOP-CSNTL16:/mnt/d/edl-master$ ./edl.py rf flash.bin --memory=ufs
Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
Traceback (most recent call last):
  File "./edl.py", line 360, in <module>
    base.run()
  File "./edl.py", line 257, in run
    mode, resp = self.doconnect(loop, mode, resp)
  File "./edl.py", line 155, in doconnect
    self.cdc.connected = self.cdc.connect()
  File "/mnt/d/edl-master/Library/usblib.py", line 213, in connect
    self.device = usb.core.find(idVendor=vid, idProduct=pid)
  File "/home/haanh/.local/lib/python3.8/site-packages/usb/core.py", line 1299, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by CyberMan571** [comment]
sudo apt install adb fastboot python3-dev python3-pip
sudo apt install liblzma-dev
sudo apt purge ModemManager or systemctl stop Modemmanager
sudo python3 -m pip install -r requirements.txt

Try it! 
Make sure the necessary files and programs are installed! 
Download it! https://github.com/M0Rf30/android-udev-rules

**Comment by CyberMan571** [comment]
https://github.com/bkerler/edl/issues/69#issuecomment-815438916  you can see link
