### ISSUE TITLE
ImportError: cannot import name 'SierraKeygen' from 'sierrakeygen'

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#75]
![image](https://user-images.githubusercontent.com/30759335/114806942-13095a00-9d95-11eb-9e3e-4726a1c6699f.png)

How to,  you and I   solve this error? this edl was updated

**Comment by bkerler** [comment]
Should be solved with commit #9a44793, please try :)

**Comment by CyberMan571** [comment]
Yes, I would be try(tried?) 
Ask you,
 how to only updated commit download?
it did not combine with 'which,that' :)
Thanks for update
