### ISSUE TITLE
Redmi Note 5A, Motorola Moto G5S Plus TV or Motorola Moto G4 Play

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#76]
Hi guys, first of all, congrats for making this tool and for sharing some loaders!!
I'm about to try any of these smarphones and is there an easy way to check if theres already a loader/firehose?
Is there any procedure?

**Comment by t5k6** [comment]
When you run ./edl.py printgpt the program will check HWID and PK_HASH of your device, and will try to match a suitable loader

**Comment by leosol** [comment]
Everything is working pretty well with Redmi Note 5A! Great! Will close the issue and in a few days I check the others. Thanks for the fast help and once again congrats for this very nice and usefull tool.
