### ISSUE TITLE
TypeError: 'int' object is not subscriptable on diag.py

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#79]
![image](https://user-images.githubusercontent.com/30759335/115368860-06cb3580-a1b7-11eb-9b2b-0bf2b0606b8b.png)

Yes, Newly issues! and will be waited  solution! :)

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/115389932-371dce80-a1cd-11eb-8bf1-1582d8a46658.png)
[(dowload)log.txt](https://github.com/bkerler/edl/files/6343192/dowload.log.txt)
![image](https://user-images.githubusercontent.com/30759335/115390119-69c7c700-a1cd-11eb-8377-a5e25a06f568.png)
[(info)log.txt](https://github.com/bkerler/edl/files/6343209/info.log.txt)

**Comment by CyberMan571** [comment]
Maybe it can work to you
[(sahara)log.txt](https://github.com/bkerler/edl/files/6343250/sahara.log.txt)

**Comment by CyberMan571** [comment]
you are patiently awaited by us @bkerler

**Comment by bkerler** [comment]
Let me see ;)

**Comment by bkerler** [comment]
Should be fixed with commit 57045a1

**Comment by CyberMan571** [comment]
No Sorry not be changed  it is going

**Comment by CyberMan571** [comment]
![Screenshot_2021-04-26_21-32-00](https://user-images.githubusercontent.com/30759335/116156292-cd288c00-a6da-11eb-93c4-31fa260141d8.png)

is port ttyusb0 is right?

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116156481-111b9100-a6db-11eb-8b4f-7dc5defcd568.png)

**Comment by CyberMan571** [comment]
└─$ lsusb -d 19d2:0500
Bus 001 Device 073: ID 19d2:0500 ZTE WCDMA Technologies MSM Android
`with` it works on uncorrupted phone with ftm mode

**Comment by bkerler** [comment]
Try latest commit. Diag Tools only work with diag port, not 0x9008 mode. Port should be /dev/ttyUSB0 instead

**Comment by CyberMan571** [comment]
```
default_vid_pid = [
    [0x2c7c, 0x0125, -1],  # Quectel EC25
    [0x1199, 0x9071, -1],  # Sierra Wireless
    [0x1199, 0x9091, -1],  # Sierra Wireless
    [0x0846, 0x68e2,  2],  # Netgear
    **[0x05C6, 0x9008, -1],  # QC EDL**
    [0x05C6, 0x676C, 0],   # QC Handset
    [0x05c6, 0x901d, 0],   # QC Android "setprop sys.usb.config diag,adb"
    [0x19d2, 0x0016, -1],  # ZTE Diag
    [0x19d2, 0x0076, -1],  # ZTE Download
    [0x19d2, 0x1404, 2],  # ZTE ADB Modem
    [0x12d1, 0x1506, -1],
    [0x413c, 0x81d7, 5],  # Telit LN940/T77W968
    [0x1bc7, 0x1040, 0],  # Telit LM960A18 USBCFG 1 QMI
    [0x1bc7, 0x1041, 0],  # Telit LM960A18 USBCFG 2 MBIM
    [0x1bc7, 0x1201, 0],  # Telit LE910C4-NF

]
````

I thought it could support it because of this code line.
