### ISSUE TITLE
a Usb Overflow bug with parameter --skipresponse

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#81]
Hi everyone 
I have  see a   usb overflow warning  with  --skipresponse!  when  I use this parameter, it give this error

**Comment by bkerler** [comment]
Please provide a log and more details what and when you get this error

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116302716-0cb1af80-a791-11eb-9dc7-7adad0c925c1.png)
![image](https://user-images.githubusercontent.com/30759335/116302783-23f09d00-a791-11eb-9ae0-2d35cddbd4fd.png)
[(--skipresponse)log.txt](https://github.com/bkerler/edl/files/6387237/--skipresponse.log.txt)

**Comment by CyberMan571** [comment]
Usb Overflow error occured with --skipresponse command line option!

**Comment by bkerler** [comment]
This won't work. You are trying to overwrite tz but you wrote it instead to the whole flash. Thus gpt is broken and edl won't work anymore. You need to repair the gpt and then write tz using w option, not wf.

**Comment by CyberMan571** [comment]
Thanks
me is what it shows on !
![image](https://user-images.githubusercontent.com/30759335/116467146-e5c1af00-a85e-11eb-9868-9b07c584a5e8.png)
How to repair gpt! with 9008 edl mode! 
it is not showing such as a mmcblk0

**Comment by CyberMan571** [comment]
can you add gpt repair option, please!

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116472232-258b9500-a865-11eb-8fb6-b2142a564927.png)
on me!

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116488905-187d9e80-a883-11eb-9976-5ef711719a8a.png)
did  give to you an idea to fix this error?
I'll also try it on an uncorrupted phone

**Comment by bkerler** [comment]
Skipresponse should only be used for old msm. For normal operation mode, it won't work.

**Comment by CyberMan571** [comment]
[skipresponse- usb IO error 5.pcapng.zip](https://github.com/bkerler/edl/files/6533507/skipresponse-.usb.IO.error.5.pcapng.zip)
Hey Dear Bkerler 
I put it 
Please on your available time,  can you look at!

**Comment by bkerler** [comment]
I had a look at the log, and the edl software seems to work fine, but it looks like your gpt table might be broken.
