### ISSUE TITLE
qfil [Errno 110] Operation timed out! and fixing gpt table

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#82]
![image](https://user-images.githubusercontent.com/30759335/116486918-40b6ce80-a87e-11eb-92f0-098884eb3a7e.png)
[(qfil)log.txt](https://github.com/bkerler/edl/files/6395549/qfil.log.txt)
[Errno 110] Operation timed out
how to solve timed out!

**Comment by CyberMan571** [comment]
Thanks
me is what it shows on !
![image](https://user-images.githubusercontent.com/30759335/116476985-86b66700-a86b-11eb-9826-9af7c49d7bc1.png)

How to repair gpt! in 9008 edl mode! 
it is not showing such as a mmcblk0
phone partitions have completely erased

**Comment by CyberMan571** [comment]
![image](https://user-images.githubusercontent.com/30759335/116472232-258b9500-a865-11eb-8fb6-b2142a564927.png)
on me!
and qfil is giving same tz.mbn error.

**Comment by CyberMan571** [comment]
![journalctl-1](https://user-images.githubusercontent.com/30759335/116802041-26d7ee80-aaff-11eb-9966-eab9cb396149.png)
`/home/kali/.xsession-errors:1434:thunar-volman: There is no device with the sysfs path "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/host3/target3:0:0/3:0:0:0/block/sda".
/home/kali/.xsession-errors:1449:thunar-volman: There is no device with the sysfs path "/sys/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/host3/target3:0:0/3:0:0:0/block/sda".`

`└─$ sudo sg_map -n -i                                                                                                                                             
/dev/sg0  /dev/sdd  Seagate   Expansion         0707
/dev/sg1  /dev/sdb  SanDisk   Cruzer Blade      1.27
/dev/sg2  /dev/sdc  Generic-  SD/MMC            1.00
`
`
sudo udevadm info /sys/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/                                                                                    126 ⨯
P: /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0
E: DEVTYPE=usb_interface
E: DRIVER=qcserial
E: PRODUCT=5c6/9008/0
E: TYPE=0/0/0
E: INTERFACE=255/255/255
E: MODALIAS=usb:v05C6p9008d0000dc00dsc00dp00icFFiscFFipFFin00
E: SUBSYSTEM=usb
E: USEC_INITIALIZED=1019013879749
E: adb_user=yes
E: ID_VENDOR_FROM_DATABASE=Qualcomm, Inc.
E: ID_MODEL_FROM_DATABASE=Gobi Wireless Modem (QDL mode)
E: ID_PATH=pci-0000:00:14.0-usb-0:9:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_9_1_0
E: ID_FOR_SEAT=usb-pci-0000_00_14_0-usb-0_9_1_0
E: TAGS=:uaccess:seat:
E: CURRENT_TAGS=:uaccess:seat:
`
Hi bkerler

my gpt disk memory is not showing in dev folder 

Please help me Can I repair gpt

**Comment by CyberMan571** [comment]
@bkerler  
Actually, Reverse engineer make a person feel cool! or Reverse engineer is the cool on one's own :) I planned :+1: 
didn't you  forget us, Right?  I hope no!

**Comment by bkerler** [comment]
You need to write a correct gpt table to the first and the last sectors of the disk. Sorry, but that's no edl software issue I could fix.

**Comment by CyberMan571** [comment]
some boxes have a gpt repair option. Is it possible by developing software? 
I only have  accessing to my phone GPT by using prog_loader!  I guess, it must will be by developing software!

**Comment by CyberMan571** [comment]
I have no a box!

**Comment by CyberMan571** [comment]
yes B. Kerler  Thanks
I understood and realized

Bjoern Kerler ***@***.***>, 5 May 2021 Çar, 10:28 tarihinde
şunu yazdı:
