### ISSUE TITLE
False Detected Cpu type -it's bug

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#83]
![image](https://user-images.githubusercontent.com/30759335/116489928-a5295c00-a885-11eb-911e-92d7e597a95e.png)

`
UsbClass - [LIB]: RX:<?xml version="1.0" encoding="UTF-8" ?><data><response value="ACK" MinVersionSupported="1" MemoryName="eMMC" MaxPayloadSizeFromTargetInBytes="4096" MaxPayloadSizeToTargetInBytes="1048576" MaxPayloadSizeToTargetInBytesSupported="1048576" MaxXMLSizeInBytes="4096" Version="1" TargetName="8936" /></data>          
`

[(false det.cpu)log.txt](https://github.com/bkerler/edl/files/6395703/false.det.cpu.log.txt)

it should has been msm8939

**Comment by bkerler** [comment]
that's not a "bug", it means that your edl loader is reporting that cpu. 8936 is the same generation as 8939.
