### ISSUE TITLE
integrate mmc-utils and extra gpt options

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#84]
git.kernel.org/pub/scm/linux/kernel/git/cjb/mmc-utils.git/

Hi bkerler

Do you want add mmc-utils  cmd-options  to your project? or add gpt fs repair, gpt table fix?

**Comment by bkerler** [comment]
There already is a command to flash the gpt (./edl.py w gpt gpt.bin or ./edl.py wf gpt.bin), right now for editing the gpt table there is no support planned as there are many other tools to do that.
