### ISSUE TITLE
File "./edl.py", line 216 self.info(f"Mode detected: {mode}") SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lfluvisotto** [bkerler/edl#86]
A zenfone 5 ze620kl connected on edl mode.

![image](https://user-images.githubusercontent.com/535626/116799504-4f94bf80-aad0-11eb-8f98-5fde7e69f1bc.png)

I'm trying to execute:

./edl.py printgpt

![image](https://user-images.githubusercontent.com/535626/116799518-64715300-aad0-11eb-93af-2a7fedcec6ff.png)

Whatever the command, the message always is being the message shown above.

**Comment by CyberMan571** [comment]
@lfluvisotto 
Hi 
please run ./edl.py printgpt --debugmode
and you sure correct and check pk hash  in your memory loader's
and you make sure verified pk hash  your memory loader's
if it's bug, please wait bkerler!

**Comment by bkerler** [comment]
This means that you're not using python3, but python2. Python 2 isn't supported, get rid of it :)

**Comment by CyberMan571** [comment]
> This means that you're not using python3, but python2. Python 2 isn't supported, get rid of it :)

:+1:  :)
