### ISSUE TITLE
Motorola XT1603 - Anybody has this loader?

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#87]
Hi guys, does anybody has this loader? could create EDL mode by shorting D0+Ground.
Any Ideas of how I could get this one? 

.main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x007050e100280000 (MSM_ID:0x007050e1,OEM_ID:0x0028,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0x59b38969c8b392f173e8fa7081a1758317c14789245ea1332b2547d6fb530c33
Serial:            0x22fea600

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (007050e100280000_59b38969c8b392f1_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}

**Comment by leosol** [comment]
Suppose that some tool is capable of sending the apropriate firehose via COM port under Ms Windows. Can I capture this traffic and extract firehose?

**Comment by CyberMan571** [comment]
https://drive.google.com/file/d/1RtKhbaSQE-v1Y73t9m3YOc2TL3wxh42H/view
I found it however you must test please

**Comment by leosol** [comment]
This is the content of this firmware update. Runnig ./fhloaderparse.py did not find any loader. Am I doing something wrong?


└── Motorola_Moto_G4_Play_XT1603_Harpia_NPIS26.48-43-2_CID50_7.1.1
    ├── Credits.txt
    ├── Driver
    │   └── Official Motorola Download.url
    ├── Firmware
    │   ├── adb.exe
    │   ├── AdbWinApi.dll
    │   ├── AdbWinUsbApi.dll
    │   ├── boot.img
    │   ├── bootloader.img
    │   ├── fastboot.exe
    │   ├── flashfile.bat
    │   ├── flashfile.xml
    │   ├── fsg.mbn
    │   ├── gpt.bin
    │   ├── HARPIA_NPIS26.48-43-2_cid50_subsidy-DEFAULT_regulatory-DEFAULT_CFC.info.txt
    │   ├── logo.bin
    │   ├── motostockrom.com.url
    │   ├── NON-HLOS.bin
    │   ├── oem.img
    │   ├── recovery.img
    │   ├── regulatory_info_default.png
    │   ├── servicefile.xml
    │   ├── slcf_rev_b_default_v1.0.nvm
    │   ├── system.img_sparsechunk.0
    │   ├── system.img_sparsechunk.1
    │   ├── system.img_sparsechunk.2
    │   ├── system.img_sparsechunk.3
    │   ├── system.img_sparsechunk.4
    │   └── system.img_sparsechunk.5
    └── How to Flash.txt

**Comment by leosol** [comment]
Can I capture COM port comunication under MS Windows and than try to find the loader that was used by a box, for example?

**Comment by bkerler** [comment]
yes, you can use wireshark with usb module for that.

**Comment by Aamiraziz1980** [comment]
Couldn't find a loader, Copy loader file (ex. prog_emmc_firehose_8916.mbn )into main EDL directory and Use command : 
`./edl.py printgpt --loader=prog_emmc_firehose_8916.mbn` @
[prog_emmc_firehose_8916.zip](https://github.com/bkerler/edl/files/6429710/prog_emmc_firehose_8916.zip)

**Comment by bkerler** [comment]
You need a firehose loader specific for this device. For motorola, get the blankflash package and extract the programmer.mbn.

**Comment by bkerler** [comment]
[programmer.zip](https://github.com/bkerler/edl/files/6435612/programmer.zip)
Hopefully this one will work.

**Comment by CyberMan571** [comment]
https://www.youtube.com/watch?v=0XO_tXt92wQ
he wrote  the firmware by  blank flash

blankflash is not found!  for g4 play

**Comment by CyberMan571** [comment]
https://www.xsfirmware.com/flash-motorola-moto-g4-play-xt1603-firmware-file/
was found alternative a way however you look at for RELIABILITY! Not tested

**Comment by leosol** [comment]
Thank you for these loaders!! Will try them all in the next few days!

Em sáb., 8 de mai. de 2021 às 05:43, Said Ali ***@***.***>
escreveu:

**Comment by CyberMan571** [comment]
yeah
please you would like look at
https://forum.xda-developers.com/t/solved-unbrick-hard-bricked-dead-motorola-g-4-plus-or-any-qualcomm-mobile-device.3585016/
then try with blankflash2.zip and blankflash3.zip files. download here
<https://drive.google.com/open?id=0B3DC0oN4XXwpQjF1eDFkT2JzTlE>*
blankflash1.zip -- is for latest mobile above android lollipop,
blankflash2.zip -- for android lollipop.
blankflash3.zip -- for Kitkat devices.
please try with 1,2 and 3 in order.
*:https://drive.google.com/open?id=0B3DC0oN4XXwpQjF1eDFkT2JzTlE

Leandro Oliveira ***@***.***>, 9 May 2021 Paz, 18:25
tarihinde şunu yazdı:

**Comment by CyberMan571** [comment]
yeah
please you would like look at
https://forum.xda-developers.com/t/solved-unbrick-hard-bricked-dead-motorola-g-4-plus-or-any-qualcomm-mobile-device.3585016/
then try with blankflash2.zip and blankflash3.zip files. download here*
blankflash1.zip -- is for latest mobile above android lollipop,
blankflash2.zip -- for android lollipop.
blankflash3.zip -- for Kitkat devices.
please try with 1,2 and 3 in order.
*:https://drive.google.com/open?id=0B3DC0oN4XXwpQjF1eDFkT2JzTlE

**Comment by leosol** [comment]
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x007050e100280000 (MSM_ID:0x007050e1,OEM_ID:0x0028,MODEL_ID:0x0000)
CPU detected:      "MSM8916"
PK_HASH:           0x59b38969c8b392f173e8fa7081a1758317c14789245ea1332b2547d6fb530c33
Serial:            0x22fea600

sahara - Uploading loader /mnt/temp0/programmer/programmer.mbn ...
Successfully uploaded programmer :)
firehose
firehose - [LIB]: Nop failed.
firehose - No supported functions detected, configuring qc generic commands
firehose - 
firehose_client - Target detected: MSM8916
firehose_client - Based on the chipset, we assume eMMC as default memory type...
firehose - TargetName=
firehose - MemoryName=eMMC
firehose - Version=

It stopped right on printing "Version" field. I't hangs in a read command. Might be the case that this loader does not implement firehose xml protocol?
[log.txt.gz](https://github.com/bkerler/edl/files/6473852/log.txt.gz)
[stdin.log.gz](https://github.com/bkerler/edl/files/6473853/stdin.log.gz)

**Comment by bkerler** [comment]
According to the log, the device doesn't answer after sending the firehose loader :(

**Comment by bkerler** [comment]
I've just ordered a xt1603 and will have a closer look.

**Comment by leosol** [comment]
Hi, I would like to thank you and say that I'm trying to find and test as many smartphons I can!
Sorry about closing the issue! Thanks once again for the help!

**Comment by CyberMan571** [comment]
Please  can wait leosol 
I will tryit unpack loader mbn from file. if I found it and I will send you

**Comment by CyberMan571** [comment]
Please  can wait leosol 
I will tryit unpack loader mbn from file. if I found it and I will send you

Edit:
Unfortunately  it is owned a MSM8952  cpu!  it has been  XT1640, XT1641, XT1642, XT1643, XT1644 :)

**Comment by CyberMan571** [comment]
Working Blank flash not available for model try to boot repair with professional boxes don't forget to take Cid partition 
found such info while searching!
I search though long time however   nothing   found

**Comment by CyberMan571** [comment]
@bkerler 
 **Working Blank flash not available for model try to boot repair with professional boxes don't forget to take Cid partition** 
 
 I took out the following statement from this information! 
 possibilities:
 1.They are reaching the phone's data without the need for programmer.mbn.
 2. These (people) have be able to pull MBN files from the phone!
 
 I can't help this on the moment! I hope I can do in the future! (Edited)Restore original

**Comment by bkerler** [comment]
@leosol How did you enter edl mode ?

**Comment by leosol** [comment]
Just short this two points in this image and plug usb cable. This trick works for many Motorolas.
![400px-Aproximacao-edl-xt1603](https://user-images.githubusercontent.com/4167122/120889052-ce01e700-c5d1-11eb-91f8-fd5fd6990f36.png)

**Comment by bkerler** [comment]
I just flashed lineageos, then "adb reboot edl" worked fine. The main issue is:
The moto g4 loader is fine. But it doesn't support firehose, only streaming mode.
As the device isn't unfused but fused and signed, it means we cannot patch the nand loader to add
read. The only thing that might work is to write, sorry :(

**Comment by leosol** [comment]
Thank you for understanding and sharing this information. At least, for the samples I've got, it seems to be unencrypted and reading could be very helpfull to data recovery.

**Comment by bkerler** [comment]
Sorry, I also couldn't find a working edl loader. Closing this issue now.
