### ISSUE TITLE
All the Sahara errors are in error?

### ISSUE THREAD

**Issue by RenateUSB** [bkerler/edl#89]
In sahara.py:
All the comments in class status are vertically off by one.
All the strings in ErrorDesc are vertically off by one.

**Comment by bkerler** [comment]
Actually no. It's intentional as it belongs to class sahara.

**Comment by RenateUSB** [comment]
Seriously? This makes sense to you?
`SAHARA_STATUS_SUCCESS = 0x00  # Invalid command received in current state`

I would have written:
`SAHARA_STATUS_SUCCESS = 0x00  # Whatever you did last succeeded. Congratulations!`

**Comment by bkerler** [comment]
I see what you mean, sorry for the misunderstanding. I will push a fix tonight.
