### ISSUE TITLE
About reading RPMB data

### ISSUE THREAD

**Issue by fxsheep** [bkerler/edl#9]
First of all , thanks for this tool as it is the only one I have seen to have the possibility to read bootrom and qfuses. I have a question, since many loaders run in EL3 and support peeking qfuses, while the RPMB provision keys were blown into these regions, is it possible to read out the key and gain access to data stored on EMMC/UFS rpmb storage?

**Comment by bkerler** [comment]
No, as this region is read protected in qfprom.

**Comment by fxsheep** [comment]
Thanks for your reply.
