### ISSUE TITLE
pull  Correct gpt_main0.bin  and to find start lba  and Lba number for gpt_main0.bin

### ISSUE THREAD

**Issue by CyberMan571** [bkerler/edl#90]
Hi who likes  help to everyone
these are problem  gpt_main0.bin  and   gpt_backup0.bin 

```
<program SECTOR_SIZE_IN_BYTES="512" file_sector_offset="0" filename="gpt_main0.bin" label="PrimaryGPT" num_partition_sectors="34" partofsingleimage="true" physical_partition_number="0" readbackverify="false" size_in_KB="17.0" sparse="false" start_byte_hex="0x0" start_sector="0"/>
<program SECTOR_SIZE_IN_BYTES="512" file_sector_offset="0" filename="gpt_backup0.bin" label="BackupGPT" num_partition_sectors="33" partofsingleimage="true" physical_partition_number="0" readbackverify="false" size_in_KB="16.5" sparse="false" start_byte_hex="(512*NUM_DISK_SECTORS)-16896." start_sector="NUM_DISK_SECTORS-33."/> 
```

hex start sector=(512*NUM_DISK_SECTORS)-168961
decimal start sector number "NUM_DISK_SECTORS-33."
how can convert hex disk sector to decimal number?
example of  1638407 start sector to hex lba start adress ?

I need to lba start address and lba number for them
Total disk size:0x00000003ab800000, sectors:0x0000000001d5c000  

it is not correctly pulled  gpt_main0.bin  and   gpt_backup0.bin

**Comment by bkerler** [comment]
If you use the qfil option, this field will be calculated automatically.

**Comment by bkerler** [comment]
Remember to flash the main gpt first using wf option

**Comment by CyberMan571** [comment]
Thanks bkerler 👍 ;)
Firstly, need I pull gpt-backup0.bin and gpt_main0.bin from  the same but  un-corrupted phone! existented at my hand!
info:existented  "gpt tables bin files"  returns  error "read verify failed".
info:using rl  option, I pulled  complete memory without userdata however gpt_main0.bin size is about(approximately) 5.04kb.

**Comment by CyberMan571** [comment]
@bkerler  Hey Master Captain
Read back verify failed can be a bad sector in emmc!  How to Fix it? how can capture needed info for debug?

**Comment by bkerler** [comment]
That's weird. It says Read back verify failed at sector -1449978330. This doesn't make any sense, as the log clearly says write to offset 0.

**Comment by CyberMan571** [comment]
https://www.youtube.com/watch?v=o6EpM7mKVr0
https://youtu.be/OTyWy-z7EfU?t=473
Hey Master bkerler 
Please  can watch videos!
these video makers   flashed  firmware using  extcsd.bin 
Or may extcsd.bin be used with another filename?
Also, videos can be useful in improving your program! at least it can give an idea! 
very important info:
I deleted the phone's partitions with minitools PM.
Windows was detecting it as an external disk. 
GP1 GP2 GPP3 GPP4 
If I create them, will it be okay?

**Comment by CyberMan571** [comment]
https://www.youtube.com/watch?v=o6EpM7mKVr0
https://youtu.be/OTyWy-z7EfU?t=473
Hey Master bkerler 
Please  can watch videos!
these video makers   flashed  firmware using  extcsd.bin 
Or may extcsd.bin be used with another filename?
Also, videos can be useful in improving your program! at least it can give an idea! 
very important info:
I deleted the phone's partitions with minitools PM.
Windows was detecting it as an external disk. 
GPP1 GPP2 GPP3 GPP4 
If I create them, will it be okay?

**Comment by CyberMan571** [comment]
@bkerler 
`CID partition contains device unique HW ID, IMEI, etc... with certs and signature/hash. Each CID partition is device unique, you will need original backup otherwise need to send to factory for reprogram.`
Could CID partition ID have suffered some kind of damage?

**Comment by bkerler** [comment]
Actually the problem seems to be your gpt, not my edl tool. Closing this issue for now.

**Comment by CyberMan571** [comment]
Thanks bkeler
gpt_both0.bin and partition.bin give the same error, but the sector number is different! for only tested
I'm not saying it has has error your edl tool. 
I wanted to refer to your knowledge because it seemed strange to me. 
I will buy edl flash cable from china, and I will try it that way.
