### ISSUE TITLE
windows 10 issues

### ISSUE THREAD

**Issue by xerootg** [bkerler/edl#92]
Thanks for the tool, I've been poking at my palm phone with it with awesome luck on my Mac!

I was having a heck of a time getting this running on a very recent win 10 build after installing libusb via zadig. 

I kept getting the following stacktrace no matter the command:

> Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
> main - Trying with no loader given ...
> main - Waiting for the device
> Traceback (most recent call last):
>   File "C:\Users\johnp\edl\edl.py", line 368, in <module>
>     base.run()
>   File "C:\Users\johnp\edl\edl.py", line 264, in run
>     mode, resp = self.doconnect(loop, mode, resp)
>   File "C:\Users\johnp\edl\edl.py", line 186, in doconnect
>     self.cdc.connected = self.cdc.connect()
>   File "C:\Users\johnp\edl\Library\usblib.py", line 217, in connect
>     self.device = usb.core.find(idVendor=vid, idProduct=pid)
>   File "C:\Users\johnp\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\core.py", line 1299, in find
>     raise NoBackendError('No backend available')
> usb.core.NoBackendError: No backend available

While digging through usblib for a bit, I ran across this note:
https://github.com/pyusb/pyusb/issues/215#issuecomment-691434667

I'm sure I'm not the only person wanting to use this on Windows ;)

**Comment by RenateUSB** [comment]
Do you actually have libusb-1.0.dll in \Windows\System32 or \Windows\SysWOW64?

**Comment by xerootg** [comment]
You know, I have no idea if I _had_ to do that, but I did and things just
worked.

**Comment by bkerler** [comment]
Yeah ... windows is sometimes strange.
