### ISSUE TITLE
MSM8909w

### ISSUE THREAD

**Issue by boystyle2010** [bkerler/edl#93]
Hi, please support Snapdragon Wear 3100 MSM8909w unlock bootloader ! Thank

**Comment by bkerler** [comment]
Sorry, I don't have any loaders for this device nor do I own it. But if you want support for it, you need to provide more details and an edl loader.

**Comment by boystyle2010** [comment]
> if

I am using MSM8909w device and what do I need to get the information provided to you?

**Comment by MagneFire** [comment]
@boystyle2010 Just an FYI, there is actually an MSM8909W firehose image for the Huawei Watch 2, you can find it here: https://forum.xda-developers.com/t/rom-bootloader-recover-huawei-watch-2-bt-leo-b09-leo-bx9.3624657/
(Don't know anything about this all, just saw this issue from the Mi Watch Telegram group)

**Comment by bkerler** [comment]
@boystyle2010 what model and vendor do you use ? Try to search a qfil update package and extract the firehose programmer from it.
