### ISSUE TITLE
downgrade my android version on my device from android 10 to android 8.

### ISSUE THREAD

**Issue by anshu-attri2327** [bkerler/edl#94]
I want downgrade my android version on my device from android 10 to android 8.

I have this device:

SH-01L tech specs
5.5" display 1080x2160
RAM 3GB
ROM 32GB
Original Android Version when launched: 8.1
Processor: Snapdragon 450
Micro SD slot up to 512GB
USB Type C port
Supports NFC

It's bootloader is locked and only edl and recovery mode is available, recovery has only wipe/reset and reboot option. 

I have tried to connect the phone to qfil in edl mode but the COM port is 9008 with emmc storage type.
I want to pull the recovery so that i can create a twrp for this device and also the rom so i can flash the android 8 rom to the device with android 10 right now.

**Comment by bkerler** [comment]
Sorry, but this is no issue of my tool EDL. Please ask such things in appropriate forums like xda-developers.
