### ISSUE TITLE
Couldn't find a loader for given hwid and pkhash

### ISSUE THREAD

**Issue by shdbwa** [bkerler/edl#95]
I am getting this error with a Crosscall Core-x3, detected as: 
**_05c6:9008 Qualcomm, Inc. Gobi Wireless Modem (QDL mode)_**
I don't own the specific FHPRG/ENPRG for this device, so I tried with:
**_0004f0e100000000_7c6dca9bf5674291_fhprg_peek.bin_**
Cause of the pk_hash
I tried with some others 8917 hisense and qualcom, factory, with no luck ! 

```
Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara -
------------------------
HWID:              0x000560e100430000 (MSM_ID:0x000560e1,OEM_ID:0x0043,MODEL_ID:0x0000)
CPU detected:      "MSM8917"
PK_HASH:           0x7c6dca9bf5674291aa39dd55760c0d4b65c7a4223097aab1db791e2192002ddf
Serial:            0xffff0000

sahara
sahara - [LIB]: Couldn't find a loader for given hwid and pkhash (000560e100430000_7c6dca9bf5674291_[FHPRG/ENPRG].bin) :(
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0,'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}
```

**Comment by cjcharles0** [comment]
I get a similar thing on a Pixel 3.... Ive tried your latest commits but I may well be missing something as this is all new to me. Happy to help if needed/useful:

```
edl.py reset
Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara -
------------------------
HWID:              0x0008b0e100420004 (MSM_ID:0x0008b0e1,OEM_ID:0x0042,MODEL_ID:0x0004)
CPU detected:      "SDM845"
PK_HASH:           0xe693a06f0c0e7e610dff09371f1c8077c5eb1bde02e7ad1da99b8c45117f8f32
Serial:            0xb370928a

sahara
sahara - [LIB]: ←[31mCouldn't find a loader for given hwid and pkhash (0008b0e100420004_e693a06f0c0e7e61_[FHPRG/ENPRG].bin) :(←[0m
Device is in an unknown sahara state, resetting
resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}
```

**Comment by bobbintb** [comment]
> I get a similar thing on a Pixel 3.... Ive tried your latest commits but I may well be missing something as this is all new to me. Happy to help if needed/useful:
> 
> ```
> edl.py reset
> Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
> main - Trying with no loader given ...
> main - Waiting for the device
> main - Device detected :)
> main - Mode detected: sahara
> Device is in EDL mode .. continuing.
> sahara -
> ------------------------
> HWID:              0x0008b0e100420004 (MSM_ID:0x0008b0e1,OEM_ID:0x0042,MODEL_ID:0x0004)
> CPU detected:      "SDM845"
> PK_HASH:           0xe693a06f0c0e7e610dff09371f1c8077c5eb1bde02e7ad1da99b8c45117f8f32
> Serial:            0xb370928a
> 
> sahara
> sahara - [LIB]: ←[31mCouldn't find a loader for given hwid and pkhash (0008b0e100420004_e693a06f0c0e7e61_[FHPRG/ENPRG].bin) :(←[0m
> Device is in an unknown sahara state, resetting
> resp={'cmd': 1, 'len': 48, 'version': 2, 'version_min': 1, 'max_cmd_len': 1024, 'mode': 0, 'res1': 0, 'res2': 0, 'res3': 0, 'res4': 0, 'res5': 0, 'res6': 0, 'object_size': 48, 'raw_data': bytearray(b'\x01\x00\x00\x000\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')}
> ```
> 
> EDIT: Phone was not flashed or anything, just suddenly turned off and would not turn back on.... (tried all the button hold/charge combos)

I have this exact issue. Same thing happened to me. Near as I can tell, you need the loader file for the Pixel 3. So far I have turned up nothing but I'm still looking.

**Comment by shdbwa** [comment]
I've mailed Hisense (bootloader), and they, ofc, never answered.

**Comment by mcdoe** [comment]
try the following things: 1. check if the vendor added security for your phone's chipset (many vendors, like LG, add their own layer of security for the MSM8917, in which case, you're out of luck)
2. run the tool with --debug flag.
