### ISSUE TITLE
Redmi Note 5 (M1803E7SG) any ideas of a different loader?

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#96]
Qualcomm Sahara / Firehose Client V3.3 (c) B.Kerler 2018-2021.
main - Trying with no loader given ...
main - Waiting for the device
......
main - Hint:   Press and hold vol up+dwn, connect usb. For some, only use vol up.
main - Xiaomi: Press and hold Vol up + pwr, in fastboot mode connect usb.
        Run "./fastboot oem edl".
main - Other:  Run "adb reboot edl".

...main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 
------------------------
HWID:              0x000cc0e100000000 (MSM_ID:0x000cc0e1,OEM_ID:0x0000,MODEL_ID:0x0000)
CPU detected:      "SDM636"
PK_HASH:           0xa7b8b82545a98eca23d6e9105fb464568d1b5828264903441bdef0cd57e3c370
Serial:            0x2b700888

sahara - Trying loader: Loaders/qualcomm/factory/sdm636/000cc0e100000000_7be49b72f9e43372_fhprg_bqx2_peek.bin
sahara - Uploading loader Loaders/qualcomm/factory/sdm636/000cc0e100000000_7be49b72f9e43372_fhprg_bqx2_peek.bin ...
sahara
sahara - [LIB]: Unexpected error on uploading, maybe signature of loader wasn't accepted ?
'int' object is not subscriptable                                                                                                                                     
No suitable loader found :(

**Comment by bkerler** [comment]
You will have to search for firmware packages containing the firehose programmer, sorry.
