### ISSUE TITLE
Error Oneplu param & firehose LIB

### ISSUE THREAD

**Issue by thexihad** [bkerler/edl#98]
![Screenshot (2)](https://user-images.githubusercontent.com/52651148/120114251-26009f80-c133-11eb-92c7-00ebcbd7b2ce.png)
............main - Device detected :)
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara -
------------------------
HWID:              0x009470e100310000 (MSM_ID:0x009470e1,OEM_ID:0x0031,MODEL_ID:0x0000)
CPU detected:      "MSM8996"
PK_HASH:           0x2cf7619a278d26073f7eea79bb7f4b7949c221487fea058ea072cffe38ce1496
Serial:            0xe895007b

sahara - Detected loader: Loaders\009470e100310000_2cf7619a278d2607_[FHPRG].bin
sahara - Uploading loader Loaders\009470e100310000_2cf7619a278d2607_[FHPRG].bin ...
Successfully uploaded programmer :)
firehose - Nop succeeded.
firehose - Chip serial num: 3902079099 (0xe895007b)
oneplus
oneplus - [LIB]: No module named 'Library.Modules.oneplus_param'
firehose -
firehose_client - Target detected: MSM8996
firehose
firehose - [LIB]: <?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="fh.attrs.MaxPayloadSizeToTargetInBytes of 1048576 > fh.channel_buffer_capacity of 4096"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="Calling usb_al_bulk_set_zlp_mode(TRUE) since ZlpAwareHost='1'"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="Calling hotplug_poll_device('UFS')"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="Storage device of type 'UFS' cannot be opened"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="storage_device_open() returned FALSE"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<log value="ERROR 13: Line 1142: HANDLE_CONFIGURE_FAILURE"/>
</data><?xml version="1.0" encoding="UTF-8" ?>
<data>
<response value="NAK" />
</data>

I am using lg v20.

**Comment by bkerler** [comment]
Hi, you need to use --memory=emmc as option as your device doesn't seem to have UFS flash.

**Comment by thexihad** [comment]
I am following this Guide (https://forum.xda-developers.com/t/guide-lg-v20-hard-unbrick.4244283/#_=_) . He says he has the same device that I have . And he did not have any problem. He said He used linux. But python should work the same way in  Windows Right??. I followed all his steps but the last steps where i have to flash the files ends with this error I mentioned . My only smartphone is bricked now. Can you please help?? my device is LG v20 vs995

**Comment by bkerler** [comment]
Actually using windows is always problematic as the libusb support under windows is very very bad. I strongly recommend to use linux or mac. Regarding your device, if you made a backup, it can be revived easily, if not, it depends what you messed up. Sometimes, having the same device doesn't mean that it was updated to the same os version. So replacing a critical partition that doesn't match the same os version will lead in a "brick" unless you flash again the right partitions. But the good thing about edl is: you never really brick the device.

**Comment by thexihad** [comment]
Okay Bro I will try it on linux and let you know.
