### ISSUE TITLE
Motorola XT1683 (Moto G5 Plus) - hangs with input / output error

### ISSUE THREAD

**Issue by leosol** [bkerler/edl#99]
main - Mode detected: sahara
Device is in EDL mode .. continuing.
sahara - 

HWID:              0x000460e103680000 (MSM_ID:0x000460e1,OEM_ID:0x0368,MODEL_ID:0x0000)
CPU detected:      "MSM8953"
PK_HASH:           0xba3906237561c8b39e65cf354ce65ef7626026f3d69a10e4a3ce54ed3468deee
Serial:            0x7a6e79dbsahara - Detected loader: Loaders/lenovo_motorola/000460e103680000_ba3906237561c8b3_fhprg_peek.bin
sahara - Uploading loader Loaders/lenovo_motorola/000460e103680000_ba3906237561c8b3_fhprg_peek.bin ...
Successfully uploaded programmer :)
firehose - Nop succeeded.
firehose - 
firehose_client - Target detected: MSM8953
firehose_client - Based on the chipset, we assume eMMC as default memory type...
firehose - TargetName=
firehose - MemoryName=e

MMC
firehose - Version=
USBError(5, 'Input/Output Error') <class 'usb.core.USBError'> 5

**Comment by leosol** [comment]
Any ideas? USB stops responding.... 
[stdin.txt.gz](https://github.com/bkerler/edl/files/6570234/stdin.txt.gz)
[log.txt.gz](https://github.com/bkerler/edl/files/6570235/log.txt.gz)

**Comment by bkerler** [comment]
The device responds with : "<?xml version="1.0" encoding="UTF-8" ?><data><log value="This version of programmer has been revoked!" /></data>" which means that the programmer you are using is older than the current device version and thus not accepted due to rollback protection I assume.

**Comment by leosol** [comment]
Nice to know! Would it be easy to show some info message with this hint?
Informing that the programmer might be older?

Em sex., 4 de jun. de 2021 às 11:35, Bjoern Kerler ***@***.***>
escreveu:

**Comment by bkerler** [comment]
Yes, I will try to improve the output :)
